"""Seal native12 R4 pull-up geometry with full support and remaining gaps explicit."""
import json,pathlib,hashlib,shutil,datetime
H=pathlib.Path(__file__).resolve().parent;R=H.parents[1];D=H/'candidate02';S=R/'candidate55'
read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();write=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n')
h=sha(D/'f722-heli.kicad_pcb');sh=sha(S/'f722-heli.kicad_pcb');assert h=='9d9f2f39c2b200f2c928dd3123f098797eb86ba56cb943d7f6e3fe89bf264a7e'
s=read(D/'owner-summary.json');assert s['board_sha256']==h and s['drc']==s['drc-all']==dict(unconnected=12,errors=0,warnings=0)
for k in ['process','mechanical','parity','firmware']:assert s[k]['passed']and s[k]['board_sha256']==h
assert s['critical']['connected_nets']==16 and not s['critical']['faults']and not s['critical']['missing_ground_returns']
assert not read(D/'owner-drc-parity.json')['schematic_parity'];assert not any(x.get('violations')for x in read(D/'owner-erc.json').get('sheets',[]))
for f in ['entry-support-audit.json','power-audit.json','endpoint-audit.json','native-coordinated-integration.json','stock-spi-binding.json']:
 q=read(D/f);assert q['passed']and q['board_sha256']==h
p=read(D/'construction-provenance.json');audit=read(D/'entry-support-audit.json');assert len(p['removed_source_records'])==0 and len(p['added_records'])==15 and len(p['changed_pad_records'])==2 and len(p['changed_footprint_records'])==1
assert audit['new_track_endpoints_checked']==26 and len(audit['nets'])==28 and len(audit['signal_groups'])==2
assert audit['deliberate_C15_feed_contact']['C14_pad_overlap_mm2']==audit['deliberate_C15_feed_contact']['C15_lead_contact_outside_actual_pad_mm2']==0
assert audit['reconstructed_CORE_junction']['full_width_join']['passed'] and audit['reconstructed_CORE_junction']['actual_C3_entry']['passed']
c=read(D/'protection-actual-io.json');b=read(S/'protection-actual-io.json');passed=lambda x:{r['id']for r in x['checks']if r['complete_clamp_first_path_passes']};assert c['passed']==b['passed']==20 and c['total']==22 and passed(c)==passed(b)
ref=read(D/'reference-comparison55.json');assert ref['critical_object_geometry_identical']
project=read(D/'project-input-preservation.json');assert all(sha(D/x['path'])==x['sha256']==sha(S/x['path'])for x in project['files'])
nets=['+3V3_CORE','FLASH_CS'];ledger=read(D/'native-length-ledger.json')
write(D/'coordinated-change-receipt.json',dict(schema='f722-R4-pullup-complete-native-reconstruction55/v1',source_board_sha256=sh,board_sha256=h,changed_nets=nets,removed_source_objects=[],added_objects=p['added_records'],changed_pad_records=p['changed_pad_records'],footprint_transforms='declared-footprint-transforms.json',all_other155_full_footprints_exact=True,all_source_track_via_arc_objects_retained=True,all28_support_groups_preserved=True,complete_R4_pullup_to_U3_branch=True,FLASH_CS_MCU_link_still_open=True,reconstructed_CORE_junction=audit['reconstructed_CORE_junction'],deliberate_C15_contact=audit['deliberate_C15_feed_contact'],raw_constructor_pending_flags_superseded_by_these_native_gates=True,numerical_power_VCAP_qualified=False,signal_quality_qualified=False,reference_AC_qualified=False,owner_adoption_claimed=False))
limits=['Geometric prototype checkpoint; independent owner adoption pending.','The actual U1.33 FLASH_CS connection remains open. Only the complete U3.1-to-R4.2 pull-up branch closes, reducing native opens from13 to12.','The new FLASH_CS branch is13.999707308mm of trace with two ordinary through vias. Edge/loading/27MHz and startup behavior require source-bound electrical review.','The new .20mm CORE feed terminates deliberately at actual C15.1,4.335mm long; original C14/C15/U3 supply/return copper and all other source copper remain exact.','The original R4 pad also joined a parallel CORE feed. A complete new .20mm,1.835755975mm bridge from its retained leaf endpoint to actual C3.1 replaces that current-carrying role. No partial overlap is used as its proof.','FLASH_CS has a minimum nominal copper-rule surplus of about1.055micrometers at a retained HOLD via in the finite screen. This is legal CAD geometry, not a manufacturing robustness claim.','All86-net saved-reference review, analog/ESD and fresh numerical power/VCAP remain pending. Raw critical refill deltas are retained without thresholds.','Candidate01 is a historical diagnostic with incidental C14/C15 supply contacts; its geometry is not imported into this successor.']
write(D/'checkpoint-limits.json',dict(board_sha256=h,limits=limits,raw_critical_reference_deltas=ref['net_numeric_deltas_after_minus_before'],native_length_ledger='native-length-ledger.json'))
(D/'README.md').write_text('''# R4 pull-up native checkpoint from accepted55

The saved board has 12 opens, zero native errors and zero warnings. R4 moves from B(27.5,19.8),180 degrees to B(40.55,19),180 degrees, preserving its 10k/1% value and actual pad/net identities. Its complete U3.1 pull-up branch is connected; the MCU U1.33 FLASH_CS gap remains open. Remaining gaps are PORT_C 5, BOOT 2, RED 1 and flash 4.

The transaction adds 13 tracks and two ordinary tented vias, removes no source copper, and changes only R4's two pads and full footprint pose. The .20 mm R4 supply lead deliberately ends at actual C15.1. It has zero overlap with C14.1, and its contact to the retained C15 lead is wholly inside the actual C15.1 pad. The original R4 pad's parallel CORE-feed junction is restored by a separate .20 mm full-width bridge to actual C3.1. Every original power, ground and other track/via remains exact.

Native DRC, schematic parity, ERC, firmware, mechanical and process checks pass. All 16 critical groups, 26 finite new endpoints, 28 supply/ground groups and all 20 previously passing actual I/O protection cases are preserved. The actual FLASH_CS pad partition changes from three groups to two; no other pad partition changes. Read the source-bound entry/support audit and coordinated integration receipt.

The native pull-up branch measures 13.999707308 mm plus two via barrels; source-bound edge/loading and power review remain pending. Raw saved-reference deltas are preserved. This is a geometric checkpoint for owner review, not an electrically qualified release.
''')
for name in ['construct_R4_pullup_native55_v2.py','audit_R4_pullup_native55_v2.py','extra_R4_pullup_native55_v2.py','measure_R4_pullup_native55_v2.py','seal_R4_pullup_native55_v2.py']:
 shutil.copy2(H/name,D/(pathlib.Path(name).stem+'.used.py'))
shutil.copy2(R/'tests/servo48/validate_checkpoint.py',D/'validate_checkpoint.used.py')
E=D/'bound-receipts';E.mkdir(exist_ok=True)
for name in ['R4-east-RED-complete55.json','R4-retained-parallel-feed55.json','CS-entry-preserve-C55.json','R4-C15-deliberate-terminal55.json']:
 shutil.copy2(H/name,E/name)
ties=read(D/'reference-snapshot/critical-reference.json')['GND_ties']
hand=dict(schema='f722-native-route-handoff/v1',status='sealed_native_12_open_complete_R4_pullup_branch_geometric_checkpoint_pending_owner_review',sealed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),board_sha256=h,integration_source_sha256=sh,native_sha256=sha(D/'f722-heli.native.json'),drc=dict(unconnected=12,errors=0,warnings=0,strict_schematic_parity=0,ERC_violations=0),remaining_gap_accounting=dict(PORT_C=5,BOOT=2,RED=1,flash=4),pose_reference=str((D/'poses-native.json').relative_to(R)),declared_footprint_transforms='declared-footprint-transforms.json',coordinated=True,allowed_changed_nets=nets,all_other155_full_footprints_exact=True,all_source_track_via_arc_objects_retained=True,removed_source_objects=0,added_native_objects=15,new_tracks=13,new_vias=2,finite_new_endpoints=26,support_groups_preserved=28,completed_branch=['U3.1','R4.2'],incomplete_FLASH_CS_terminal='U1.33',actual_IO_cuts_passed=20,actual_IO_contracts=22,actual_IO_passes_exactly_preserved=True,critical_object_geometry_identical=True,raw_critical_reference_deltas=ref['net_numeric_deltas_after_minus_before'],all_signal_reference_owner_review_pending=True,ground_ties_to_both_saved_planes=len(ties['accepted']),rejected_ground_ties=len(ties['rejected']),native_length_ledger='native-length-ledger.json',limits_file='checkpoint-limits.json',signal_quality_qualified=False,reference_AC_qualified=False,protection_transient_qualified=False,numerical_power_VCAP_qualified=False,owner_adoption_pending=True)
hand['files']={str(f.relative_to(D)):sha(f)for f in sorted(D.rglob('*'))if f.is_file()and f.name!='route-handoff.json'};write(D/'route-handoff.json',hand);assert all(sha(D/k)==v for k,v in hand['files'].items());print(json.dumps(dict(board_sha256=h,handoff_sha256=sha(D/'route-handoff.json'),files=len(hand['files']),status=hand['status'])))
