#!/usr/bin/python3
"""Close the exact R140 delta and current-source native/contact regression."""
import copy,hashlib,json,xml.etree.ElementTree as ET
from pathlib import Path
D=Path(__file__).resolve().parents[1];F=Path(__file__).resolve().parent;B=D/'final-3c80eba2';P=Path('/workspace/shared/storm32-redesign/controller-r3s-p6');PAD=D.parent/'controller-r3s-p6-pad-attachment-audit';H='cf16a6f5ceae65aad217e29eef23a60dbc8f15af743b363df03aa5a42c9c71dc';sha=lambda q:hashlib.sha256(q.read_bytes()).hexdigest();read=lambda q:json.loads(q.read_text());base=read(B/'complete-source-qualification.json');report=copy.deepcopy(base);errors=[]
def check(ok,msg):
 if not ok:errors.append(msg)
full=read(F/'native-gate-summary.json');geo=read(F/'revision-geometry.json');top=read(F/'topology.json');replay=read(F/'route-replay.json');quality=read(F/'route-quality/route-quality-comparison.json');delta=read(D/'r140-final-delta/exact-delta.json');joins=read(D/'join-throats-cf16a6f5.json');via=read(D/'all-via-attachments-cf16a6f5.json');functional=read(D/'all-via-functional-layer-roles-cf16a6f5.json');trees=read(D/'pad-anchored-dead-trees-cf16a6f5.json');cleanup=read(D/'authorized-pruning-cf16a6f5.json');padfloor=read(D/'r140-final-delta/pad-floor.json');padnom=read(D/'r140-final-delta/pad-nominal.json')
for name,doc in [('native',full),('geometry',geo),('topology',top),('replay',replay),('exact delta',delta),('joins',joins),('via',via),('functional vias',functional),('dead trees',trees),('cleanup',cleanup)]:
 check(doc['candidate_sha256']==H,name+' source hash differs');check(not doc.get('errors'),name+' errors')
check(full['status'].startswith('PASS') and full['source_stable'] and not any(full['native_counts'].values()),'Final stable native gate failed');check(delta['status']=='PASS EXACT R140-ONLY DELTA' and delta['all_other_native_semantics_unchanged'],'Delta exceeds authorized R140 route');check(not joins['narrow_local_join_flags'],'New narrow joint');check(not via['new_or_worsened_shallow_groups'] and not via['inherited_or_improved_shallow_groups'],'Shallow via attachment');check(via['disappeared_via_layer_contacts']==read(D/'all-via-attachments-3c80eba2.json')['disappeared_via_layer_contacts'],'Via contact retirement differs from approved source');check(functional['via_count']==406 and functional['ground_vias']==97 and not functional['one_layer_or_zero_layer_review'],'Meaningless via found');check(not trees['review_trees'] and trees['peeled_via_count']==0,'Exposed dangling tree found')
for mode,doc in [('floor',padfloor),('nominal',padnom)]:
 prior=read(PAD/('final-3c80eba2-'+mode+'.json'));check(doc['sha256']==H and doc['profiles']==prior['profiles'],'Pad '+mode+' profile differs from independently qualified source')
check(padfloor['counts']['failed_groups']==0,'Pad floor failure');check(delta['direct_pad_attachment_geometry_unchanged'],'Pad geometry carry-forward invalid');check(all(q['loss_mm2']==q['gain_mm2']==0 for q in delta['filled_zone_deltas']),'Ground-plane/pad attachment carry-forward invalid');check(base['pad_attachments']['unresolved_functional_nominal_advisories']==0,'Prior pad disposition unresolved')
negative=read(D/'join-throats-p5-constructive.json');check(negative['audit_script_sha256']==joins['audit_script_sha256']==sha(D/'audit_copper_join_throats.py'),'Negative and final join methods differ')
# Exactly four source bytesets differ from the previous qualified source map.
changed=sorted(path for path,h in base['export_guard_source_sha256'].items() if sha(Path(path))!=h)
expected=sorted(str(P/q) for q in ['controller.kicad_pcb','tools/render_p6_review.py','review/printed-pad-legend.json','review/approved-small-vias.json']);check(changed==expected,'Unexpected source delta from3c80: '+str(changed));oldhelper=(B/'cli-snapshot/tools/render_p6_review.py').read_text();newhelper=(P/'tools/render_p6_review.py').read_text();check(oldhelper.count('ASSEMBLY NOT CLEARED')==1 and newhelper==oldhelper.replace('ASSEMBLY NOT CLEARED','PCBA production approval required'),'Report helper differs beyond exact footer string')
for path,h in full['source_sha256'].items():check(sha(Path(path))==h,'Source changed during final closure: '+path)
check(sha(P/'controller.kicad_pcb')==H,'Main PCB changed')
# Preserve the already normalized XML because all seven schematic bytes are fixed.
xml=P/'review/controller-netlist.xml';fresh=F/'cli-snapshot/review/controller-netlist.xml';check(sha(xml)==base['metadata_closure']['current_main_XML_sha256'],'Qualified current XML changed');sheets=list(P.glob('*.kicad_sch'));check(len(sheets)==7 and all(sha(q)==base['export_guard_source_sha256'][str(q)] for q in sheets),'Schematic source bytes changed');x,y=ET.parse(xml).getroot(),ET.parse(fresh).getroot();electrical={k:ET.tostring(x.find(k))==ET.tostring(y.find(k)) for k in ['components','libparts','nets']};check(all(electrical.values()),'New CLI export electrical content differs');normalize=lambda raw:raw.replace(str(F/'cli-snapshot').encode(),b'ROOT').replace(str(P).encode(),b'ROOT');check(normalize(ET.tostring(x.find('libraries')))==normalize(ET.tostring(y.find('libraries'))),'Fresh XML library identities differ');xd,yd=copy.deepcopy(x.find('design')),copy.deepcopy(y.find('design'));xd.find('date').text=yd.find('date').text;check(normalize(ET.tostring(xd))==normalize(ET.tostring(yd)),'Fresh XML metadata differs beyond root/date');check([q.text for q in x.findall('./design/sheet/title_block/rev')]==['R3-S6-P6']*7,'XML title revision mismatch')
metadata={'status':'PASS UNCHANGED SCHEMATIC/XML AND EXACT FOOTER METADATA CLOSURE','candidate_sha256':H,'current_main_XML_sha256':sha(xml),'fresh_cli_XML_sha256':sha(fresh),'retained_main_XML_from_qualified_3c80':True,'unchanged_schematic_count':7,'fresh_export_electrical_sections_identical':electrical,'footer_only_helper_delta':{'before_sha256':sha(B/'cli-snapshot/tools/render_p6_review.py'),'after_sha256':sha(P/'tools/render_p6_review.py'),'before':'ASSEMBLY NOT CLEARED','after':'PCBA production approval required'},'all_other_main_source_files_unchanged_except':['Exact authorized R140 copper','Truthful PCB hash rebinding in legend and seven-via inventory']};(F/'metadata-closure.json').write_text(json.dumps(metadata,indent=2)+'\n')
guard={path:sha(Path(path)) for path in full['source_sha256']};cache=guard.pop(str(P/'controller.kicad_prl'),None)
for path in base['export_guard_source_sha256']:guard[path]=sha(Path(path))
evidence=dict(base['evidence_sha256']);evidence[str(B/'complete-source-qualification.json')]=sha(B/'complete-source-qualification.json')
new_evidence=[F/q for q in ['native-gate-summary.json','revision-geometry.json','route-replay.json','topology.json','metadata-closure.json','erc.json','drc.json','refill-verification.json','uncapped-copper-census.json','advisories/advisory-clearance-census.json','pin-audit-run.log','native-audit.json','close_source_qualification.py']]+[D/q for q in ['join-throats-cf16a6f5.json','all-via-attachments-cf16a6f5.json','all-via-functional-layer-roles-cf16a6f5.json','pad-anchored-dead-trees-cf16a6f5.json','authorized-pruning-cf16a6f5.json','final-cf16a6f5-exceptions.json','r140-final-delta/exact-delta.json','r140-final-delta/check_delta.py','r140-final-delta/pad-floor.json','r140-final-delta/pad-nominal.json']]
for q in new_evidence:evidence[str(q)]=sha(q)
for path,h in evidence.items():check(sha(Path(path))==h,'Underlying source evidence changed: '+path)
report.update(status='PASS FINAL SOURCE CAD AND COMPLETE COPPER-ATTACHMENT QUALIFICATION' if not errors else 'NOT PASSED',candidate_sha256=H,errors=errors,native_counts=full['native_counts'],logical_pin_entries=full['independent_pin_entries'],physical_live_nets=len(top['candidate']['nets']),operation_count=replay['operation_count'],rail_operation_count=replay['rail_operation_count'],copper_joins={'summary':joins['summary'],'all_narrow_local_join_flags':0,'proof_modes':{key:sum(bool(q.get(key)) for q in joins['all_screened_low_lens_width_contacts']) for key in ['strict_erosion_connected','constructive_full_width_path_connected','contained_target_width_virtual_stroke','one_nm_polygon_near_exact_nominal_width_connected']},'negative_control':base['copper_joins']['negative_control'],'numerical_limits':joins['tolerances']},via_attachments=via['summary'],reference_dispositions=geo['facts']['reference_gap_classification'],route_quality_before=quality['before_summary'],route_quality_after=quality['after_summary'],metadata_closure=metadata,export_guard_source_sha256=guard,evidence_sha256=evidence,functional_vias={'audited_vias':406,'ground_vias':97,'unresolved_count':len(functional['one_layer_or_zero_layer_review']),'method':functional['method']},pad_anchored_dead_trees={'unresolved_count':len(trees['review_trees']),'peeled_via_count':0,'method':trees['method']},exact_R140_delta=delta,qualification_carry_forward={'from_source_sha256':base['candidate_sha256'],'qualification_sha256':sha(B/'complete-source-qualification.json'),'unchanged_scopes':['All component and pad geometry','Every filled zone copper union and ground attachment','All via geometry and six named retirements','Exact USB/HSE/VCAP/buck/GND exceptions','Current/power rail geometry','All7 schematic sheets,405pins and normalized XML','Qualified VDDA/J162 local pad contexts'],'pad_regression':'Fresh floor and nominal runs produce exact same835 pad-contact profiles; only total track count differs'},portable_guard_exclusions={str(P/'controller.kicad_prl'):{'snapshot_sha256':cache,'reason':'Volatile KiCad UI cache only; all design inputs and tool bytes remain required'}})
report['pad_attachments']['counts']=dict(padfloor['counts']);report['pad_attachments']['carried_dispositions_with_exact_profile_equality']=True;report['ground_plane_attachments']['carried_from_exact_unchanged_filled_copper_sha256']=base['candidate_sha256'];report['reference_plane_integrity']['raw_deltas']=cleanup['reference_plane_delta'];report['supplemental_In2_ground_fill']['carried_to_candidate_sha256']=H
(F/'complete-source-qualification.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'status':report['status'],'candidate_sha256':H,'errors':errors,'native_counts':full['native_counts'],'track_count':quality['after_summary']['track_count'],'operation_count':replay['operation_count'],'report_sha256':sha(F/'complete-source-qualification.json')},indent=2));raise SystemExit(bool(errors))
