from pathlib import Path
import json,shutil,hashlib
R=Path(__file__).resolve().parents[1];D=R/'integrated-routing/trial03';N=R/'repo/f722-heli/layout-revision';C=N/'checks'
s=json.load(open(D/'owner-summary.json'));assert s['board_sha256']==hashlib.sha256((D/'f722-heli.kicad_pcb').read_bytes()).hexdigest();assert s['drc']['errors']==0 and all(s[k]['passed'] for k in ['process','mechanical','parity','firmware'])
shutil.copy2(D/'f722-heli.kicad_pcb',N/'hardware/f722-heli.kicad_pcb');shutil.copy2(R/'placement-adjustments/usb-u5-05/poses.json',N/'placement.json')
for name,target in [('owner-drc','placement-drc'),('owner-mechanical','mechanical-report'),('owner-parity','native-schematic-parity'),('owner-firmware','firmware-pinmap'),('owner-process','via-process'),('owner-critical','critical-net-connectivity'),('power-audit','power-pad-groups'),('owner-summary','routing-checkpoint-summary')]:shutil.copy2(D/(name+'.json'),C/(target+'.json'))
shutil.copy2(D/'owner-protection.json',C/'protection/candidate-recheck.json');shutil.copy2(D/'owner-supplemental.json',C/'protection/candidate-supplemental.json');shutil.copy2(R/'fixed-copper-routing/audit_native.py',N/'scripts/check_critical_connectivity.py')
status=json.load(open(C/'current-status.json'));status.update(status='WIP — PARTIALLY ROUTED — NOT FOR MANUFACTURE',board_sha256=s['board_sha256'],unfinished_connections=158,drc_errors=0,drc_warnings=17,reproducible_native_build=False,reproducible_placement_build=True,routed_native_source='hardware/f722-heli.kicad_pcb',protection_paths_passed=1,protection_paths_total=18,supplemental_protection_passed=5,supplemental_protection_total=7,critical_nets_connected=16,ground_pad_groups=1,checkpoint_progress='Critical clock/IMU/VCAP/USB routes and all ground pad connections added. Loaded power trunks and ordinary protected signals remain incomplete.',warning_scope='16 dangling vias and one dangling track at unfinished route interfaces.')
old=json.load(open(N/'placement-build.json'));poses=json.load(open(N/'placement.json'));status['changed_poses_from_published']=sum(poses[k]!=old['poses_before'][k] for k in poses);status['not_yet_complete']=['Loaded power routing and ordinary protected signals','All remaining protection-path cuts','Loaded power/ground and signal-reference qualification','Final manufacturing exports and CAM/assembly checks','Physical qualification'];(C/'current-status.json').write_text(json.dumps(status,indent=2)+'\n')
# Record traceable intermediate input identities without publishing scratch paths.
source={'board_sha256':s['board_sha256'],'placement_pose_sha256':hashlib.sha256((N/'placement.json').read_bytes()).hexdigest(),'prior_published_checkpoint':'7425b04e317ce7eebf1e652477a75448d067c583','frozen_power_input_sha256':'d698b0e3d46f73723f105ae8c569661a19a91a505a1ea0dbb1ecafa3ea4686bd','frozen_critical_input_sha256':'e9a617766ae61513874d83ba6cdcfaf3c6226f93a3ef6c948534a401b949af06','integration':'Merged tracks/vias; restored GND zones; removed conflicting power branch groups; added all remaining GND escapes; applied CC2 dogleg with0.187102mm outside-pad gap. Main native file is authoritative; placement builder does not recreate routing.'};(N/'routing-build.json').write_text(json.dumps(source,indent=2)+'\n')
print(status['board_sha256'],status['changed_poses_from_published'])
