#!/usr/bin/python3
"""Join independently completed CAD/attachment reports and fresh XML semantics."""
import copy,hashlib,json,xml.etree.ElementTree as ET
from pathlib import Path
D=Path(__file__).resolve().parents[1];F=D/'final-3c80eba2';P=Path('/workspace/shared/storm32-redesign/controller-r3s-p6');A=Path('/workspace/shared/storm32-redesign/controller-r3s-p5');PAD=Path('/workspace/shared/storm32-redesign/research/controller-r3s-p6-pad-attachment-audit');H='3c80eba2e6dfd7161f875436aff8c64bcaee0ad8d6cc94a55b24bfc5e2014e47';sha=lambda q:hashlib.sha256(q.read_bytes()).hexdigest();read=lambda q:json.loads(q.read_text());errors=[]
def check(ok,msg):
 if not ok:errors.append(msg)
full=read(F/'native-gate-summary.json');geo=read(F/'revision-geometry.json');top=read(F/'topology.json');replay=read(F/'route-replay.json');joins=read(D/'join-throats-3c80eba2.json');via=read(D/'all-via-attachments-3c80eba2.json');plane=read(D/'ground-plane-attachments-3c80eba2.json');pad=read(PAD/'final-3c80eba2-closure.json');pad_integration=read(PAD/'final-3c80eba2-integration-proof.json');quality=read(F/'route-quality/route-quality-comparison.json');negative=read(D/'join-throats-p5-constructive.json')
for name,doc in [('native',full),('geometry',geo),('topology',top),('replay',replay),('joins',joins),('via',via),('plane',plane),('pads',pad)]:
 check(doc.get('candidate_sha256')==H,name+' source hash mismatch');check(not doc.get('errors'),name+' contains errors')
check(full['status'].startswith('PASS') and full['source_stable'],'Full numerical gate did not pass with stable source');check(not any(full['native_counts'].values()),'Native ERC/DRC/opens/parity nonzero');check(not joins['narrow_local_join_flags'],'Unresolved local copper joins');check(not via['new_or_worsened_shallow_groups'] and not via['inherited_or_improved_shallow_groups'],'Unresolved signal/via contact quality');check(pad['counts']['failed_groups']==0 and pad['unresolved_functional_nominal_advisory_count']==0 and not pad['new_or_worse_nominal_cases'],'Unresolved functional pad-entry geometry');check(pad['all431_pad_inventory_unchanged'],'Pad inventory changed');check(pad_integration['main_sha256']==pad_integration['snapshot_sha256']==H and pad_integration['final_closure_report_sha256']==sha(PAD/'final-3c80eba2-closure.json'),'Pad independent integration proof differs');check(plane['verified_reference_plane_terminal_attachments']==303,'Incomplete solid-reference-plane terminal coverage')
negative_host=[q for q in negative['narrow_local_join_flags'] if q['net']=='HOST_TX_RAW'];check(len(negative_host)==2 and all(abs(q['pair_circle_lens_neck_mm']-.05)<1e-10 for q in negative_host),'Known HOST_TX_RAW negative control was not detected');check(negative['audit_script_sha256']==joins['audit_script_sha256']==sha(D/'audit_copper_join_throats.py'),'Negative/final copper-join methods differ')
clone=F/'cli-snapshot';oldxml=A/'review/controller-netlist.xml';fresh=clone/'review/controller-netlist.xml';current=P/'review/controller-netlist.xml';raw=fresh.read_bytes();expected=raw.replace(str(clone).encode(),str(P).encode());check(raw.count(str(clone).encode())==8,'Fresh XML prefix count differs');check(current.read_bytes()==expected,'Current XML differs beyond the exact eight clone-root replacements');xo=ET.parse(oldxml).getroot();xf=ET.parse(fresh).getroot();xc=ET.parse(current).getroot();electrical={tag:ET.tostring(xo.find(tag))==ET.tostring(xc.find(tag))==ET.tostring(xf.find(tag)) for tag in ['components','libparts','nets']};check(all(electrical.values()),'XML electrical content differs')
norm=lambda data:data.replace(str(A).encode(),b'PROJECT_ROOT').replace(str(P).encode(),b'PROJECT_ROOT');libraries=norm(ET.tostring(xo.find('libraries')))==norm(ET.tostring(xc.find('libraries')));check(libraries,'XML library identities differ');ad,bd=copy.deepcopy(xo.find('design')),copy.deepcopy(xc.find('design'));dates={'baseline':ad.findtext('date'),'final':bd.findtext('date')};ad.find('date').text=bd.findtext('date');design=norm(ET.tostring(ad))==norm(ET.tostring(bd)).replace(b'R3-S6-P6',b'R3-S6-P5');check(design,'XML design metadata differs beyond exact title/root/date normalization');revs=[q.text for q in xc.findall('./design/sheet/title_block/rev')];check(len(revs)==7 and set(revs)=={'R3-S6-P6'},'Fresh XML does not contain exactly seven P6 titles')
metadata={'status':'PASS FRESH XML METADATA/SEMANTIC CLOSURE' if all(electrical.values()) and libraries and design and current.read_bytes()==expected else 'NOT PASSED','candidate_sha256':H,'fresh_cli_XML_sha256':sha(fresh),'current_main_XML_sha256':sha(current),'exact_root_prefix_replacements':8,'electrical_sections_unchanged':electrical,'library_identity_unchanged':libraries,'exact_design_metadata_normalization':design,'sheet_revisions':revs,'export_dates':dates,'allowed_changes':'Fresh native export date, exact P5→P6 title revision, and exact isolated-snapshot root rebasing to main project; no component/libpart/net edits'};(F/'XML-metadata-closure.json').write_text(json.dumps(metadata,indent=2)+'\n')
changed=[]
for path,h in full['source_sha256'].items():
 now=sha(Path(path))
 if now!=h:changed.append(path)
wrapper=P/'tools/export_release_p6.py';snapshot_wrapper=clone/'tools/export_release_p6.py'
old_line="exec(compile(source, str(producer), 'exec'), globals())"
new_lines="producer_namespace = {'__file__': str(producer), '__name__': '__main__', '__builtins__': __builtins__}\nexec(compile(source, str(producer), 'exec'), producer_namespace)"
check(snapshot_wrapper.read_text().count(old_line)==1 and wrapper.read_text()==snapshot_wrapper.read_text().replace(old_line,new_lines),'Wrapper differs beyond exact producer-namespace isolation')
check(set(changed)=={str(current),str(wrapper)},'Unexpected source changes after full gate: '+str(changed));check(sha(P/'controller.kicad_pcb')==H,'Native PCB changed after qualification')
guard={path:sha(Path(path)) for path in full['source_sha256']}
for rel in ['review/printed-pad-legend.json','review/approved-small-vias.json','review/pad-wiring-map.csv','review/assembly-cpl-overrides.json','inputs/user-corrected-JLC_CPL.csv','review/edge-pad-map.json','review/h743-pin-map.json']:guard[str(P/rel)]=sha(P/rel)
evidence=[F/'native-gate-summary.json',F/'revision-geometry.json',F/'route-replay.json',F/'topology.json',F/'XML-metadata-closure.json',F/'erc.json',F/'drc.json',F/'refill-verification.json',F/'uncapped-copper-census.json',F/'advisories/advisory-clearance-census.json',F/'pin-audit-run.log',F/'native-audit.json',D/'join-throats-3c80eba2.json',D/'join-throats-p5-constructive.json',D/'all-via-attachments-3c80eba2.json',D/'ground-plane-attachments-3c80eba2.json',PAD/'final-3c80eba2-closure.json',PAD/'final-3c80eba2-integration-proof.json',D/'final-3c80eba2-exceptions.json',D/'east-rail-reference-independent.json',D/'j162-pruning-rebased-independent.json']
cleanup=read(D/'authorized-pruning-3c80eba2.json');functional=read(D/'all-via-functional-layer-roles-3c80eba2.json');trees=read(D/'pad-anchored-dead-trees-3c80eba2.json');supplemental=read(D/'supplemental-In2-fill-3c80eba2.json')
for name,doc in [('retirement',cleanup),('functional vias',functional),('dead trees',trees),('supplemental fill',supplemental)]:check(doc['candidate_sha256']==H,name+' hash differs')
check(cleanup['status']=='PASS EXACT REDUNDANT VIA/STUB PRUNING' and not cleanup['errors'],'Retirement qualification failed')
check(functional['via_count']==406 and functional['ground_vias']==97 and not functional['one_layer_or_zero_layer_review'],'Nonfunctional via remains')
check(not trees['review_trees'] and trees['peeled_via_count']==0,'Exposed pad-anchored dangling tree remains')
check(supplemental['status'].startswith('PASS'),'Supplemental fill not qualified')
retired={r['uuid'] for r in cleanup['removed_via_records']};root_via='e662c27f-1468-4ab2-86f2-d1b4a98b1610'
expected_disappeared={(q['via_uuid'],q['layer']) for q in via['baseline']['profiles'].values() if q['via_uuid'] in retired}|{(root_via,'In2.Cu')}
actual_disappeared={(q['via_uuid'],q['layer']) for q in via['disappeared_via_layer_contacts']}
check(actual_disappeared==expected_disappeared and len(actual_disappeared)==13,'Unexpected disappearing routed via-layer profile')
root_role=next(r for r in functional['all_via_roles'] if r['uuid']==root_via)
check(root_role['functional_layers']==['B.Cu','F.Cu'] and not root_role['review'],'Retained USB_SOURCE_DISABLE tree root lost real layer function')
root_profile=via['baseline']['profiles'][root_via+':In2.Cu'];pruned_ids={t['uuid'] for c in cleanup['retired_terminal_components'] for t in c['tracks']}
check(all(t['uuid'] in pruned_ids for g in root_profile['contact_groups'] for t in g['tracks']),'Retained root lost a non-retired branch contact')
for name in ['authorized-pruning-3c80eba2.json','all-via-functional-layer-roles-3c80eba2.json','pad-anchored-dead-trees-3c80eba2.json','supplemental-In2-fill-3c80eba2.json','two-ground-shoulders-3c80eba2.json','single-terminal-copper-fafa9c3f.json','pad-anchored-dead-trees-fafa9c3f.json']:evidence.append(D/name)
evidence += [F/'close_source_qualification.py',F/'audit_supplemental_fill.py']
cache_path=str(P/'controller.kicad_prl');cache_hash=guard.pop(cache_path,None)
metadata['export_wrapper_namespace_correction']={'before_sha256':sha(snapshot_wrapper),'after_sha256':sha(wrapper),'exact_two_line_delta_verified':True,'scope':'Producer runs in its own namespace, preserving wrapper expected PCB hash; all guards and producer code remain identical'}
(F/'XML-metadata-closure.json').write_text(json.dumps(metadata,indent=2)+'\n')
proof_modes={key:sum(bool(q.get(key)) for q in joins['all_screened_low_lens_width_contacts']) for key in ['strict_erosion_connected','constructive_full_width_path_connected','contained_target_width_virtual_stroke','one_nm_polygon_near_exact_nominal_width_connected']}
report={'status':'PASS FINAL SOURCE CAD AND COMPLETE COPPER-ATTACHMENT QUALIFICATION' if not errors else 'NOT PASSED','candidate_sha256':H,'baseline_sha256':full['baseline_sha256'],'errors':errors,'native_counts':full['native_counts'],'logical_pin_entries':full['independent_pin_entries'],'physical_live_nets':len(top['candidate']['nets']),'reference_planes_unchanged':all(q['loss_mm2']==q['gain_mm2']==0 for q in geo['facts']['reference_plane_delta']),'unchanged_footprints':geo['facts']['footprints'],'exact_USB_tracks':full['protected_USB_tracks'],'USB_width_mm':.1392,'ordinary_trace_floor_mm':.13,'foreign_trace_clearance_mm':.16,'all_vias':via['summary']['audited_vias'],'ground_vias':geo['facts']['ground_via_count'],'ground_pads':top['candidate']['ground_pad_count'],'operation_count':replay['operation_count'],'rail_operation_count':replay['rail_operation_count'],'copper_joins':{'summary':joins['summary'],'all_narrow_local_join_flags':0,'proof_modes':proof_modes,'negative_control':'The same exact script rejects both P5 HOST_TX_RAW .050mm throats and finds no unresolved final join','numerical_limits':joins['tolerances']},'via_attachments':via['summary'],'pad_attachments':{'counts':pad['counts'],'unresolved_functional_nominal_advisories':0,'all_pad_inventory_unchanged':True,'manufactured_land_limited_contacts':pad['intended_land_limited_contacts'],'qualified_local_contexts':{'VDDA':'Original small redundant corner graze has a separately proven full .200mm native-union route','J162':'The .450×.050mm endpoint flare does not set feed width; its sole .300mm incoming path passes the full nominal check'}},'ground_plane_attachments':{'plane_only_live_pads':4,'reference_plane_terminal_attachment_checks':303,'actual_modes':'FULL_SOLID; no thermal spokes are relied upon','annular_geometry':plane['annulus_exception'],'routing_layer_GND_fill':'In2 GND fill is supplemental and may form separate islands; every ground terminal independently passes all three solid reference planes','outside_terminal_proof_width_mm':.1302},'reference_dispositions':geo['facts']['reference_gap_classification'],'route_quality_before':quality['before_summary'],'route_quality_after':quality['after_summary'],'metadata_closure':metadata,'export_guard_source_sha256':guard,'evidence_sha256':{str(q):sha(q) for q in evidence},'qualification_limits':['Final all-route visual acceptance is owned by the independent visual reviewer; shape-count reductions alone are not acceptance','This source qualification permits final export generation under the exact hash guard; final Gerber/drill/BOM/CPL/package parity must still be verified','Native land and approved plated-annulus dimensions are intentionally distinguished from ordinary trace necks','Measured load-current/thermal capacity, impedance, EMI, firmware and hardware performance are not certified by CAD checks; the release report separately states selected fabrication and preassembly production requirements']}
report.update(functional_vias={'audited_vias':406,'ground_vias':97,'unresolved_count':len(functional['one_layer_or_zero_layer_review']),'method':functional['method']},pad_anchored_dead_trees={'unresolved_count':len(trees['review_trees']),'peeled_via_count':trees['peeled_via_count'],'method':trees['method']},qualified_redundant_via_retirement={'retired_via_count':6,'removed_vias':cleanup['removed_via_records'],'qualified_disappeared_via_layer_profiles':13,'all_surviving_via_records_unchanged':True,'retained_USB_SOURCE_DISABLE_root':'Its retired In2 antenna branch is gone; functional F.Cu and B.Cu routes remain'},reference_plane_integrity={'status':'PASS EXACT SIX-VIA-ONLY NATIVE REFILL','raw_deltas':cleanup['reference_plane_delta'],'reference_plane_definitions_unchanged':True,'oracle':'Frozen fafa board with only six named vias removed reproduces all three final reference-plane copper unions exactly'},supplemental_In2_ground_fill=supplemental,portable_guard_exclusions={cache_path:{'snapshot_sha256':cache_hash,'reason':'Only volatile KiCad UI layer/selection/visibility/panel state; all native design, rule, library, map, input and tool files remain required'}})
(F/'complete-source-qualification.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k in ['status','candidate_sha256','errors','native_counts','logical_pin_entries','physical_live_nets','all_vias','ground_vias','ground_pads','operation_count','rail_operation_count']},indent=2));raise SystemExit(bool(errors))
