import pathlib,json,hashlib,shutil,math
HERE=pathlib.Path(__file__).resolve().parent;ROOT=HERE.parents[2];S=ROOT/'ordinary-routing/candidate44';D=HERE/'candidate01'
read=lambda f:json.loads(pathlib.Path(f).read_text());sha=lambda f:hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest();write=lambda n,r:(D/n).write_text(json.dumps(r,indent=2)+'\n')
h=sha(D/'f722-heli.kicad_pcb');oldh=sha(S/'f722-heli.kicad_pcb');assert oldh=='02d2090ad7220a64a8f4a1a259d522f7b0bca3e15214b73107491d17626bd51f';assert h=='9881a992b12fed90f17131ed627f12af77680cc2ddf95030adf8c564aaa24eb2'
summary=read(D/'owner-summary.json');assert summary['board_sha256']==h and summary['drc']==summary['drc-all']=={'unconnected':34,'errors':0,'warnings':0};assert not read(D/'owner-drc-parity.json')['schematic_parity'];assert all(summary[k]['passed']for k in ['process','mechanical','parity','firmware']);assert summary['critical']['connected_nets']==summary['critical']['total_nets']==16 and not summary['critical']['faults'] and not summary['critical']['missing_ground_returns']
erc=read(D/'owner-erc.json');assert not any(s['violations']for s in erc['sheets'])
audit=read(D/'entry-support-audit.json');ref=read(D/'reference-runtime-index-proof.json');integration=read(D/'native-coordinated-integration.json');assert audit['passed'] and all(audit['gates'].values())and ref['passed']and integration['passed'];assert all(x['rejected']for x in audit['negative_controls']+ref['negative_controls']);assert all(x['board_sha256']==h for x in[audit,ref,integration]);assert ref['all_saved_zone_records_exact'] and ref['all_critical_reference_net_reports_exact']
io=read(D/'protection-actual-io.json');prior=read(S/'protection-actual-io.json');assert io['board_sha256']==h and io['passed']==prior['passed']==11 and io['total']==22;assert {x['id']for x in io['checks']if x['complete_clamp_first_path_passes']}=={x['id']for x in prior['checks']if x['complete_clamp_first_path_passes']}
i2c=read(D/'i2c-geometry-review.json');assert all(i2c['nets'][n]['topology']['clean_complete_tree']for n in['BARO_SCL','BARO_SDA']);assert i2c['I2C_final_status']=='NOT_QUALIFIED'
prov=read(D/'construction-provenance.json');mapping=read(D/'f722-heli.logical-route-map.json')['logical_route_map'];oldmap=read(S/'f722-heli.logical-route-map.json')['logical_route_map'];assert all(mapping.get(k)==v for k,v in oldmap.items())
write('coordinated-change-receipt.json',{'schema':'f722-explicit-coordinated-native-transaction/v1','passed':True,'source_board_sha256':oldh,'board_sha256':h,'source_native_sha256':sha(S/'f722-heli.native.json'),'candidate_native_sha256':sha(D/'f722-heli.native.json'),'source_map_sha256':sha(S/'f722-heli.logical-route-map.json'),'candidate_map_sha256':sha(D/'f722-heli.logical-route-map.json'),'removed_source_records':[],'added_candidate_records':prov['added_records'],'changed_pad_records':prov['changed_pad_records'],'changed_footprint_records':prov['changed_footprint_records'],'removed_logical_owners':{},'added_logical_owners':{o['uuid']:mapping[o['uuid']]for o in prov['added_records']},'all_other_source_objects_exact_except_runtime_net_code':prov['all_other_source_native_objects_exact_except_net_code'],'all_retained_logical_owners_exact':True,'all_existing_native_board_track_via_arc_structures_exact':True,'all_GND_pad_track_via_zone_records_exact':True,'runtime_net_code_reindexing_receipt':'construction-provenance.json','complete_rewritten_entry_receipt':'entry-support-audit.json','complete_rewritten_entry_receipt_sha256':sha(D/'entry-support-audit.json'),'support_receipt':'power-audit.json','support_receipt_sha256':sha(D/'power-audit.json'),'actual_io_receipt':'protection-actual-io.json','actual_io_receipt_sha256':sha(D/'protection-actual-io.json'),'footprint_transform_receipt':'native-coordinated-integration.json','footprint_transform_receipt_sha256':sha(D/'native-coordinated-integration.json'),'reference_runtime_index_proof_sha256':sha(D/'reference-runtime-index-proof.json'),'construction_provenance_sha256':sha(D/'construction-provenance.json'),'engine_success_claimed':False,'numerical_power_VCAP_applicable':False,'adoption_claimed':False})
write('f722-heli.import.json',{'schema':'f722-explicit-coordinated-native-construction-receipt/v1','passed':True,'source_sha256':oldh,'output_sha256':h,'construction_source_sha256':oldh,'construction_kind':'Complete NRST testpoint closure by declared native TP5 side/position transform and two B.Cu tracks; no existing copper changes and no new vias.','direct_engine_output':False,'engine_routing_succeeded':False,'engine_partial_geometry_adopted':False,'ses_engine_native_geometry_equal':False,'session_artifact':None,'coordinated_change_receipt':'coordinated-change-receipt.json','coordinated_change_receipt_sha256':sha(D/'coordinated-change-receipt.json'),'construction_provenance':'construction-provenance.json','construction_provenance_sha256':sha(D/'construction-provenance.json'),'logical_route_map_artifact':'f722-heli.logical-route-map.json','logical_route_map_sha256':sha(D/'f722-heli.logical-route-map.json'),'undeclared_native_changes':0,'footprints_preserved':155,'footprints_transformed':1,'reference_plane_refill_performed':True,'fresh_model_zero_control_performed':False,'numerical_power_VCAP_applicable':False})
write('power-revalidation-required.json',{'board_sha256':h,'source_board_sha256':oldh,'numerical_power_and_VCAP_applicability':False,'geometric_support_continuity_passed':True,'all28_support_groups_exact':True,'all_saved_zone_records_exact':True,'all_existing_power_and_GND_copper_exact':True,'reason':'The accepted source44 numerical applicability remained pending. This testpoint-only successor adds no holes or power copper and preserves all saved zones exactly; it does not inherit the separately validated source43 numerical result.','transient_qualification_claimed':False,'I2C_electrical_status':'NOT_QUALIFIED'})
for name in ['construct.py','audit.py','screen.py','prove_reference_identity.py','seal.py']:shutil.copy2(HERE/name,D/(pathlib.Path(name).stem+'.used.py'))
sources=[HERE/'construct.py',HERE/'audit.py',HERE/'screen.py',HERE/'prove_reference_identity.py',HERE/'seal.py',S/'f722-heli.kicad_pcb',S/'f722-heli.native.json',S/'poses-native.json',S/'power-audit.json',ROOT/'ordinary-routing/dsm40-audits/audit_dsm40_entries_return.py',ROOT/'ordinary-routing/dsm41-audits/audit_dsm41_entries_return.py',ROOT/'integrated-routing/verify_footprint_transforms.py',ROOT/'integrated-routing/check_coordinated_integration.py',ROOT/'integrated-routing/verify_support_adoption.py'];write('input-hashes.json',{str(p.relative_to(ROOT)):sha(p)for p in sources})
text='''# Isolated NRST testpoint closure from accepted candidate44

Native result: 34 unfinished connections, zero geometric errors/warnings, strict schematic parity and ERC zero. Not adopted or manufacturing/flight qualified.

TP5 retains its UUID, SWD NRST function, 1.0 mm exposed testpad and native footprint. It moves from F.Cu (37,23.8),0° to B.Cu (16.9,6.0),0°. A native Flip(false),0° orientation and translation exactly reproduce the complete footprint. The other155 footprints and all1381 previous native track/via/arc structures remain identical. TP1 is unchanged.

Two0.127 mm B.Cu tracks are added: (16.9,6.0)→(17.12882,6.22882)→existing NRST via (17.12882,6.83933). There are no new vias, removals or changed existing copper. Native graphs connect C10.1,R1.2,TP5.1,U1.7. Finite full-width pad, join and actual-annulus proofs and five refusal controls pass.

The1.4 mm analytic probe-access disk clears every body; nearest body radial margin is0.411124556 mm. Nearest existing drill-to-new-mask gap is0.269944076 mm and new pad-to-foreign-copper gap is0.358487475 mm. All complete projected through-hole header body/lead spans remain clear, with at least0.3 mm lead-access reserve outside the probe disk. Full native courtyard, assembly reserve, solder access, outline, hole and orthogonal placement checks pass. This does not establish a specific3D fixture or assembled harness geometry.

All16 critical nets and returns, all28 native support partitions, both I2C clean trees, actual protection11/22 endpoint cases and9/20 channels are preserved. I2C electrical status and numerical power/VCAP remain unqualified.

Reference caveat: the raw complete-record comparator remains false because83 critical records received different transient KiCad net_code integers after changing TP5's side. No stored snapshots or raw comparison were normalized. reference-runtime-index-proof.json proves exact physical identity for all153 critical records, bijective runtime net mappings, exact saved zone records and exact complete reference net reports. Six rejection controls cover changes to name,width,UUID,endpoint,copper and omission. Owner adoption needs an explicit adapter for this verified index-only case, not a generic geometry exemption.

Source board SHA256: SOURCE_SHA
Candidate board SHA256: CANDIDATE_SHA

The bounded SWDIO local-placement screen found no accessible1mm testpoint site beside U1.46: the suggested(28.4,16.5) B site overlaps C55 and C3. No SWDIO changes are included.
'''.replace('SOURCE_SHA',oldh).replace('CANDIDATE_SHA',h)
(D/'README.md').write_text(text)
files={str(p.relative_to(D)):sha(p)for p in D.rglob('*')if p.is_file()and p.name!='route-handoff.json'and p.suffix not in ['.log','.kicad_prl']}
handoff={'schema':'f722-native-route-handoff/v1','status':'frozen_native_verified_34_open_complete_NRST_geometric_WIP_pending_owner_review','board_sha256':h,'integration_source_sha256':oldh,'drc':{'unconnected':34,'errors':0,'warnings':0,'strict_schematic_parity':0,'ERC_violations':0},'pose_reference':str((D/'poses-native.json').relative_to(ROOT)),'declared_footprint_transforms':'declared-footprint-transforms.json','all_other_155_footprints_exact':True,'retained_native_track_via_arc_objects_exact':1381,'removed_source_objects':0,'added_native_objects':2,'completed_net':'NRST','completed_terminals':['C10.1','R1.2','TP5.1','U1.7'],'actual_io_passed':11,'actual_io_total':22,'actual_io_channels_passed':9,'actual_io_channels_total':20,'entry_support_audit':'entry-support-audit.json','entry_support_gates':len(audit['gates']),'negative_controls':len(audit['negative_controls'])+len(ref['negative_controls']),'power_wrapper_schema':'f722-native-support-audit/v1','power_wrapper_derived_from_current_native_groups':True,'raw_critical_object_geometry_identical':False,'reference_runtime_index_proof':'reference-runtime-index-proof.json','reference_runtime_index_proof_sha256':sha(D/'reference-runtime-index-proof.json'),'all_physical_critical_records_exact_except_runtime_net_code':True,'all_saved_zone_records_exact':True,'both_BARO_clean_complete_trees':True,'I2C_electrical_status':'NOT_QUALIFIED','numerical_power_VCAP_applicable':False,'owner_adoption_pending':True,'direct_engine_output':False,'fresh_router_zero_replay_performed':False,'files':files}
write('route-handoff.json',handoff);assert all(sha(D/name)==digest for name,digest in handoff['files'].items());print(json.dumps({'board_sha256':h,'route_handoff_sha256':sha(D/'route-handoff.json'),'sealed_files':len(files),'native_unconnected':34,'negative_controls':handoff['negative_controls']}))
