import pathlib,json,hashlib,shutil
HERE=pathlib.Path(__file__).resolve().parent;ROOT=HERE.parents[2];S=ROOT/'ordinary-routing/candidate45';D=HERE/'candidate01'
read=lambda f:json.loads(pathlib.Path(f).read_text());sha=lambda f:hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest();write=lambda n,r:(D/n).write_text(json.dumps(r,indent=2)+'\n')
h=sha(D/'f722-heli.kicad_pcb');oldh=sha(S/'f722-heli.kicad_pcb');assert oldh=='9881a992b12fed90f17131ed627f12af77680cc2ddf95030adf8c564aaa24eb2';assert h=='87c5ced471edaf2e0ace382d4236bc1787efb869b7ae759c53d87ee76165c0cb'
summary=read(D/'owner-summary.json');assert summary['board_sha256']==h and summary['drc']==summary['drc-all']=={'unconnected':33,'errors':0,'warnings':0};strict=read(D/'owner-drc-parity.json');assert not strict['schematic_parity'] and not strict['violations'];assert all(summary[k]['passed']for k in ['process','mechanical','parity','firmware']);assert summary['critical']['connected_nets']==summary['critical']['total_nets']==16 and not summary['critical']['faults'] and not summary['critical']['missing_ground_returns'];assert not any(s['violations']for s in read(D/'owner-erc.json')['sheets'])
audit=read(D/'entry-support-audit.json');ref=read(D/'reference-comparison45.json');integration=read(D/'native-additive-integration.json');assert audit['passed']and all(audit['gates'].values())and integration['passed'];assert all(x['rejected']for x in audit['negative_controls']);assert ref['critical_object_geometry_identical']and not ref['critical_object_differences'];assert all(v==0 for x in ref['net_numeric_deltas_after_minus_before'].values()for v in x.values());assert all(x['physical_GND_lost_mm2']==x['physical_GND_gained_mm2']==0 for x in ref['ground_fill_changes'].values())
assert read(S/'reference-snapshot/critical-reference.json')['nets']==read(D/'reference-snapshot/critical-reference.json')['nets']
io=read(D/'protection-actual-io.json');prior=read(S/'protection-actual-io.json');assert io['board_sha256']==h and io['passed']==12 and prior['passed']==11 and io['total']==22;passed=lambda r:{x['id']for x in r['checks']if x['complete_clamp_first_path_passes']};assert passed(prior)<passed(io) and passed(io)-passed(prior)=={'supplemental-06'};cut=next(x for x in io['checks']if x['id']=='supplemental-06');assert cut['complete_clamp_first_path_passes']and cut['source_target_physically_disconnected_after_removing_actual_pad_copper']and cut['minimum_gap_measured_mm']>=.127
channels=len({(x['net'],x['clamp'])for x in io['checks']if x['complete_clamp_first_path_passes']});assert channels==10
i2c=read(D/'i2c-geometry-review.json');assert all(i2c['nets'][n]['topology']['clean_complete_tree']for n in ['BARO_SCL','BARO_SDA']);assert i2c['I2C_final_status']=='NOT_QUALIFIED';assert read(D/'stock-spi-binding.json')['passed']
prov=read(D/'construction-provenance.json');mapping=read(D/'f722-heli.logical-route-map.json')['logical_route_map'];oldmap=read(S/'f722-heli.logical-route-map.json')['logical_route_map'];assert all(mapping.get(k)==v for k,v in oldmap.items());assert {mapping[o['uuid']]for o in prov['added_records']}=={'RPM_HV::P0'}
before=read(S/'f722-heli.native.json');after=read(D/'f722-heli.native.json');old={o['uuid']:o for o in before['objects']};now={o['uuid']:o for o in after['objects']};assert all(now[u]==o for u,o in old.items());assert all(before[k]==after[k]for k in ['footprints','zones','edge_cuts','outline_with_npth','copper_layers','board_thickness_mm']);assert len(old)==1941 and len(now)==1950
assert sha(S/'poses-native.json')==sha(D/'poses-native.json');assert read(D/'owner-mechanical.json')['input_hashes']['poses-native.json']==sha(D/'poses-native.json');assert read(D/'owner-native.json')==after
for r in read(D/'project-input-preservation.json')['files']:assert sha(D/r['path'])==sha(S/r['path'])==r['sha256']
for name in ['construct.py','audit.py','plan.py','route_rpm.py','refine.py','native_geometry.py','extra_gates.py','seal.py']:shutil.copy2(HERE/name,D/(pathlib.Path(name).stem+'.used.py'))
for name in ['rpm-F-route.json','rpm-F-final-proposal.json','refinement-history.json']:shutil.copy2(HERE/name,D/name)
refine=read(D/'refinement-history.json');assert refine['final_proposal_sha256']==sha(D/'rpm-F-final-proposal.json');assert refine['final_points']==read(D/'rpm-F-final-proposal.json')['points'];assert prov['proposal_sha256']==sha(D/'rpm-F-final-proposal.json')
write('f722-heli.import.json',{'schema':'f722-explicit-additive-native-construction-receipt/v1','passed':True,'source_sha256':oldh,'output_sha256':h,'construction_source_sha256':oldh,'construction_kind':'Complete R25.2 to actual bonded U16.1 RPM_HV branch; nine F.Cu tracks, no existing copper or placement changes, no new vias.','direct_engine_output':False,'engine_routing_succeeded':False,'engine_partial_geometry_adopted':False,'ses_engine_native_geometry_equal':False,'session_artifact':None,'construction_provenance':'construction-provenance.json','construction_provenance_sha256':sha(D/'construction-provenance.json'),'logical_route_map_artifact':'f722-heli.logical-route-map.json','logical_route_map_sha256':sha(D/'f722-heli.logical-route-map.json'),'source_objects_preserved_exact':1941,'routes_added':9,'routes_removed':0,'footprints_preserved':156,'reference_plane_refill_performed':False,'reference_plane_refill_required':False,'all_saved_zone_records_exact':True,'fresh_model_zero_control_performed':False,'numerical_power_VCAP_applicable':False})
write('power-revalidation-required.json',{'board_sha256':h,'source_board_sha256':oldh,'numerical_power_and_VCAP_applicability':False,'geometric_support_continuity_passed':True,'all28_support_groups_exact':True,'all_saved_zone_records_exact':True,'all_existing_power_and_GND_copper_exact':True,'reason':'The accepted source45 numerical applicability remained pending. This successor adds no holes or power copper and preserves all saved zones exactly; it does not inherit the separately validated source43 numerical result.','transient_qualification_claimed':False,'I2C_electrical_status':'NOT_QUALIFIED'})
sources=[HERE/f for f in ['construct.py','audit.py','plan.py','route_rpm.py','refine.py','native_geometry.py','extra_gates.py','seal.py']]+[S/'f722-heli.kicad_pcb',S/'f722-heli.native.json',S/'poses-native.json',S/'power-audit.json',ROOT/'ordinary-routing/dsm40-audits/audit_dsm40_entries_return.py',ROOT/'integrated-routing/check_additive_integration.py',ROOT/'integrated-routing/verify_support_adoption.py'];write('input-hashes.json',{str(p.relative_to(ROOT)):sha(p)for p in sources})
(D/'README.md').write_text(f'''# Isolated RPM_HV closure from accepted candidate45

Native result:33 unfinished connections, zero geometric errors/warnings, strict schematic parity and ERC zero. Pending owner review; not manufacturing/flight qualified.

Adds nine0.127 mm F.Cu segments from R25.2 to actual bonded U16.1. The native RPM_HV graph now joins R25.2,U16.1,Q1.3. No vias, removals or footprint changes. All1941 previous native records,156 footprints,1383 previous track/via/arc structures and every saved zone record remain exact. Outside-layer-only additions need no plane refill.

All18 new endpoints have finite full-width proof: two native pad entries and eight exact round-ended joins. Five rejection controls pass. All28 support partitions and both I2C complete trees are preserved. The actual U16.1 pad-cut disconnects source from Q1.3 with nominal outside-pad separation{cut['minimum_gap_measured_mm']:.12f} mm, zero outside-pad overlap. Actual protection rises11→12/22 endpoint cases and9→10/20 channels.

A bounded0.04 mm planning-grid search found a complete same-face corridor. Native exact-distance line-of-sight simplification permits arbitrary track angles. The raw proposal and all later local-centering sweeps remain in rpm-F-route.json and refinement-history.json. Final minimum nominal CAD copper gap is{audit['nominal_CAD_copper_gap_mm']:.12f} mm, excess{audit['nominal_CAD_copper_gap_mm']-.127:.12f} mm above the0.127 mm rule. This is nominal CAD geometry, not manufacturing margin. No actual clearance or fabrication rule was relaxed.

Raw critical comparison is true with zero numerical projection deltas, empty physical GND loss/gain and exact critical record equality. No runtime-net-index exception is needed. All16 critical nets/returns and29 firmware checks pass. I2C electrical status and current numerical power/VCAP remain unqualified.

Source board SHA256:{oldh}
Candidate board SHA256:{h}

SBUS_HV remains open. Initial fixed-source local screens are retained one directory above and are not a global impossibility proof. No experimental SBUS geometry is included.
''')
files={str(p.relative_to(D)):sha(p)for p in D.rglob('*')if p.is_file()and p.name!='route-handoff.json'and p.suffix not in ['.log','.kicad_prl']}
handoff={'schema':'f722-native-route-handoff/v1','status':'frozen_native_verified_33_open_complete_RPM_HV_geometric_WIP_pending_owner_review','board_sha256':h,'integration_source_sha256':oldh,'drc':{'unconnected':33,'errors':0,'warnings':0,'strict_schematic_parity':0,'ERC_violations':0},'pose_reference':'ordinary-routing/candidate45/poses-native.json','all_156_footprints_exact':True,'retained_native_track_via_arc_objects_exact':1383,'source_objects_retained_exact':1941,'removed_source_objects':0,'added_native_objects':9,'new_vias':0,'completed_net':'RPM_HV','new_logical_branches_complete':['RPM_HV::P0'],'completed_terminals':['R25.2','U16.1','Q1.3'],'actual_io_passed':12,'actual_io_total':22,'actual_io_channels_passed':10,'actual_io_channels_total':20,'actual_U16_pad_cut_gap_mm':cut['minimum_gap_measured_mm'],'entry_support_audit':'entry-support-audit.json','entry_support_gates':len(audit['gates']),'negative_controls':len(audit['negative_controls']),'power_wrapper_schema':'f722-native-support-audit/v1','power_wrapper_derived_from_current_native_groups':True,'raw_critical_object_geometry_identical':True,'all_saved_zone_records_exact':True,'critical_reference_deltas_exactly_zero':True,'both_BARO_clean_complete_trees':True,'I2C_electrical_status':'NOT_QUALIFIED','numerical_power_VCAP_applicable':False,'native_refill_performed':False,'native_refill_required':False,'owner_adoption_pending':True,'direct_engine_output':False,'fresh_router_zero_replay_performed':False,'files':files}
write('route-handoff.json',handoff);assert all(sha(D/name)==digest for name,digest in handoff['files'].items());print(json.dumps({'board_sha256':h,'route_handoff_sha256':sha(D/'route-handoff.json'),'sealed_files':len(files),'native_unconnected':33,'negative_controls':handoff['negative_controls']}))
