import pathlib,json,hashlib,shutil
H=pathlib.Path(__file__).resolve().parent;D=H/'candidate02';R=H.parents[2];read=lambda f:json.loads(pathlib.Path(f).read_text());sha=lambda f:hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest();write=lambda f,x:pathlib.Path(f).write_text(json.dumps(x,indent=2)+'\n')
t=read(D/'construction-transaction.json');S=pathlib.Path(t['source_dir']);old=read(S/'f722-heli.native.json');new=read(D/'f722-heli.native.json');fill=read(D/'native-refill.json');h=sha(D/'f722-heli.kicad_pcb');assert h==new['board_sha256']==fill['board_sha256']and fill['unfilled_board_sha256']==t['board_sha256'];assert old['board_sha256']==t['source_board_sha256']==sha(S/'f722-heli.kicad_pcb')
before={o['uuid']:o for o in old['objects']};after={o['uuid']:o for o in new['objects']};removed=set(t['removed_source_ids']);added=set(t['added_ids']);physical=lambda o:{k:v for k,v in o.items()if k!='net_code'}
assert set(after)-set(before)==added and set(before)-set(after)==removed
changed={k for k in before.keys()&after.keys()if physical(before[k])!=physical(after[k])};assert {after[k].get('key')for k in changed}=={'R45.1','R45.2'};assert all(physical(o)==physical(after[k])for k,o in before.items()if k not in removed|changed);f0={f['ref']:f for f in old['footprints']};f1={f['ref']:f for f in new['footprints']};assert {k for k in f0 if f0[k]!=f1[k]}=={'R45'}
for k in ['edge_cuts','outline_with_npth','copper_layers','copper_layer_ids','board_thickness_mm']:assert old[k]==new[k]
zone=lambda z:{k:v for k,v in z.items()if k not in ['filled','fill_representation']};assert list(map(zone,old['zones']))==list(map(zone,new['zones']))
prov=dict(schema='f722-SBUS-R45-native-construction/v1',source_board_sha256=old['board_sha256'],board_sha256=h,source_native_sha256=sha(S/'f722-heli.native.json'),native_sha256=sha(D/'f722-heli.native.json'),constructor_sha256=t['constructor_sha256'],proposal_sha256=sha(D/'proposal.json'),source_object_count=len(before),retained_object_count=len(before)-len(removed),added_object_count=len(added),removed_object_count=len(removed),added_records=[after[k]for k in t['added_ids']],removed_source_records=[before[k]for k in sorted(removed)],routes=t['route_ids'],vias=t['via_ids'],changed_pad_records=[dict(before=before[k],after=after[k])for k in sorted(changed)],changed_footprint_records=[dict(before=f0['R45'],after=f1['R45'])],all_other_source_native_objects_exact_except_net_code=True,full_footprint_count_preserved=len(new['footprints']),full_pad_count_preserved=sum(o['kind']=='pad'for o in new['objects']),native_refill_performed=True,adoption_claimed=False,numerical_power_VCAP_applicable=False)
write(D/'construction-provenance.json',prov);mapping=read(S/'f722-heli.logical-route-map.json');assert mapping['board_sha256']==old['board_sha256'];lm={k:v for k,v in mapping['logical_route_map'].items()if k not in removed};lm.update(t['logical_map_additions']);write(D/'f722-heli.logical-route-map.json',dict(schema='f722-logical-route-map/v1',board_sha256=h,source_sha256=old['board_sha256'],logical_route_map=lm));write(D/'fixed-explicit-native-ids.json',sorted((set(read(S/'fixed-explicit-native-ids.json'))-removed)|added));write(D/'declared-footprint-transforms.json',dict(schema='f722-declared-footprint-transforms/v1',source_board_sha256=old['board_sha256'],board_sha256=h,changes={'R45':{'before':[16.0,10.2,0,'F.Cu'],'after':[11.65,21.8,0,'F.Cu'],'flip_left_right':None}}))
project=read(D/'project-input-preservation.json');project['board_sha256']=h;write(D/'project-input-preservation.json',project)
print(json.dumps(dict(board_sha256=h,added=len(added),removed=len(removed),changed_pads=len(changed))))
