"""Freeze the complete native SBUS transaction and review scopes for owner adoption."""
from pathlib import Path
import json,hashlib,shutil
H=Path(__file__).resolve().parent;R=H.parents[2];D=H/'candidate02';S=H.parent/'port-a48/candidate05'
read=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();write=lambda p,v:Path(p).write_text(json.dumps(v,indent=2)+'\n')
h=sha(D/'f722-heli.kicad_pcb');old=sha(S/'f722-heli.kicad_pcb');assert h=='71d33748909bb960c5829973642272460607d8521831a6212975f7de6790d660';assert old=='80eb38da7100fd677862b8d3bc161329b278c410614f3b15460b5a5c863a75e6'
x=read(D/'owner-summary.json');assert x['board_sha256']==h and x['drc']==x['drc-all']==dict(unconnected=17,errors=0,warnings=0)
for k in ['process','mechanical','parity','firmware']:assert x[k]['passed']and x[k]['board_sha256']==h
assert not x['critical']['faults']and x['critical']['connected_nets']==16 and not x['critical']['missing_ground_returns'];assert not read(D/'owner-drc-parity.json')['schematic_parity'];assert all(not sheet['violations']for sheet in read(D/'owner-erc.json')['sheets'])
for f in ['entry-support-audit.json','power-audit.json','native-coordinated-integration.json','remaining-MCU-access.json']:
 a=read(D/f);assert a['passed']and a['board_sha256']==h
assert read(D/'remaining-MCU-access.json')['complete'];ref=read(D/'new-route-reference-review.json');assert ref['all_new_tracks_reference_complete_outside_explicit_own_via_windows'];c=read(D/'critical-projection-preservation.json');assert c['board_sha256']==h and c['source_board_sha256']==old and c['critical_objects_exact']and c['all_missing_centerline_geometries_equal']and c['all_outside_own_windows_geometries_equal']and c['maximum_actual_lost_ground_width_area_mm2']==0
actual=read(D/'protection-actual-io.json');previous=read(S/'protection-actual-io.json');assert actual['passed']==18 and actual['total']==22;now={r['id']:r for r in actual['checks']};assert all(now[r['id']]['complete_clamp_first_path_passes']for r in previous['checks']if r['complete_clamp_first_path_passes']);sb=next(r for r in actual['checks']if r['net']=='SBUS_MCU');assert sb['complete_clamp_first_path_passes']and sb['minimum_gap_measured_mm']>=.127
prov=read(D/'construction-provenance.json');assert len(prov['added_records'])==46 and len(prov['removed_source_records'])==5 and len(prov['changed_pad_records'])==2;assert {r['net']for r in prov['removed_source_records']}=={'SBUS_LV'};assert len(prov['vias'])==5
for name in ['construct_sbus_native19.py','audit_sbus_native_final.py','audit_sbus_entries_final.py','extra_sbus_gates_final.py','reference_sbus_routes_final.py','verify_remaining_access17.py','rebind_final_sbus.py','composite_sbus_native19b.py','route_complete_sbus50.py','seal_sbus17.py']:
 shutil.copy2(H/name,D/(Path(name).stem+'.used.py'))
for name in ['final19-proposal.json','final19-screen.json','reference-corrected-sbus19-proposal.json']:shutil.copy2(H/name,D/name)
shutil.copytree(H/'conditional-signal-review',D/'conditional-signal-review',dirs_exist_ok=True)
receipt=dict(schema='f722-complete-SBUS-coordinated-change/v1',source_board_sha256=old,board_sha256=h,allowed_changed_nets=['SBUS_LV','SBUS_MCU'],completed_nets=['SBUS_MCU'],restored_complete_nets=['SBUS_LV'],footprint_transforms={'R45':{'before':[16,10.2,0,'F.Cu'],'after':[11.65,21.8,0,'F.Cu']}},all_other155_footprints_exact=True,changed_pad_count=2,all_existing_vias_exact=True,removed_source_records=prov['removed_source_records'],added_records=prov['added_records'],all82_new_endpoints_finitely_connected=True,all28_support_groups_restored=True,actual_clamp_source='R45.2',actual_clamp='U13.1',actual_clamp_target='U1.17',actual_outside_pad_gap_mm=sb['minimum_gap_measured_mm'],complete_NRST_already_in_source_and_exact=True,all_prior_actual_protection_passes_preserved=True,actual_cases_passed=18,actual_cases_total=22,actual_channels_passed=16,actual_channels_total=20,new_reference='new-route-reference-review.json',critical_reference='critical-projection-preservation.json',all_new_reference_complete_outside_own_via_windows=True,critical_reference_nonzero_numeric_delta_retained=c['numeric_deltas_retained'],electrical_review='conditional-signal-review/SBUS-electrical-review.md',numerical_power_VCAP_applicable=False,SBUS_electrically_qualified=False,owner_adoption_claimed=False)
write(D/'coordinated-change-receipt.json',receipt)
write(D/'power-revalidation-required.json',dict(board_sha256=h,source_board_sha256=old,numerical_power_and_VCAP_applicability=False,geometric_support_continuity_passed=True,all28_support_groups_exact=True,reference_planes_refilled=True,reason='Five added ordinary signal vias and moved R45 alter filled GND geometry. Source43 numerical power results are historical; fresh current-source power/VCAP qualification remains required.',transient_qualification_claimed=False,I2C_electrical_status='NOT_QUALIFIED',SBUS_waveform_and_ESD_qualification=False))
write(D/'f722-heli.import.json',dict(schema='f722-explicit-coordinated-native-construction-receipt/v1',passed=True,source_sha256=old,output_sha256=h,construction_source_sha256=old,construction_kind='Complete SBUS_MCU actual-clamp tree, complete relocated R45/SBUS_LV reconstruction; five old LV tracks replaced by41 tracks and5 vias. Complete source NRST and all other support retained.',direct_engine_output=False,engine_routing_succeeded=False,engine_partial_geometry_adopted=False,ses_engine_native_geometry_equal=False,session_artifact=None,coordinated_change_receipt='coordinated-change-receipt.json',coordinated_change_receipt_sha256=sha(D/'coordinated-change-receipt.json'),construction_provenance='construction-provenance.json',construction_provenance_sha256=sha(D/'construction-provenance.json'),logical_route_map_artifact='f722-heli.logical-route-map.json',logical_route_map_sha256=sha(D/'f722-heli.logical-route-map.json'),undeclared_native_changes=0,footprints_preserved=155,footprints_transformed=1,reference_plane_refill_performed=True,fresh_model_zero_control_performed=False,numerical_power_VCAP_applicable=False,owner_review=None))
(D/'README.md').write_text('''# Complete SBUS native candidate17

Source: final shared A/B native19, PCB80eb38da…a75e6. Candidate:71d33748…90d660. Native17 opens/0 errors/0 warnings, strict parity and ERC clean. Owner adoption is pending.

This complete transaction closes the protected R45.2→U13.1→U1.17 tree, relocates R45 inward to F(11.65,21.8), and reconstructs the complete SBUS_LV pull-up/pass-FET branch.41 tracks and5 ordinary tented vias replace5 old LV tracks. All155 other footprints,556 other pad records and existing vias are exact. Complete source NRST is unchanged.

All82 new endpoints have finite pad, junction or actual-annulus proof. All28 support groups and all prior actual cuts remain complete.18/22 actual cases and16/20 channels pass, with U13.1 outside-pad branch gap0.170269mm. Remaining signals are explicitly unfinished.

Both new nets have zero saved-plane centerline and finite-width gap outside explicit own-via windows. Critical copper and outside-own-window missing reference geometries are exact; raw BARO_SDA width delta−2.3792756653762126e−10mm² is retained, with zero actual lost critical width overlap. Whole-plane equality and AC-return qualification are not claimed.

SBUS_LV is75.647640mm; SBUS_MCU is50.990697mm. The pinned default100k SBUS has conditional RC support, with optional200k requiring a substantially smaller load budget. Unknown receiver/cable, nonlinear FET loading and low-level behavior prevent an electrical-release guarantee. See conditional-signal-review. Fresh numerical power/VCAP qualification remains pending.
''')
handoff=dict(schema='f722-native-route-handoff/v1',status='frozen_native_verified_17_open_complete_SBUS_geometric_WIP_pending_owner_review',board_sha256=h,integration_source_sha256=old,source_dir=str(S.relative_to(R)),drc=dict(unconnected=17,errors=0,warnings=0,strict_schematic_parity=0,ERC_violations=0),pose_reference=str((D/'poses-native.json').relative_to(R)),declared_footprint_transforms='declared-footprint-transforms.json',coordinated=True,allowed_changed_nets=['SBUS_LV','SBUS_MCU'],exact_unchanged_footprints=155,changed_pad_count=2,all_existing_vias_exact=True,removed_source_objects=5,added_native_objects=46,new_signal_vias=5,completed_net='SBUS_MCU',restored_complete_nets=['SBUS_LV'],entry_support_audit='entry-support-audit.json',remaining_access='remaining-MCU-access.json',new_route_reference_review='new-route-reference-review.json',critical_reference_review='critical-projection-preservation.json',critical_numeric_deltas_retained=c['numeric_deltas_retained'],actual_cases_passed=18,actual_cases_total=22,actual_channels_passed=16,actual_channels_total=20,SBUS_electrical_review='conditional-signal-review/SBUS-electrical-review.md',SBUS_electrical_status='NOT_QUALIFIED',I2C_electrical_status='NOT_QUALIFIED',numerical_power_VCAP_applicable=False,owner_adoption_pending=True,direct_engine_output=False,fresh_router_zero_replay_performed=False)
handoff['files']={str(p.relative_to(D)):sha(p)for p in sorted(D.rglob('*'))if p.is_file()and p.name!='route-handoff.json'};write(D/'route-handoff.json',handoff);assert all(sha(D/n)==z for n,z in handoff['files'].items());print(json.dumps(dict(board_sha256=h,files=len(handoff['files']),remaining=17,status=handoff['status'])))
