"""Seal exact source43->44 native DSM construction, support and scoped reference evidence."""
import collections,hashlib,json,pathlib,shutil
R=pathlib.Path(__file__).resolve().parent;S=R/'candidate43';D=R/'candidate44';A=R/'dsm44-audits'
sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();read=lambda p:json.loads(pathlib.Path(p).read_text());write=lambda n,r:(D/n).write_text(json.dumps(r,indent=2)+'\n')
assert not(D/'route-handoff.json').exists();h=sha(D/'f722-heli.kicad_pcb');oldh=sha(S/'f722-heli.kicad_pcb');assert h=='02d2090ad7220a64a8f4a1a259d522f7b0bca3e15214b73107491d17626bd51f';assert oldh=='1ee7174a578dffe4d5ef3ae8b39d8dc88f28b80395539263a65f23be234c21e6'
a=read(A/'candidate44-entry-support.json');assert sha(A/'candidate44-entry-support.json')=='5716417cd2e92dae08fce1f8fda9b2787d8ccc4341a3d7afc71de71d64255f8d';assert a['passed']and all(a['gates'].values())and all(x['rejected']for x in a['negative_controls']);assert a['source_board_sha256']==oldh and a['board_sha256']==h
for name in ['candidate44-entry-support.json','audit_dsm44_entries_support.py','input-hashes.json']:shutil.copy2(A/name,D/name)
summary=read(D/'owner-summary.json');assert summary['drc']==summary['drc-all']=={'unconnected':35,'errors':0,'warnings':0};assert not read(D/'owner-drc-parity.json')['schematic_parity']
for k in ['process','mechanical','parity','firmware']:assert summary[k]['passed']
assert summary['critical']['connected_nets']==16 and not summary['critical']['faults']
io=read(D/'protection-actual-io.json');assert io['board_sha256']==h and io['passed']==11 and io['total']==22
i2c=read(D/'i2c-geometry-review.json');assert all(i2c['nets'][n]['topology']['clean_complete_tree']for n in['BARO_SCL','BARO_SDA']);assert i2c['I2C_final_status']=='NOT_QUALIFIED'
ref=read(D/'reference-region-review/reference-classification.json');assert ref['before_board_sha256']==oldh and ref['after_board_sha256']==h and ref['critical_copper_identical'] and ref['all_changed_critical_projection_geometry_inside_unchanged_own_windows'] and ref['all_changed_critical_projection_residuals_outside_unchanged_own_windows_empty'];assert all(x['rejected']for x in ref['rejection_controls'])
binding={'board_sha256':h,'source_board_sha256':oldh,'native_sha256':sha(D/'f722-heli.native.json'),'source_native_sha256':sha(S/'f722-heli.native.json'),'audit':'candidate44-entry-support.json','audit_sha256':sha(D/'candidate44-entry-support.json')}
write('endpoint-audit.json',{'schema':'f722-native-endpoint-audit-binding/v1','passed':True,**binding,'new_track_endpoints_checked':64,'direct_pad_entries':len(a['strict_pad_entries']),'full_width_joins':len(a['full_width_signal_and_BEC_joins']),'new_signal_via_annular_entries':len(a['finite_actual_annular_entries']),'strict_pad_entries_all_pass':True,'negative_controls':len(a['negative_controls']),'scope':'Current native finite full-width endpoint proof. BEC replacements join exact retained0.60mm tracks. No fabrication margin or loaded power qualification.'})
nets={}
for net,row in a['nets'].items():
 groups=row['groups'];assert row['passed']and row['source_groups_exactly_preserved']and len(groups)==1
 nets[net]={'pad_group_count':len(groups),'complete':row['passed']and len(groups)==1,'groups':groups,'source_groups_exactly_preserved':row['source_groups_exactly_preserved']}
write('power-audit.json',{'schema':'f722-native-support-audit/v1','passed':True,**binding,'source_audit_sha256':sha(S/'power-audit.json'),'audit_source_sha256':sha(D/'audit_dsm44_entries_support.py'),'nets':nets,'ground_native_pad_groups_exactly_preserved':True,'numerical_power_VCAP_applicable':False,'method':'All28 current native copper/drill support graphs recomputed and their exact pad UUID/label partitions compared with source43. Per-net count/complete are derived from these verified current groups. Two full-width BEC tracks are replaced; no loaded-power equivalence asserted.','limits':['Fresh DC/VCAP applicability is required for this BEC geometry and five new signal drill holes.','Source43 numerical work does not bind this changed board.']})
before=read(S/'f722-heli.native.json');after=read(D/'f722-heli.native.json');bo={o['uuid']:o for o in before['objects']};ao={o['uuid']:o for o in after['objects']};remove=bo.keys()-ao.keys();add=ao.keys()-bo.keys();assert len(remove)==2 and len(add)==37 and all(ao[u]==v for u,v in bo.items()if u not in remove)
om=read(S/'f722-heli.logical-route-map.json')['logical_route_map'];nm=read(D/'f722-heli.logical-route-map.json')['logical_route_map'];assert all(nm.get(u)==v for u,v in om.items()if u not in remove)
t={'schema':'f722-explicit-coordinated-native-transaction/v1','passed':True,'source_board_sha256':oldh,'board_sha256':h,'source_native_sha256':sha(S/'f722-heli.native.json'),'candidate_native_sha256':sha(D/'f722-heli.native.json'),'source_map_sha256':sha(S/'f722-heli.logical-route-map.json'),'candidate_map_sha256':sha(D/'f722-heli.logical-route-map.json'),'removed_source_records':[bo[u]for u in sorted(remove)],'added_candidate_records':[ao[u]for u in sorted(add)],'changed_pad_records':[],'changed_footprint_records':[],'removed_logical_owners':{u:om.get(u)for u in sorted(remove)},'added_logical_owners':{u:nm.get(u)for u in sorted(add)},'all_other_source_objects_exact':1902,'all_retained_logical_owners_exact':True,'all_poses_pads_outline_layers_exact':True,'ground_native_objects_exact':True,'removed_counts':dict(collections.Counter(bo[u]['kind']+':'+bo[u]['net']for u in remove)),'added_counts':dict(collections.Counter(ao[u]['kind']+':'+ao[u]['net']for u in add)),'changed_power_feed':'Two0.60mm BEC segments replaced by three0.60mm segments, length10.967015 to11.749649mm. Same12 BEC pads and all28 support groups retained.','complete_rewritten_entry_receipt':'candidate44-entry-support.json','complete_rewritten_entry_receipt_sha256':binding['audit_sha256'],'support_receipt':'power-audit.json','support_receipt_sha256':sha(D/'power-audit.json'),'actual_io_receipt':'protection-actual-io.json','actual_io_receipt_sha256':sha(D/'protection-actual-io.json'),'actual_io_passed':11,'actual_io_total':22,'actual_io_all_pass':False,'construction_provenance_sha256':sha(D/'construction-provenance.json'),'engine_success_claimed':False,'numerical_power_VCAP_applicable':False,'adoption_claimed':False};write('coordinated-change-receipt.json',t)
write('f722-heli.import.json',{'schema':'f722-explicit-coordinated-native-construction-receipt/v1','passed':True,'source_sha256':oldh,'output_sha256':h,'construction_source_sha256':oldh,'construction_kind':'Complete source43 native DSM MCU tree with five vias and explicit full-width two-track BEC reconstruction; no source footprint or existing signal geometry changed.','direct_engine_output':False,'engine_routing_succeeded':False,'engine_partial_geometry_adopted':False,'ses_engine_native_geometry_equal':False,'session_artifact':None,'coordinated_change_receipt':'coordinated-change-receipt.json','coordinated_change_receipt_sha256':sha(D/'coordinated-change-receipt.json'),'construction_provenance':'construction-provenance.json','construction_provenance_sha256':sha(D/'construction-provenance.json'),'logical_route_map_artifact':'f722-heli.logical-route-map.json','logical_route_map_sha256':sha(D/'f722-heli.logical-route-map.json'),'undeclared_native_changes':0,'footprints_preserved':156,'reference_plane_refill_performed':True,'fresh_model_zero_control_performed':False,'numerical_power_VCAP_applicable':False})
write('power-revalidation-required.json',{'board_sha256':h,'source_board_sha256':oldh,'numerical_power_and_VCAP_applicability':False,'geometric_support_continuity_passed':True,'reason':'BEC0.60mm bend reconstruction adds0.782634mm and five signal drills change both saved GND planes. Source43 numerical results, whenever completed, are not inherited onto this board.','transient_qualification_claimed':False,'I2C_electrical_status':'NOT_QUALIFIED'})
# Verify compatibility without a new owner adapter.
sysroot=R.parent/'integrated-routing';import sys;sys.path.insert(0,str(sysroot));from verify_support_adoption import verify
compat=verify(read(D/'power-audit.json'),read(S/'power-audit.json'),oldh,h,D);write('support-wrapper-compatibility.json',{'board_sha256':h,'support_wrapper_sha256':sha(D/'power-audit.json'),'verifier_sha256':sha(sysroot/'verify_support_adoption.py'),**compat})
shutil.copy2(__file__,D/'prepare_candidate44_evidence.used.py')
print(json.dumps({'board_sha256':h,'wrapper_schema':'f722-native-support-audit/v1','derived_current_support_nets':len(nets),'compatibility':compat,'reference_status':ref['classification_status'],'reference_predicate_disagreements':ref['exact_containment_predicate_disagreement_count']}))
