import app.freerouting.Freerouting;import app.freerouting.settings.*;import app.freerouting.board.*;import app.freerouting.core.*;import app.freerouting.interactive.*;import app.freerouting.designforms.specctra.DsnFile;import app.freerouting.management.analytics.FRAnalytics;import com.google.gson.*;import java.nio.file.*;import java.util.*;
/** Full native model serialization control; no route search or PCB changes. */
public final class FullNativeCopyControl {
 public static void main(String[] args)throws Exception{
  Path dir=Path.of(args[0]);JsonObject model=JsonParser.parseString(Files.readString(dir.resolve("model.json"))).getAsJsonObject();for(var e:model.getAsJsonObject("adapter_sources").entrySet())if(!LocalRouter.hash(Path.of(e.getKey())).equals(e.getValue().getAsString()))throw new AssertionError("Adapter source drift");String source=model.get("board_sha256").getAsString();
  Freerouting.globalSettings=new GlobalSettings();Freerouting.globalSettings.usageAndDiagnosticData.disableAnalytics=true;Freerouting.globalSettings.apiServerSettings.isEnabled=false;FRAnalytics.setEnabled(false);RoutingJob job=new RoutingJob();HeadlessBoardManager mgr=new HeadlessBoardManager(Locale.ENGLISH,job);if(mgr.loadFromSpecctraDsn(Files.newInputStream(dir.resolve("routing.dsn")),new BoardObserverAdaptor(),new ItemIdentificationNumberGenerator())!=DsnFile.ReadResult.OK)throw new AssertionError("DSN");RoutingBoard b=mgr.get_routing_board();NativeGuardFactory.install(b,model);model=null;String fixed=LocalRouter.fixedGeometryHash(b);JsonObject before=LocalRouter.snapshot(b,false);long started=System.nanoTime();RoutingBoard copy=b.deepCopy();if(copy==null)throw new AssertionError("Full native deepCopy failed");double seconds=(System.nanoTime()-started)/1e9;
  JsonObject after=LocalRouter.snapshot(copy,false);if(!before.equals(after)||!fixed.equals(LocalRouter.fixedGeometryHash(copy)))throw new AssertionError("Copy changed native partitions or geometry");Map<Integer,Item> identities=new HashMap<>();for(Item i:copy.get_items())identities.put(i.get_id_no(),i);int contacts=0,peers=0;for(Item i:copy.get_items())if(i instanceof NativePadContactArea c){contacts++;for(Item peer:c.get_normal_contacts()){if(identities.get(peer.get_id_no())!=peer)throw new AssertionError("Copied contact references another board's item");peers++;}}
  JsonObject out=new JsonObject();out.addProperty("passed",true);out.addProperty("board_sha256",source);out.addProperty("model_sha256",LocalRouter.hash(dir.resolve("model.json")));out.addProperty("deep_copy_seconds",seconds);out.addProperty("contact_items",contacts);out.addProperty("contact_references_checked",peers);out.addProperty("contact_partitions",after.getAsJsonArray("contact_partitions").size());out.addProperty("exact_fixed_geometry_and_partitions",true);out.addProperty("route_solver_used",false);Files.writeString(Path.of(args[1]),new GsonBuilder().setPrettyPrinting().create().toJson(out));System.out.println(out);
 }
}
