#!/usr/bin/env python3
"""Explicit post-router terminal completion inside an actual native pad.
Only extends one existing terminal segment along its own line; does not route a net.
"""
import argparse,collections,hashlib,json,math,re
from pathlib import Path
from shapely import unary_union
from shapely.geometry import Polygon,Point,LineString
ap=argparse.ArgumentParser();ap.add_argument('--session',type=Path,required=True);ap.add_argument('--engine-report',type=Path,required=True);ap.add_argument('--native',type=Path,required=True);ap.add_argument('--net',required=True);ap.add_argument('--pad',required=True);ap.add_argument('--out-prefix',type=Path,required=True);a=ap.parse_args();sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();n=json.loads(a.native.read_text());e=json.loads(a.engine_report.read_text());pads=[p for p in n['objects']if p['kind']=='pad'and p['key']==a.pad and p['net']==a.net];assert len(pads)==1;pad=pads[0];routes=[r for r in e['routes']if r['fixed']!='SYSTEM_FIXED'and r['nets']==[a.net]and r['kind']=='track'];degree=collections.Counter(tuple(p)for r in routes for p in [r['points'][0],r['points'][-1]]);matches=[]
for r in routes:
 if r['layer']not in pad['inside']:continue
 inside=unary_union([Polygon(p['outer'],p.get('holes',[]))for p in pad['inside'][r['layer']]])
 for index,neighbor in [(0,1),(-1,-2)]:
  old=r['points'][index]
  if degree[tuple(old)]==1 and inside.contains(Point(old)):matches.append((r,index,neighbor,inside))
assert len(matches)==1,'Need one terminal centerline already inside the requested pad';r,index,neighbor,inside=matches[0];old=r['points'][index];q=r['points'][neighbor];length=math.dist(old,q);direction=[(old[i]-q[i])/length for i in (0,1)];radius=r['width']/2;safe=inside.buffer(-radius-.00002);assert not safe.is_empty;bounds=inside.bounds;extent=2*math.hypot(bounds[2]-bounds[0],bounds[3]-bounds[1]);ray=LineString([old,[old[i]+direction[i]*extent for i in (0,1)]]);feasible=safe.intersection(ray);parts=[feasible]if feasible.geom_type=='LineString'else [g for g in feasible.geoms if g.geom_type=='LineString'];parts=[p for p in parts if p.length>0];assert parts,'Original terminal line must reach a full-width native pad interior';part=min(parts,key=lambda p:p.distance(Point(old)));new=[round(v,5)for v in part.interpolate(.5,normalized=True).coords[0]];assert safe.covers(Point(new));assert inside.covers(LineString([old,new])),'Added centerline must remain inside its own native pad';text=a.session.read_text();assert re.search(r'\(resolution\s+mm\s+100000\)',text);oldints=[round(old[0]*1e5),-round(old[1]*1e5)];newints=[round(new[0]*1e5),-round(new[1]*1e5)];pattern=r'(?<![\d.\-])'+str(oldints[0])+r'\s+'+str(oldints[1])+r'(?![\d.])';assert len(re.findall(pattern,text))==1,'Endpoint must occur once in the actual session';text=re.sub(pattern,f'{newints[0]} {newints[1]}',text,count=1);r['points'][index]=new;fix={'kind':'explicit_native_pad_endpoint_completion','logical_net':a.net,'pad':a.pad,'pad_uuid':pad['uuid'],'layer':r['layer'],'old_xy_mm':old,'new_xy_mm':new,'extension_mm':math.dist(old,new),'width_mm':r['width'],'new_centerline_in_native_inside_pad':True,'new_endpoint_in_half_width_eroded_pad':True,'native_inside_erosion_mm':radius+.00002,'original_session_sha256':sha(a.session),'original_engine_report_sha256':sha(a.engine_report),'native_geometry_sha256':sha(a.native),'native_board_sha256':n['board_sha256'],'not_a_new_router_run':True};e['native_pad_endpoint_completion']=fix;e['native_validation_required']=True;a.out_prefix.parent.mkdir(parents=True,exist_ok=True);ses=Path(str(a.out_prefix)+'.ses');report=Path(str(a.out_prefix)+'.after.json');ses.write_text(text);report.write_text(json.dumps(e,indent=2)+'\n');fix.update(output_session_sha256=sha(ses),output_report_sha256=sha(report),completion_source_sha256=sha(__file__));Path(str(a.out_prefix)+'.endpoint-completion.json').write_text(json.dumps(fix,indent=2)+'\n');print(json.dumps(fix))
