from pathlib import Path
import json,shutil,hashlib,datetime
R=Path(__file__).resolve().parents[1];N=R/'repo/f722-heli/layout-revision';C=N/'checks';S=R/'checkpoint13-owner-review';D=R/'ordinary-routing/candidate55';O=C/'checkpoint55-integration';h=hashlib.sha256((D/'f722-heli.kicad_pcb').read_bytes()).hexdigest()
def read(p):return json.loads(p.read_text())
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
for f in ['owner-adoption-assessment.json','all-net-reference-summary.json','all-net-comparison.json','all-routed-net-targets.json','inspect_selected_reference.py','summarize_all_net_reference.py','reference-window-v1.log']:
 shutil.copy2(S/f,O/f)
for f in ['entry-support-audit.json','power-audit-sealed-original.json','power-audit.json','owner-summary.json']:
 shutil.copy2(D/f,O/f)
shutil.copytree(R/'ordinary-routing/tests/small-signal-review54',O/'conditional-signal-review',dirs_exist_ok=True)
shutil.copy2(R/'checkpoint13-placement-reproduction-native/placement-reproduction.json',C/'placement13-reproduction.json')
s=read(C/'current-status.json');s['loaded_power_diagnostic']=s['loaded_power_diagnostic'].replace('Current14','Current13');s['current_numerical_power_status']=s['current_numerical_power_status'].replace('current14','current13');s['placement_recipe_current_evidence']='placement13-reproduction.json';s['placement_transform_current_evidence']='transform-placement13.json';s['placement_recipe_original_reproduction']='placement13-reproduction.json';s['i2c_routing']['source_board_sha256']=h
s['historical_adc_bus_review']=s.pop('adc_bus_review');s['historical_reference_preservation']=s.pop('reference_preservation')
s['adc_bus_review']={'board_sha256':h,'complete':True,'receipt':'checkpoint55-integration/conditional-signal-review/review-receipt.json','nominal_divider_ratio':0.32,'nominal_RC_ms':4.7872,'hardware_noise_or_accuracy_qualified':False,'reference_receipt':'checkpoint55-integration/all-net-reference-summary.json','scope':'Current ADC_BUS and MID rerouted; prior physical branch lengths and reference equality statements are historical. Effective C31, acquisition settings and ADC noise remain conditional.'}
s['reference_preservation']={'board_sha256':h,'receipt':'checkpoint55-integration/reference-window-classification.json',**read(D/'owner-adoption.json')['reference_window_classification'],'all_routed_nets_receipt':'checkpoint55-integration/all-net-reference-summary.json','AC_or_impedance_qualification':False}
s['changed_signal_review']={'board_sha256':h,'receipt':'checkpoint55-integration/conditional-signal-review/README.md','DSM_main_receive_path_mm':136.672265,'GREEN_total_planar_mm':71.87564991794923,'electrical_qualification':False}
write(C/'current-status.json',s)
p=N/'README.md';t=p.read_text().replace('checks/checkpoint14-owner-review.json','checks/checkpoint13-owner-review.json');anchor='Checkpoint54 completes';t=t.replace(anchor,'Checkpoint55 completes GREEN while rebuilding DSM, ADC and static flash pull-up routes. Only R44 rotates in place; all 156 poses and 558 native pad records reproduce. The [source-bound signal review](checks/checkpoint55-integration/conditional-signal-review/README.md) records the 136.672 mm DSM main receive path and 71.876 mm GREEN route, with loading and waveform limits still open. All 86 routed-net reference projections were inspected: 79 unchanged nets retain exact copper, while changed nets have no centerline gaps outside their own via windows. Finite width-edge residues remain. Eight exact actual-hole boundary predicate conflicts remain unresolved; the [owner assessment](checks/checkpoint55-integration/owner-adoption-assessment.json) preserves the failed stricter test and all limitations. Both ground planes remain connected with 117 plated ties, which does not establish current capacity or AC return quality. Fresh numerical power/VCAP remains pending.\n\nThe preceding '+anchor)
t=t.replace('ADC_BUS remains complete, with C31 inward beside the MCU. Its capacitor branch is now','Historical source49 ADC_BUS was complete, with C31 inward beside the MCU. Its then-current capacitor branch was').replace('**18 of 22 endpoint cases, covering 16 of 20 bonded protection channels**. Four channels remain unfinished.','**20 of 22 endpoint cases, covering 18 of 20 bonded protection channels**. Two channels remain unfinished.').replace('original 18-check convention has 14 passes','original 18-check convention has 16 passes');p.write_text(t)
p=R/'ACTIVE-STATE.json';d=read(p);d['updated_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();d['owner_current_review']={'source':'ordinary-routing/candidate55','board_sha256':h,'assessment':'checkpoint13-owner-review/owner-adoption-assessment.json','actual_hole_predicate_conflicts':8,'numerical_power_current':False};write(p,d)
with (R/'OWNER-RESUME.md').open('a') as f:f.write('\n\n2026-10-10 04:10 UTC: Accepted candidate55, 13 opens/0 errors/0 warnings; PCB '+h+'. Placement156/pads558 reproduced. Owner review checkpoint13-owner-review; 8 unresolved actual-hole boundary predicates explicitly retained. Fresh power pending. Original sealed support report retained alongside additive group-count serialization adapter. Frozen14 publisher unaffected.\n')
print('Canonical13 evidence refreshed; power/AC limits retained.')
