import pathlib,json,hashlib,sys,math
H=pathlib.Path(__file__).resolve().parent;R=H.parents[2];S=R/'ordinary-routing/candidate48';D=H/'candidate01';T=R/'repo/f722-heli/layout-revision/signal-review/native';sys.path.insert(0,str(T))
from check_signal_geometry import poly,centerline,copper_entries
from check_critical_reference import ground_geometry,REFERENCE
from shapely.geometry import Point,mapping
from shapely.ops import unary_union
read=lambda f:json.loads(pathlib.Path(f).read_text());sha=lambda f:hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest()
n=read(D/'f722-heli.native.json');old=read(S/'f722-heli.native.json');h=sha(D/'f722-heli.kicad_pcb');assert n['board_sha256']==h;_,zones,physical,drills=ground_geometry(n,copper_entries(n));nets=['PORT_A_TX_MCU','PORT_A_RX_MCU','ADC_BUS'];rows=[]
for net in nets:
 vias=[o for o in n['objects']if o['net']==net and o['kind']=='via'];windows=unary_union([Point(o['xy']).buffer(o['width']/2+.127+.01,quad_segs=96)for o in vias])
 for o in n['objects']:
  if o['net']!=net or o['kind']!='track':continue
  layer=next(iter(o['copper']));ref=REFERENCE[layer];line=centerline(o);cu=poly(o['copper'][layer]);miss=line.difference(physical[ref]);wm=cu.difference(physical[ref]);outside=miss.difference(windows);wo=wm.difference(windows)
  rows.append(dict(uuid=o['uuid'],net=net,layer=layer,reference_layer=ref,length_mm=line.length,centerline_missing_mm=miss.length,width_missing_mm2=wm.area,centerline_outside_own_via_windows_mm=outside.length,width_outside_own_via_windows_mm2=wo.area,outside_centerline_empty=outside.is_empty,outside_width_empty=wo.is_empty,actual_centerline_missing_geometry=mapping(miss),actual_width_missing_geometry=mapping(wm),own_via_windows=[dict(uuid=v['uuid'],xy=v['xy'],radius_mm=v['width']/2+.127+.01)for v in vias]))
by={net:dict(track_count=sum(r['net']==net for r in rows),total_track_length_mm=sum(r['length_mm']for r in rows if r['net']==net),centerline_missing_mm=sum(r['centerline_missing_mm']for r in rows if r['net']==net),width_missing_mm2=sum(r['width_missing_mm2']for r in rows if r['net']==net),outside_own_windows_centerline_mm=sum(r['centerline_outside_own_via_windows_mm']for r in rows if r['net']==net),outside_own_windows_width_mm2=sum(r['width_outside_own_via_windows_mm2']for r in rows if r['net']==net),all_reference_outside_own_windows_empty=all(r['outside_centerline_empty']and r['outside_width_empty']for r in rows if r['net']==net))for net in nets}
phys=lambda o:{k:v for k,v in o.items()if k!='net_code'};op={o['uuid']:o for o in old['objects']if o['kind']=='pad'};np={o['uuid']:o for o in n['objects']if o['kind']=='pad'};assert op.keys()==np.keys()and all(phys(op[u])==phys(np[u])for u in op)and old['footprints']==n['footprints']
out=dict(schema='f722-PORT-A-local-return-projection/v1',board_sha256=h,source_board_sha256=old['board_sha256'],native_sha256=sha(D/'f722-heli.native.json'),all_full_footprints_exact=len(n['footprints']),all_full_pad_records_exact=len(np),summary=by,tracks=rows,own_via_window_formula='actual via radius + 0.127mm clearance + 2*0.005mm native-design polygon allowance',dc_connectivity_separate_from_ac_return=True,AC_signal_integrity_or_EMC_qualification=False,numerical_power_qualification=False,limits=['This records exact saved-plane centerline and finite-width projection. Empty outside-window projection is a geometric check only.','Own-via windows are reported explicitly, not claimed to be solid reference copper.','No transient return-current extraction, crosstalk, EMI, manufacturing-tolerance or flight qualification is claimed.'])
_,_,oldphysical,_=ground_geometry(old,copper_entries(old));oldby={o['uuid']:o for o in old['objects']};oldwindows=unary_union([Point(o['xy']).buffer(o['width']/2+.127+.01,quad_segs=96)for o in old['objects']if o['net']=='ADC_BUS'and o['kind']=='via']);inherited=[]
for row in rows:
 if row['net']!='ADC_BUS' or row['width_outside_own_via_windows_mm2']==0:continue
 o=oldby[row['uuid']];layer=next(iter(o['copper']));g=poly(o['copper'][layer]).difference(oldphysical[REFERENCE[layer]]).difference(oldwindows);current=poly(next(q for q in n['objects']if q['uuid']==o['uuid'])['copper'][layer]).difference(physical[REFERENCE[layer]]).difference(oldwindows);assert g.equals(current);inherited.append(dict(uuid=o['uuid'],source_width_gap_mm2=g.area,candidate_width_gap_mm2=current.area,exact_geometry_equal=True))
added={o['uuid']for o in read(D/'construction-provenance.json')['added_records']};assert all(r['outside_centerline_empty']and r['outside_width_empty']for r in rows if r['uuid']in added)
out.update(all_new_or_changed_tracks_reference_complete_outside_explicit_own_via_windows=True,unchanged_ADC_source_width_gaps=inherited,source_ADC_existing_gap_total_mm2=sum(r['source_width_gap_mm2']for r in inherited))
(D/'new-route-reference-review.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(dict(board_sha256=h,summary=by,full_footprints=len(n['footprints']),full_pads=len(np))))
