import pathlib,json,hashlib,shutil,math
H=pathlib.Path(__file__).resolve().parent;D=H/'candidate01';R=H.parents[2];S=R/'ordinary-routing/candidate48'
read=lambda p:json.loads(pathlib.Path(p).read_text());sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();write=lambda p,v:pathlib.Path(p).write_text(json.dumps(v,indent=2)+'\n')
h=sha(D/'f722-heli.kicad_pcb');old=sha(S/'f722-heli.kicad_pcb');summary=read(D/'owner-summary.json');assert summary['board_sha256']==h and summary['drc']==summary['drc-all']==dict(unconnected=29,errors=0,warnings=0)
for k in ['process','mechanical','parity','firmware']:assert summary[k]['passed']and summary[k]['board_sha256']==h
assert not read(D/'owner-drc-parity.json')['schematic_parity'];assert not summary['critical']['faults']and summary['critical']['connected_nets']==16
for name in ['entry-support-audit.json','power-audit.json','native-coordinated-integration.json','remaining-access.json']:
 q=read(D/name);assert q['passed']and q['board_sha256']==h
ref=read(D/'new-route-reference-review.json');assert ref['all_new_or_changed_tracks_reference_complete_outside_explicit_own_via_windows']and ref['all_full_footprints_exact']==156 and ref['all_full_pad_records_exact']==558
comp=read(D/'reference-comparison48.json');assert comp['critical_object_geometry_identical']and all(all(v==0 for v in row.values())for row in comp['net_numeric_deltas_after_minus_before'].values())
classify=read(H/'reference-classification.json');assert classify['source_binding_verified']and classify['before_board_sha256']==old and classify['after_board_sha256']==h and classify['missing_centerline_geometries_exactly_equal']and classify['exact_containment_predicate_disagreement_count']==0
region=D/'reference-region-review';region.mkdir(exist_ok=True)
for name in ['reference-classification.json','reference-classification.log','classify_reference_delta.py']:shutil.copy2(H/name,region/name)
for name in ['construct_mcu.py','audit_mcu.py','extra_gates.py','electrical_screen.py','reference_routes.py','final_access.py','seal_mcu.py','native_geometry.py','inspect_access.py','route_centered.py','compact_mcu_proposal.py']:
 shutil.copy2(H/name,D/(pathlib.Path(name).stem+'.used.py'))
for name in ['compact-mcu-proposal.json','rx-centered-In2.Cu.json','pad-access-comparison.json','proposal.json']:shutil.copy2(H/name,D/name)
p=read(D/'proposal.json');prov=read(D/'construction-provenance.json');elec=read(D/'adc-electrical-screen.json');assert elec['board_sha256']==h and math.isclose(elec['topology']['capacitor_to_U1_pad_path_mm'],6.9633624394244125)
write(D/'coordinated-change-receipt.json',dict(schema='f722-PORT-A-complete-MCU-reconstruction/v1',source_board_sha256=old,board_sha256=h,changed_nets=['PORT_A_TX_MCU','PORT_A_RX_MCU','ADC_BUS'],removed_source_objects=prov['removed_source_records'],added_objects=prov['added_records'],all156_full_footprint_records_exact=True,all558_full_pad_records_exact=True,all_existing_vias_exact=True,no_peer_proposal_adopted=True,all28_support_groups_restored=True,ADC_capacitor_branch_mm=elec['topology']['capacitor_branch_mm'],ADC_capacitor_to_U1_mm=elec['topology']['capacitor_to_U1_pad_path_mm'],ADC_ground_lead_mm=elec['topology']['new_ground_lead_mm'],remaining_access='remaining-access.json',reference_projection='new-route-reference-review.json',source48_inherited_ADC_width_gap_mm2=ref['source_ADC_existing_gap_total_mm2'],peer_reservations=['Joint flash native-stage48 additions','Seven servo48 completion-search-inner-negative proposal routes','PORT_B_RX via 17.93,10.79','RPM future via 15.10,9.59'],peer_reservations_are_planning_constraints_only=True,numerical_power_VCAP_applicable=False,ADC_functional_qualification=False,owner_adoption_claimed=False))
(D/'README.md').write_text('# PORT_A MCU native candidate\n\nComplete source48 reconstruction closes PORT_A_TX_MCU and restores PORT_A_RX_MCU and ADC_BUS, leaving 29 native opens and zero geometric errors or warnings. Nineteen tracks and two ordinary tented vias replace six source tracks. All 156 complete footprint records, 558 pad records and existing vias are exact.\n\nTX is 8.370079 mm; RX is 10.988722 mm including an 8.872218 mm In2 trunk. ADC capacitor branch is 4.448361 mm; C31-to-U1 is 6.963362 mm and the unchanged ground lead is 1.379246 mm. All new endpoints have finite pad, junction or annular entry. All 28 support graphs and both BARO trees remain complete.\n\nEvery changed/new track has complete saved-plane centerline and width projection outside its explicit own-via windows. Two prior ADC width gaps totaling 0.0000608648125 mm² remain exactly unchanged. The 16 prior critical nets remain complete and critical/BARO reference numeric deltas are exactly zero. No AC return, ADC functional, numerical power, manufacturing or flight qualification is claimed.\n\nThe final access report screens all 17 originally unresolved MCU pads and preserves the existing RPM portal. PORT_A external protected routes remain unfinished. This board contains no peer proposal geometry and awaits independent owner review; it is not adopted.\n')
handoff=dict(schema='f722-native-route-handoff/v1',status='frozen_native_verified_29_open_complete_PORT_A_MCU_geometric_WIP_pending_owner_review',board_sha256=h,integration_source_sha256=old,drc=dict(unconnected=29,errors=0,warnings=0,strict_schematic_parity=0,ERC_violations=0),pose_reference=str((D/'poses-native.json').relative_to(R)),declared_footprint_transforms='declared-footprint-transforms.json',coordinated=True,allowed_changed_nets=['PORT_A_TX_MCU','PORT_A_RX_MCU','ADC_BUS'],all156_full_footprints_exact=True,all558_full_pads_exact=True,all_existing_vias_exact=True,removed_source_objects=len(prov['removed_source_records']),added_native_objects=len(prov['added_records']),new_signal_vias=len(prov['vias']),completed_net='PORT_A_TX_MCU',restored_complete_nets=['PORT_A_RX_MCU','ADC_BUS'],entry_support_audit='entry-support-audit.json',adjacent_remaining_access='remaining-access.json',reserved_RPM_portal_mm=[15.1,9.59],raw_critical_object_geometry_identical=True,critical_reference_deltas_exactly_zero=True,reference_window_classification='reference-region-review/reference-classification.json',reference_window_classification_sha256=sha(region/'reference-classification.json'),missing_centerline_geometries_exactly_equal=True,actual_hole_predicate_disagreements=0,new_route_reference_review='new-route-reference-review.json',ADC_electrical_review='adc-electrical-screen.json',both_BARO_clean_complete_trees=True,I2C_electrical_status='NOT_QUALIFIED',numerical_power_VCAP_applicable=False,ADC_functional_qualification=False,owner_adoption_pending=True,direct_engine_output=False,fresh_router_zero_replay_performed=False)
handoff['files']={str(q.relative_to(D)):sha(q)for q in sorted(D.rglob('*'))if q.is_file()and q.name!='route-handoff.json'};write(D/'route-handoff.json',handoff);print(json.dumps(dict(board_sha256=h,files=len(handoff['files']),remaining=29,status=handoff['status'])))
