"""Seal the complete 13-open geometric checkpoint, with electrical limits explicit."""
import pathlib,json,hashlib,shutil,datetime
H=pathlib.Path(__file__).resolve().parent;R=H.parents[1];D=H/'small-candidate01';S=R/'candidate54'
read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();write=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n')
h=sha(D/'f722-heli.kicad_pcb');sh=sha(S/'f722-heli.kicad_pcb');assert h=='14dea1df09ea9d800bf66a6d74eb5f0dac33a8705161e9ed1a02f2e11f3b58b8'
s=read(D/'owner-summary.json');assert s['board_sha256']==h and s['drc']==s['drc-all']==dict(unconnected=13,errors=0,warnings=0)
for k in ['process','mechanical','parity','firmware']:assert s[k]['passed']and s[k]['board_sha256']==h
assert s['critical']['connected_nets']==16 and not s['critical']['faults']and not s['critical']['missing_ground_returns']
assert not read(D/'owner-drc-parity.json')['schematic_parity'];assert not any(x.get('violations')for x in read(D/'owner-erc.json').get('sheets',[]))
for f in ['entry-support-audit.json','power-audit.json','endpoint-audit.json','native-coordinated-integration.json','stock-spi-binding.json']:
 q=read(D/f);assert q['passed']and q['board_sha256']==h
p=read(D/'construction-provenance.json');audit=read(D/'entry-support-audit.json');assert len(p['removed_source_records'])==75 and len(p['added_records'])==117 and len(p['changed_pad_records'])==2 and len(p['changed_footprint_records'])==1
assert audit['new_track_endpoints_checked']==208 and len(audit['nets'])==28 and len(audit['signal_groups'])==7
c=read(D/'protection-actual-io.json');b=read(S/'protection-actual-io.json');passed=lambda x:{r['id']for r in x['checks']if r['complete_clamp_first_path_passes']};assert c['passed']==b['passed']==20 and c['total']==22 and passed(c)==passed(b)
ref=read(D/'reference-comparison54.json');assert ref['critical_object_geometry_identical']
project=read(D/'project-input-preservation.json');assert all(sha(D/x['path'])==x['sha256']==sha(S/x['path'])for x in project['files'])
nets=sorted({o['net']for o in p['removed_source_records']+p['added_records']}|{x['before']['net']for x in p['changed_pad_records']})
write(D/'coordinated-change-receipt.json',dict(schema='f722-small-GREEN-complete-native-reconstruction54/v1',source_board_sha256=sh,board_sha256=h,changed_nets=nets,removed_source_objects=p['removed_source_records'],added_objects=p['added_records'],changed_pad_records=p['changed_pad_records'],footprint_transforms='declared-footprint-transforms.json',all_other155_full_footprints_exact=True,all_other_source_objects_exact_except_runtime_net_code=True,all28_support_groups_restored=True,complete_GREEN_and_all_donors=True,raw_constructor_pending_flags_superseded_by_these_native_gates=True,numerical_power_VCAP_qualified=False,signal_quality_qualified=False,reference_AC_qualified=False,owner_adoption_claimed=False))
ledger=read(D/'native-length-ledger.json')
limits=['Geometric prototype checkpoint; owner adoption pending.','Fresh numerical power/VCAP and source-bound signal/analog/ESD review remain pending.','Retained critical copper is exact, but the complete raw refill-reference delta is nonzero; all86-net owner return review and classification remain pending.','GREEN PC14 total load below30pF remains unproven. Current2.2k resistors retained; the original66.981610mm calculation must be updated to this71.875650mm native witness.','A RX shifted via has0.131mm copper gap against0.127mm rule:4micrometers nominal CAD surplus, not a manufacturing robustness claim.','MID R44 rotates180degrees in place with its own new local ground tie; divider values and all other component identities/poses are retained.','DSM full native drawn copper is139.907072mm. Added copper134.658347mm is a different quantity; actual R38-to-U1.43 centerline path is136.672265mm. Receive and startup-bind loading/timing remain explicitly unqualified.']
write(D/'checkpoint-limits.json',dict(board_sha256=h,limits=limits,raw_critical_reference_deltas=ref['net_numeric_deltas_after_minus_before'],native_length_ledger='native-length-ledger.json'))
(D/'README.md').write_text('''# GREEN native checkpoint from accepted54

The board has13 opens, zero native errors and zero warnings. GREEN is complete, and all reconstructed DSM, ADC, flash support and A RX functions are restored. Remaining gaps are PORT_C5, BOOT2, RED1 and flash5. No C bank expansion or rotated flash cell is imported.

The exact transaction removes75 source copper objects and adds104 tracks and13 ordinary tented vias. R44 alone rotates180degrees at F(25.8,16.0); both actual net identities and its16.0k/0.1% value remain. Its new .25mm ground lead reaches an exclusive new tie at(25.08,15.78), with positive contacts to both saved ground planes. All other155 complete footprints and unrelated source copper remain exact.

Native DRC, parity, ERC, firmware, mechanical and process checks pass. All16 critical connectivity groups,208 finite new endpoints,28 supply/ground groups, seven changed signal groups, and all20 previously passing actual I/O cuts are preserved. Read entry-support-audit.json, native-coordinated-integration.json and the declared transform for the source-bound evidence.

Read checkpoint-limits.json before using this board. Critical copper is unchanged, but raw refill-reference deltas are nonzero and preserved. Ordinary as well as critical return changes require owner review. PC14 loading, DSM receive/startup behavior, analog/filter changes, transient/ESD behavior and fresh numerical power/VCAP remain unqualified. This is a sealed geometric checkpoint for review, not a release-ready board.
''')
for f in ['construct_small_GREEN_native54.py','audit_small_GREEN_native54.py','extra_small_GREEN_native54.py','measure_small_GREEN_native54.py','seal_small_GREEN_native54.py','export_small_GREEN_complete54.py']:
 shutil.copy2(H/f,D/(pathlib.Path(f).stem+'.used.py'))
shutil.copy2(R/'tests/servo48/validate_checkpoint.py',D/'validate_checkpoint.used.py')
ties=read(D/'reference-snapshot/critical-reference.json')['GND_ties']
hand=dict(schema='f722-native-route-handoff/v1',status='sealed_native_13_open_complete_GREEN_geometric_checkpoint_pending_owner_review',sealed_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),board_sha256=h,integration_source_sha256=sh,native_sha256=sha(D/'f722-heli.native.json'),drc=dict(unconnected=13,errors=0,warnings=0,strict_schematic_parity=0,ERC_violations=0),remaining_gap_accounting=dict(PORT_C=5,BOOT=2,RED=1,flash=5),pose_reference=str((D/'poses-native.json').relative_to(R)),declared_footprint_transforms='declared-footprint-transforms.json',coordinated=True,allowed_changed_nets=nets,all_other155_full_footprints_exact=True,removed_source_objects=75,added_native_objects=117,new_tracks=104,new_vias=13,finite_new_endpoints=208,support_groups_preserved=28,changed_signal_groups_complete=7,completed_net='LED_GREEN_K',actual_IO_cuts_passed=20,actual_IO_contracts=22,actual_IO_passes_exactly_preserved=True,critical_object_geometry_identical=True,critical_reference_deltas_exactly_zero=False,raw_critical_reference_deltas=ref['net_numeric_deltas_after_minus_before'],all_signal_reference_owner_review_pending=True,ground_ties_to_both_saved_planes=len(ties['accepted']),rejected_ground_ties=len(ties['rejected']),R44_return_exclusive_until_plane=True,native_length_ledger='native-length-ledger.json',limits_file='checkpoint-limits.json',signal_quality_qualified=False,reference_AC_qualified=False,protection_transient_qualified=False,numerical_power_VCAP_qualified=False,owner_adoption_pending=True)
hand['files']={str(f.relative_to(D)):sha(f)for f in sorted(D.rglob('*'))if f.is_file()and f.name!='route-handoff.json'};write(D/'route-handoff.json',hand);assert all(sha(D/k)==v for k,v in hand['files'].items());print(json.dumps(dict(board_sha256=h,handoff_sha256=sha(D/'route-handoff.json'),files=len(hand['files']),status=hand['status'])))
