import pathlib,json,hashlib,shutil
H=pathlib.Path(__file__).resolve().parent;R=H.parents[2];D=H/'candidate03';S=R/'ordinary-routing/candidate49'
read=lambda p:json.loads(pathlib.Path(p).read_text());sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();write=lambda p,v:pathlib.Path(p).write_text(json.dumps(v,indent=2)+'\n')
h=sha(D/'f722-heli.kicad_pcb');old=sha(S/'f722-heli.kicad_pcb');s=read(D/'owner-summary.json');assert h==s['board_sha256']and s['drc']==s['drc-all']==dict(unconnected=27,errors=0,warnings=0)
for k in ['process','mechanical','parity','firmware']:assert s[k]['passed']and s[k]['board_sha256']==h
assert not read(D/'owner-drc-parity.json')['schematic_parity'];assert not s['critical']['faults']and s['critical']['connected_nets']==16
erc=read(D/'owner-erc.json');assert not any(sh.get('violations')for sh in erc.get('sheets',[]))
for name in ['entry-support-audit.json','power-audit.json','native-coordinated-integration.json','stock-spi-binding.json']:
 q=read(D/name);assert q['passed']and q['board_sha256']==h
cut=read(D/'protection-actual-io.json');base=read(S/'protection-actual-io.json');assert cut['passed']==14 and cut['total']==22
passed=lambda d:{r['id']for r in d['checks']if r['complete_clamp_first_path_passes']};assert passed(base)<passed(cut)and passed(cut)-passed(base)=={'published-08'}
comp=read(D/'reference-comparison49.json');assert comp['critical_object_geometry_identical']and all(all(v==0 for v in row.values())for row in comp['net_numeric_deltas_after_minus_before'].values())
classify=read(H/'reference-classification.json');assert classify['source_binding_verified']and classify['before_board_sha256']==old and classify['after_board_sha256']==h and classify['missing_centerline_geometries_exactly_equal']and classify['exact_containment_predicate_disagreement_count']==0
reg=D/'reference-region-review';reg.mkdir(exist_ok=True)
for name in ['reference-classification.json','reference-classification.log','classify_reference_delta.py']:shutil.copy2(H/name,reg/name)
si=D/'conditional-signal-review';si.mkdir(exist_ok=True)
for name in ['TAIL-electrical-review.md','electrical-evidence.json','fetched-source-index.json','tail-path-comparison.json','measure_tail_paths.py','selected-pb3-speed00-model.txt','stm32f7x2_lqfp64.ibs','Readme.txt']:shutil.copy2(H/'signal-review'/name,si/name)
shutil.copytree(H/'signal-review/firmware',si/'firmware',dirs_exist_ok=True)
ev=read(si/'electrical-evidence.json');assert ev['board_sha256']==h and ev['assessment']['geometry_checkpoint_recommended_conditionally']and not ev['assessment']['electrical_release_qualified']
for name in ['construct_complete49_v3.py','audit_complete.py','extra_gates.py','audit_signal_details.py','export_tail_reference.py','check_tail_reference.py','seal_complete.py']:shutil.copy2(H/name,D/(pathlib.Path(name).stem+'.used.py'))
write(D/'declared-footprint-transforms.json',{'schema':'f722-declared-footprint-transforms/v1','source_board_sha256':old,'board_sha256':h,'declared':[],'all156_full_footprints_exact':True})
prov=read(D/'construction-provenance.json');audit=read(D/'entry-support-audit.json');geo=read(D/'signal-geometry-details.json')
write(D/'coordinated-change-receipt.json',dict(schema='f722-TAIL-complete-native-reconstruction/v1',source_board_sha256=old,board_sha256=h,changed_nets=['TAIL_MCU','TAIL_EXT','SERVO3_MCU','RPM_LV','ADC_DIV_MID','+3V3_CORE'],removed_source_objects=prov['removed_source_records'],added_objects=prov['added_records'],all156_full_footprint_records_exact=True,all558_full_pad_records_exact=True,all_existing_vias_exact=True,all28_support_groups_restored=True,ADC_BUS_capacitor_branch_objects_exact=True,completed_SERVO2_objects_exact=True,completed_SERVO3_tree_restored=True,no_peer_proposal_adopted=True,peer_reservations=['Joint flash native-stage48 added objects and R4 changed pads','PORT_A candidate01 already adopted as source49','PORT_B shared-path-summary and RX resistor stub'],reference_residuals_retained=True,conditional_signal_review='conditional-signal-review/TAIL-electrical-review.md',numerical_power_VCAP_applicable=False,signal_quality_qualified=False,owner_adoption_claimed=False))
(D/'README.md').write_text('# Complete TAIL native candidate03\n\nSource49 reconstruction closes the actual R23.2–U12.6–U1.55 protected tree, reducing29 opens to27 with zero native errors/warnings. All156 footprint poses and558 pad records are unchanged. All28 support partitions and completed SERVO2/3, ADC, RPM and PORT_A paths are restored.\n\nThe MCU-to-clamp path is81.063747mm, with4 signal vias; clamp-to-R23 is4.6125mm. CORE has one additional via and an8.867409mm replacement branch at0.20mm. All116 new track endpoints and all5 ordinary tented0.45/0.20mm vias pass finite native entry checks.\n\nTAIL actual-pad cut passes with0.371503mm gap;14/22 actual I/O contracts now pass, preserving every prior pass. Critical/BARO copper and missing-reference geometries remain exact49. TAIL has2.823919mm missing centerline in own-via windows and0.000224846616mm² width outside those windows, preserved and classified in signal-geometry-details.json.\n\nSee conditional-signal-review/TAIL-electrical-review.md for pinned LOW GPIO, exact ST IBIS model, component loading, historical topology and limits. This is a geometric prototype checkpoint pending owner review. Waveform, ESD-transient, AC-return and loaded-power qualification remain open; the source43 numerical power result does not apply. Earlier candidate01/02 courtyard failures are preserved separately.\n')
handoff=dict(schema='f722-native-route-handoff/v1',status='sealed_native_27_open_complete_TAIL_geometric_prototype_pending_owner_review',board_sha256=h,integration_source_sha256=old,drc=dict(unconnected=27,errors=0,warnings=0,strict_schematic_parity=0,ERC_violations=0),pose_reference=str((D/'poses-native.json').relative_to(R)),declared_footprint_transforms='declared-footprint-transforms.json',coordinated=True,allowed_changed_nets=['TAIL_MCU','TAIL_EXT','SERVO3_MCU','RPM_LV','ADC_DIV_MID','+3V3_CORE'],all156_full_footprints_exact=True,all558_full_pads_exact=True,all_existing_vias_exact=True,removed_source_objects=len(prov['removed_source_records']),added_native_objects=len(prov['added_records']),new_signal_vias=4,new_CORE_vias=1,completed_net='TAIL_MCU',restored_complete_nets=['TAIL_EXT','SERVO3_MCU','RPM_LV','ADC_DIV_MID','+3V3_CORE'],entry_support_audit='entry-support-audit.json',raw_critical_object_geometry_identical=True,critical_reference_deltas_exactly_zero=True,reference_window_classification='reference-region-review/reference-classification.json',missing_centerline_geometries_exactly_equal=True,actual_hole_predicate_disagreements=0,TAIL_reference='tail-reference/reference-review.json',TAIL_reference_residuals='signal-geometry-details.json',TAIL_total_track_length_mm=85.67624733962451,TAIL_MCU_to_clamp_mm=81.06374733962451,conditional_signal_review='conditional-signal-review/TAIL-electrical-review.md',stock_GPIO_speed='LOW_OSPEEDR00',conditional_model_evidence_only=True,signal_quality_qualified=False,protection_transient_qualified=False,reference_AC_qualified=False,both_BARO_clean_complete_trees=True,I2C_electrical_status='NOT_QUALIFIED',numerical_power_VCAP_applicable=False,owner_adoption_pending=True,direct_engine_output=False,fresh_router_zero_replay_performed=False)
handoff['files']={str(q.relative_to(D)):sha(q)for q in sorted(D.rglob('*'))if q.is_file()and q.name!='route-handoff.json'};write(D/'route-handoff.json',handoff);print(json.dumps(dict(board_sha256=h,files=len(handoff['files']),remaining=27,removed=len(prov['removed_source_records']),added=len(prov['added_records']),status=handoff['status'])))
