"""Prepare exact native I2C construction/entry/support wrappers, without adoption."""
from pathlib import Path
import collections,hashlib,json,shutil
R=Path(__file__).resolve().parent;S=R/'candidate41';D=R/'candidate43';RAW=R/'candidate42'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
read=lambda p:json.loads(Path(p).read_text())
def write(name,v):(D/name).write_text(json.dumps(v,indent=2)+'\n')
assert not(D/'route-handoff.json').exists()
source,current=read(S/'f722-heli.native.json'),read(D/'f722-heli.native.json')
h=sha(D/'f722-heli.kicad_pcb');assert h==current['board_sha256']=='1ee7174a578dffe4d5ef3ae8b39d8dc88f28b80395539263a65f23be234c21e6'
assert source['board_sha256']==sha(S/'f722-heli.kicad_pcb')=='539d9547eb8c4d5984481293ae10cee34355ee838dff11ab43b00cca270ceae2'
before={o['uuid']:o for o in source['objects']};after={o['uuid']:o for o in current['objects']}
removed=set(before)-set(after);added=set(after)-set(before);changed={u for u in before.keys()&after.keys()if before[u]!=after[u]}
assert len(removed)==7 and len(added)==41 and len(changed)==6
oldfp={o['uuid']:o for o in source['footprints']};newfp={o['uuid']:o for o in current['footprints']};changedfp={u for u in oldfp if oldfp[u]!=newfp[u]}
assert {oldfp[u]['ref']for u in changedfp}=={'R7','R8','C69'}
assert all(o['net']=='+3V3_CORE'for u,o in before.items()if u in removed)
a=read(D/'i2c-entry-support-audit.json');assert a['passed']and all(a['gates'].values())and all(c['rejected']for c in a['negative_controls'])
assert a['board_sha256']==h and a['source_board_sha256']==source['board_sha256']
assert read(D/'owner-summary.json')['drc']=={'unconnected':37,'errors':0,'warnings':0}
io=read(D/'protection-actual-io.json');assert io['board_sha256']==h and io['passed']==11 and io['total']==22
signals=read(D/'i2c-geometry-review.json');assert all(signals['nets'][net]['topology']['clean_complete_tree']for net in ['BARO_SCL','BARO_SDA'])
assert signals['I2C_final_status']=='NOT_QUALIFIED'
oldmap=read(S/'f722-heli.logical-route-map.json')['logical_route_map'];newmap=read(D/'f722-heli.logical-route-map.json')['logical_route_map'];assert all(newmap.get(u)==owner for u,owner in oldmap.items()if u not in removed)
project=read(S/'project-input-preservation.json');assert len(project['files'])==60
for row in project['files']:assert sha(S/row['path'])==sha(D/row['path'])==row['sha256']
write('project-input-preservation.json',{'source_board_sha256':source['board_sha256'],'board_sha256':h,'all_listed_non_board_project_inputs_byte_identical':True,'files':project['files']})
binding={'board_sha256':h,'source_board_sha256':source['board_sha256'],'audit':'i2c-entry-support-audit.json','audit_sha256':sha(D/'i2c-entry-support-audit.json')}
write('endpoint-audit.json',{'schema':'f722-I2C-complete-endpoint-binding/v1','passed':True,**binding,'scope':'Finite pad, annular and full-width junction geometry; two false direct R8 predicates remain explicit and use named finite full-width corridors.','direct_pad_entry_failures_preserved':a['direct_pad_entry_failures_preserved'],'strict_pad_entries_all_pass':False,'full_width_corridor_review':'explicit_R8_retained_junction','new_track_endpoints_checked':len(a['classification']),'pad_entry_predicates':len(a['strict_pad_entries']),'full_width_track_joins':len(a['full_width_track_joins']),'annular_entries':len(a['finite_annular_entries']),'retained_track_interior_entries':len(a['retained_track_interior_entries']),'negative_controls':len(a['negative_controls']),'manufacturing_margin_claimed':False})
write('power-audit.json',{'schema':'f722-I2C-complete-support-binding/v1','passed':True,**binding,'scope':'Copper-only continuity of all28 source support groups; no loaded numerical power, VCAP, rail budget, decoupling or transient pass.','nets':a['nets'],'all_28_support_groups_preserved':True,'native_sha256':sha(D/'f722-heli.native.json'),'numerical_power_VCAP_applicable':False})
t={'schema':'f722-explicit-coordinated-native-transaction/v1','passed':True,'source_board_sha256':source['board_sha256'],'board_sha256':h,'source_native_sha256':sha(S/'f722-heli.native.json'),'candidate_native_sha256':sha(D/'f722-heli.native.json'),'source_map_sha256':sha(S/'f722-heli.logical-route-map.json'),'candidate_map_sha256':sha(D/'f722-heli.logical-route-map.json'),'removed_source_records':[before[u]for u in sorted(removed)],'added_candidate_records':[after[u]for u in sorted(added)],'changed_pad_records':[{'before':before[u],'after':after[u]}for u in sorted(changed)],'changed_footprint_records':[{'before':oldfp[u],'after':newfp[u]}for u in sorted(changedfp)],'removed_logical_owners':{u:oldmap.get(u)for u in sorted(removed)},'added_logical_owners':{u:newmap.get(u)for u in sorted(added)},'all_other_source_objects_exact':len(before)-len(removed)-len(changed),'all_retained_logical_owners_exact':True,'all_poses_pads_outline_layers_exact':False,'all_undeclared_poses_pads_outline_layers_exact':True,'declared_pad_pose_changes':6,'declared_footprint_pose_changes':3,'removed_counts':dict(collections.Counter(before[u]['kind']+':'+before[u]['net']for u in removed)),'added_counts':dict(collections.Counter(after[u]['kind']+':'+after[u]['net']for u in added)),'changed_power_feed':'Seven obsolete CORE objects removed, R7 pullup feed and R8 extension added; R7/R8/C69 poses explicitly changed. All28 source copper pad partitions preserved; numerical power stale.','ground_native_objects_exact':True,'restored_PORT_C_source41_objects_exact':True,'complete_rewritten_entry_receipt':'i2c-entry-support-audit.json','complete_rewritten_entry_receipt_sha256':sha(D/'i2c-entry-support-audit.json'),'support_receipt':'power-audit.json','support_receipt_sha256':sha(D/'power-audit.json'),'actual_io_receipt':'protection-actual-io.json','actual_io_receipt_sha256':sha(D/'protection-actual-io.json'),'actual_io_passed':11,'actual_io_total':22,'actual_io_all_pass':False,'construction_provenance_sha256':sha(D/'construction-provenance.json'),'engine_success_claimed':False,'numerical_power_VCAP_applicable':False,'adoption_claimed':False}
write('coordinated-change-receipt.json',t)
write('f722-heli.import.json',{'schema':'f722-explicit-coordinated-native-construction-receipt/v1','passed':True,'source_sha256':source['board_sha256'],'output_sha256':h,'construction_source_sha256':sha(RAW/'f722-heli.kicad_pcb'),'construction_kind':'Complete native I2C routing and explicit support/pose revision on accepted41, then five-track SDA correction from isolated42. PORT_C source41 geometry restored exactly.','direct_engine_output':False,'engine_routing_succeeded':False,'engine_partial_geometry_adopted':False,'ses_engine_native_geometry_equal':False,'session_artifact':None,'coordinated_change_receipt':'coordinated-change-receipt.json','coordinated_change_receipt_sha256':sha(D/'coordinated-change-receipt.json'),'construction_provenance':'construction-provenance.json','construction_provenance_sha256':sha(D/'construction-provenance.json'),'logical_route_map_artifact':'f722-heli.logical-route-map.json','logical_route_map_sha256':sha(D/'f722-heli.logical-route-map.json'),'undeclared_native_changes':0,'footprints_preserved':153,'declared_footprint_pose_changes':3,'reference_plane_refill_performed':True,'fresh_model_zero_control_performed':False,'numerical_power_VCAP_applicable':False})
write('power-revalidation-required.json',{'board_sha256':h,'numerical_power_and_VCAP_applicability':False,'last_fully_bound_numerical_candidate':'candidate24','last_fully_bound_numerical_receipt':'static-power-validation/candidate24-power-result-applicability.json','last_fully_bound_numerical_receipt_sha256':'8373a599fe81a58571422fc4a1f4fe3afb65acad2fd7b3528eef43d575edce11','reason':'Intentional CORE route removal/additions, R7/R8/C69 pose revisions and changed signal drilling/saved GND. No inherited loaded power/VCAP or decoupling pass.','geometric_support_continuity_passed':True,'transient_qualification_claimed':False})
write('nominal-clearance-reserves.json',{'board_sha256':h,'scope':'Nominal CAD clearances, not fabrication or assembly tolerance allowances.','source_local_screen_sha256':sha(RAW/'small-cap-portal-screen.json'),'poses_and_vias_exact_to_source42':True,'rules':[{'objects':['SCL_sensor_via_ecee0449-3181-5049-8e1a-0df4c3ce26e1','C69.2'],'rule':'different-net copper-to-copper clearance','required_mm':.127,'nominal_actual_mm':.1285,'nominal_excess_mm':.0015},{'objects':['C69.1','GND_via_ae56f326-719f-4298-954b-54bb06b5a21e'],'rule':'different-net copper-to-copper clearance','required_mm':.127,'nominal_actual_mm':.1277866640068527,'nominal_excess_mm':.0007866640068527053}],'mask_and_drill_checks_separate':'owner-process.json and owner-drc-all.json','manufacturing_tolerance_allowance_claimed':False,'final_source_specific_manufacturing_assembly_review_pending':True})
copies={R/'construct_i2c_complete42.py':'construct_i2c_complete42.used.py',R/'audit_i2c43_entries_support.py':'audit_i2c43_entries_support.used.py',RAW/'i2c-geometry-review.json':'isolated42-topology-refusal.json',RAW/'construction-provenance.json':'isolated42-construction-provenance.json',RAW/'i2c-entry-support-audit.initial-direct-refusal.json':'isolated42-direct-entry-refusal.json',RAW/'i2c-entry-support-audit.section-only-control-refusal.json':'isolated42-section-only-control-refusal.json',RAW/'small-cap-portal-screen.json':'selected-portal-pose-screen.json',R.parent/'integrated-routing/declared-transforms41-to43.json':'declared-transforms41-to43.json'}
for src,name in copies.items():shutil.copy2(src,D/name)
shutil.copy2(__file__,D/'prepare_candidate43_evidence.used.py')
print(json.dumps({'board_sha256':h,'source41_removed':len(removed),'added':len(added),'retained_exact':t['all_other_source_objects_exact'],'I2C_electrical_status':signals['I2C_final_status']}))
