"""Seal additive RPM14 with raw return limitation and conditional loading review."""
from pathlib import Path
import json,hashlib,shutil
H=Path(__file__).resolve().parent;R=H.parents[2];D=H/'candidate01';S=H.parent/'servo48/candidate04'
read=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();write=lambda name,x:(D/name).write_text(json.dumps(x,indent=2)+'\n')
h=sha(D/'f722-heli.kicad_pcb');old=sha(S/'f722-heli.kicad_pcb');assert h=='73dbae05954b8edec4143d91248bf38c40537f83e8f5f3fed51744105169d6c7';assert old=='755545e8198e9a3649c0e07533c23e67010d91ab6a8b09556d7463e064ac89eb'
source_handoff=read(S/'route-handoff.json');assert source_handoff['board_sha256']==old;assert all(sha(S/p)==z for p,z in source_handoff['files'].items())
x=read(D/'owner-summary.json');assert x['board_sha256']==h and x['drc']==x['drc-all']==dict(unconnected=14,errors=0,warnings=0)
for k in ['process','mechanical','parity','firmware']:assert x[k]['passed']and x[k]['board_sha256']==h
assert not x['critical']['faults']and x['critical']['connected_nets']==16 and not x['critical']['missing_ground_returns'];assert not read(D/'owner-drc-parity.json')['schematic_parity'];assert all(not s['violations']for s in read(D/'owner-erc.json')['sheets'])
for f in ['native-additive-integration.json','entry-support-audit.json','power-audit.json','actual-protection-superset.json','stock-spi-binding.json']:
 a=read(D/f);assert a['passed']and a['board_sha256']==h
prov=read(D/'construction-provenance.json');assert prov['source_board_sha256']==old and prov['board_sha256']==h
assert len(prov['added_records'])==24 and len(prov['vias'])==5 and len(prov['routes'])==6
for k in ['removed_source_records','changed_pad_records','changed_track_records','changed_footprint_records']:assert not prov[k]
for k in ['all_source_native_objects_exact_except_runtime_net_code','all156_full_footprint_records_exact','all558_full_pad_records_exact','all_source_vias_exact']:assert prov[k]
assert not prov['private_flash_reservations_added_as_copper'];assert {o['net']for o in prov['added_records']}=={'RPM_MCU'}
assert sum(o['kind']=='track'for o in prov['added_records'])==19
assert read(D/'project-input-preservation.json')['all_listed_non_board_project_inputs_byte_identical']
audit=read(D/'entry-support-audit.json');assert audit['new_track_endpoints_checked']==38 and len(audit['nets'])==28 and all(r['rejected']for r in audit['negative_controls'])
c=read(D/'reference-comparison15.json');assert c['before_board_sha256']==old and c['after_board_sha256']==h and c['critical_object_geometry_identical']and not c['critical_object_differences'];assert all(v==0 for row in c['net_numeric_deltas_after_minus_before'].values()for v in row.values());assert all(v['lost_GND_overlap_with_trace_width_mm2']==0 for row in c['ground_fill_changes'].values()for v in row['critical_trace_proximity'].values())
br=read(S/'reference-snapshot/critical-reference.json');ar=read(D/'reference-snapshot/critical-reference.json');assert br['nets']==ar['nets']
write('critical-reference-preservation.json',dict(schema='f722-RPM-strict-critical-reference-preservation/v1',passed=True,board_sha256=h,source_board_sha256=old,comparison_sha256=sha(D/'reference-comparison15.json'),critical_objects_exact=True,reference_per_net_records_exact=True,numeric_deltas_exactly_zero=True,lost_GND_overlap_with_critical_trace_width_exactly_zero=True,ground_fill_changes=c['ground_fill_changes'],plane_equality_claimed=False,runtime_index_exception_used=False,contour_normalization_used=False))
ref=read(D/'new-route-reference-review.json');ctx=read(D/'conditional-signal-review/RPM-return-context.json');top=read(D/'conditional-signal-review/RPM-path-topology.json');load=read(D/'conditional-signal-review/RPM-loading-sensitivity.json')
for row in [ref,ctx,top,load]:assert row['board_sha256']==h and row['source_board_sha256']==old
assert ref['summary']['RPM_MCU']['outside_own_windows_centerline_mm']==0
assert ref['summary']['RPM_MCU']['outside_own_windows_width_mm2']==2.725130554532544e-05
assert not ref['all_new_tracks_reference_complete_outside_explicit_own_via_windows']
assert not ctx['normalization_or_tolerance_waiver_used']and len(ctx['outside_window_width_residuals'])==1 and load['electrical_status']=='NOT_QUALIFIED'
actual=read(D/'protection-actual-io.json');assert actual['passed']==20 and actual['total']==22;rpm=next(z for z in actual['checks']if z['net']=='RPM_MCU');assert rpm['complete_clamp_first_path_passes']and rpm['minimum_gap_measured_mm']>=.127
write('declared-footprint-transforms.json',dict(schema='f722-explicit-native-footprint-transforms/v1',board_sha256=h,source_board_sha256=old,transforms=[],unchanged_full_footprints=156,unchanged_full_pads=558,pose_sha256=sha(D/'poses-native.json')))
write('additive-change-receipt.json',dict(schema='f722-complete-RPM-additive-change/v1',board_sha256=h,source_board_sha256=old,source_handoff_sha256=sha(S/'route-handoff.json'),allowed_added_nets=['RPM_MCU'],completed_nets=['RPM_MCU'],removed_source_objects=0,changed_source_objects=0,new_tracks=19,new_vias=5,all_source_footprints_pads_and_existing_vias_exact=True,all38_new_endpoints_finitely_connected=True,all28_support_groups_preserved=True,actual_cut='R39.2 -> U13.6 -> U1.16',actual_outside_pad_gap_mm=rpm['minimum_gap_measured_mm'],all_prior_actual_protection_passes_preserved=True,actual_cases_passed=20,actual_cases_total=22,critical_reference='critical-reference-preservation.json',new_reference='new-route-reference-review.json',centerline_outside_own_windows_mm=0,width_outside_own_windows_mm2=ref['summary']['RPM_MCU']['outside_own_windows_width_mm2'],all_new_reference_complete_outside_own_windows=False,conditional_signal_review='conditional-signal-review/RPM-electrical-review.md',signal_quality_qualified=False,numerical_power_VCAP_applicable=False,owner_adoption_claimed=False))
write('power-revalidation-required.json',dict(board_sha256=h,source_board_sha256=old,numerical_power_and_VCAP_applicability=False,geometric_support_continuity_passed=True,all28_support_groups_preserved=True,all_source_support_copper_exact=True,reference_planes_refilled=True,new_ordinary_signal_vias=5,reason='Five new through-vias alter saved GND fill and antipads. Complete source support copper and critical reference are preserved, but prior numerical power/VCAP results remain historical. Fresh current-source power and VCAP analysis is required.',RPM_electrical_status='NOT_QUALIFIED',I2C_electrical_status='NOT_QUALIFIED',transient_qualification_claimed=False))
write('f722-heli.import.json',dict(schema='f722-explicit-additive-native-construction-receipt/v1',passed=True,source_sha256=old,output_sha256=h,construction_source_sha256=old,construction_kind='Explicit native additive construction of complete RPM_MCU downstream actual-clamp branch:19 tracks and5 ordinary vias; all source objects and156 footprints retained. Saved planes refilled.',direct_engine_output=False,engine_routing_succeeded=False,engine_partial_geometry_adopted=False,ses_engine_native_geometry_equal=False,session_artifact=None,additive_change_receipt='additive-change-receipt.json',additive_change_receipt_sha256=sha(D/'additive-change-receipt.json'),construction_provenance='construction-provenance.json',construction_provenance_sha256=sha(D/'construction-provenance.json'),logical_route_map_artifact='f722-heli.logical-route-map.json',logical_route_map_sha256=sha(D/'f722-heli.logical-route-map.json'),undeclared_native_changes=0,footprints_preserved=156,footprints_transformed=0,reference_plane_refill_performed=True,fresh_model_zero_control_performed=False,numerical_power_VCAP_applicable=False,owner_review=None))
scripts=['construct_native.py','refill_native.py','seal_native.py','extra_gates.py','audit_entries_support.py','reference_routes.py','review_rpm_context.py','preconstruction.py','routing_context.py','routing_context15.py','complete_layer_graph15.py','seal_complete.py']
for name in scripts:shutil.copy2(H/name,D/(Path(name).stem+'.used.py'))
for name in ['complete-layer-proposal.json','preconstruction-screen.json']:shutil.copy2(H/name,D/name)
tools=['integrated-routing/check_additive_integration.py','integrated-routing/verify_support_adoption.py','ordinary-routing/dsm40-audits/audit_dsm40_entries_return.py','ordinary-routing/dsm41-audits/audit_dsm41_entries_return.py','repo/f722-heli/layout-revision/signal-review/native/check_critical_reference.py','repo/f722-heli/layout-revision/signal-review/native/check_signal_geometry.py','repo/f722-heli/layout-revision/protection-review/tools/check_protection_paths.py']
write('receipt-source-bindings.json',dict(board_sha256=h,local_scripts={name:sha(H/name)for name in scripts},existing_helpers={p:sha(R/p)for p in tools},source_handoff=dict(path=str((S/'route-handoff.json').relative_to(R)),sha256=sha(S/'route-handoff.json'),files_verified=len(source_handoff['files'])),review_date_UTC='2026-10-10'))
(D/'README.md').write_text('''# Complete additive RPM native14

Board73dbae05…69d6c7, on sealed SERVO15 board755545e8…c89eb. Owner adoption remains separate.

The complete R39.2→U13.6→U1.16 tree passes actual pad-cut protection. This transaction adds19 tracks and5 ordinary0.45/0.20mm tented vias, removes nothing, and retains all156 full footprints/558 pads and every source track/via. Native normal/all-track/parity DRC14 opens,0 errors,0 warnings; ERC/parity/firmware/process/mechanical and all16 critical connections pass. All38 new endpoints have finite entry/join proof. All28 support groups and all19 source passing actual protection cases survive; actual cases20/22.

Critical native records and per-net reference records are exactly equal, numeric deltas0 and lost-GND overlap with critical widths0. Ground planes change after refill. RPM centerline projection is complete outside explicit own-via windows, but one real In3 width-edge residue0.0000272513mm² remains beside the merged RPM/SERVO3 via hole. Raw width coverage remains false; no contour normalization or tolerance waiver is used.

RPM_MCU inventory is59.446075mm, including57.886227mm added. The conditional review binds Q1/R36/R39, native path inventory, five vias, exact return ties, assumed loading and pulse/edge distinctions. Two same-net midsegment via-land contacts mean the endpoint walk is not a unique shortest physical path. Unknown external driver/cable and unextracted nonlinear loading prevent electrical qualification. RPM/I2C electrical and fresh numerical power/VCAP qualification remain pending. See conditional-signal-review/RPM-electrical-review.md.
''')
handoff=dict(schema='f722-native-route-handoff/v1',status='sealed_native_14_open_complete_RPM_additive_geometry_with_explicit_return_residue_pending_owner_review',board_sha256=h,integration_source_sha256=old,source_dir=str(S.relative_to(R)),source_handoff_sha256=sha(S/'route-handoff.json'),drc=dict(unconnected=14,errors=0,warnings=0,strict_schematic_parity=0,ERC_violations=0),pose_reference=str((D/'poses-native.json').relative_to(R)),pose_sha256=sha(D/'poses-native.json'),coordinated=False,additive=True,allowed_added_nets=['RPM_MCU'],all156_full_footprints_exact=True,all558_full_pads_exact=True,all_existing_source_objects_exact=True,removed_source_objects=0,added_native_objects=24,new_signal_vias=5,completed_net='RPM_MCU',entry_support_audit='entry-support-audit.json',all38_new_endpoints_finite=True,all28_support_groups_preserved=True,new_route_reference_review='new-route-reference-review.json',critical_reference_review='critical-reference-preservation.json',raw_critical_objects_exact=True,critical_per_net_reference_records_exact=True,critical_numeric_deltas_zero=True,lost_critical_width_overlap_zero=True,actual_cases_passed=20,actual_cases_total=22,actual_gap_mm=rpm['minimum_gap_measured_mm'],all_prior_actual_protection_passes_preserved=True,RPM_MCU_track_inventory_mm=top['net_inventory']['RPM_MCU']['total_track_length_mm'],RPM_new_track_inventory_mm=top['new_planar_length_mm'],new_centerline_gap_outside_own_windows_mm=0,new_width_gap_outside_own_windows_mm2=ref['summary']['RPM_MCU']['outside_own_windows_width_mm2'],new_width_projection_complete=False,remaining_MCU_access_fresh_census_performed=False,RPM_electrical_review='conditional-signal-review/RPM-electrical-review.md',RPM_electrical_status='NOT_QUALIFIED',I2C_electrical_status='NOT_QUALIFIED',numerical_power_VCAP_applicable=False,owner_adoption_pending=True,direct_engine_output=False,fresh_router_zero_replay_performed=False)
handoff['files']={str(p.relative_to(D)):sha(p)for p in sorted(D.rglob('*'))if p.is_file()and p.name!='route-handoff.json'};write('route-handoff.json',handoff);assert all(sha(D/p)==z for p,z in handoff['files'].items());assert sha(D/'f722-heli.kicad_pcb')==h
print(json.dumps(dict(board_sha256=h,source_board_sha256=old,source_handoff_sha256=sha(S/'route-handoff.json'),route_handoff_sha256=sha(D/'route-handoff.json'),files=len(handoff['files']),remaining=14,status=handoff['status'])))
