package app.freerouting.board;
import app.freerouting.Freerouting;import app.freerouting.settings.*;import app.freerouting.core.*;import app.freerouting.interactive.*;import app.freerouting.designforms.specctra.DsnFile;import app.freerouting.management.analytics.FRAnalytics;import com.google.gson.*;import java.nio.file.*;import java.util.*;
/** Synthetic in-memory peer mutation test; does not import or edit a native PCB. */
public final class NativePeerMutationControl {
 static void check(boolean p,String s){if(!p)throw new AssertionError(s);}
 static void checkPeer(NativePadContactArea a,Item expected,int id){var found=a.get_normal_contacts().stream().filter(i->i.get_id_no()==id).findFirst().orElse(null);check(found==expected,"Peer index must resolve current object identity");}
 public static void main(String[] args)throws Exception{
  Path dir=Path.of(args[0]);JsonObject m=JsonParser.parseString(Files.readString(dir.resolve("model.json"))).getAsJsonObject();Freerouting.globalSettings=new GlobalSettings();Freerouting.globalSettings.usageAndDiagnosticData.disableAnalytics=true;Freerouting.globalSettings.apiServerSettings.isEnabled=false;FRAnalytics.setEnabled(false);RoutingJob j=new RoutingJob();HeadlessBoardManager mgr=new HeadlessBoardManager(Locale.ENGLISH,j);check(mgr.loadFromSpecctraDsn(Files.newInputStream(dir.resolve("routing.dsn")),new BoardObserverAdaptor(),new ItemIdentificationNumberGenerator())==DsnFile.ReadResult.OK,"DSN");RoutingBoard b=mgr.get_routing_board();NativeGuardFactory.install(b,m);NativePadContactArea sample=(NativePadContactArea)b.get_items().stream().filter(i->i instanceof NativePadContactArea).findFirst().orElseThrow();int net=sample.get_net_no(0);NativePadContactArea a=new NativePadContactArea(sample.get_relative_area(),sample.get_layer(),net,new int[]{net},"synthetic-a","synthetic-a",false,"synthetic-peers",true,b),z=new NativePadContactArea(sample.get_relative_area(),sample.get_layer(),net,new int[]{net},"synthetic-z","synthetic-z",false,"synthetic-peers",true,b);b.insert_item(a);b.insert_item(z);List<NativePadContactArea> peers=Collections.unmodifiableList(Arrays.asList(a,z));a.setNativePeers(peers);z.setNativePeers(peers);int id=z.get_id_no();checkPeer(a,z,id);b.remove_item(z);checkPeer(a,null,id);NativePadContactArea replacement=(NativePadContactArea)z.copy(id);b.insert_item(replacement);checkPeer(a,replacement,id);b.generate_snapshot();b.remove_item(replacement);checkPeer(a,null,id);check(b.undo(new TreeSet<>()),"Undo should restore removed peer");NativePadContactArea currentA=(NativePadContactArea)b.get_item(a.get_id_no());checkPeer(currentA,b.get_item(id),id);RoutingBoard clone=b.deepCopy();check(clone!=null,"Clone");NativePadContactArea cloneA=(NativePadContactArea)clone.get_item(a.get_id_no());checkPeer(cloneA,clone.get_item(id),id);check(clone.get_item(id)!=b.get_item(id),"Clone must own independent peer instances");System.out.println("PASS: peer removal, same-ID replacement, undo restoration, cloned board-local identity; no route search or native edits.");
 }
}
