from pathlib import Path
import json,shutil,hashlib,datetime
R=Path(__file__).resolve().parents[1];N=R/'repo/f722-heli/layout-revision';C=N/'checks';S=R/'checkpoint12-owner-review';D=R/'ordinary-routing/candidate56';O=C/'checkpoint56-integration';h=hashlib.sha256((D/'f722-heli.kicad_pcb').read_bytes()).hexdigest()
def read(p):return json.loads(p.read_text())
def write(p,d):p.write_text(json.dumps(d,indent=2)+'\n')
for f in ['owner-adoption-assessment.json','global-retained-track-reference-delta.json','check_global_reference_delta.py','inspect_selected_reference.py','changed-net-reference-targets.json','comparison-13-to-12.json','owner-review-run.json']:
 shutil.copy2(S/f,O/f)
for f in ['entry-support-audit.json','power-audit-sealed-original.json','power-audit.json','owner-summary.json','support-report-adapter.json']:
 shutil.copy2(D/f,O/f)
shutil.copy2(S/'changed-net-reference/critical-reference.json',O/'changed-net-reference.json')
shutil.copytree(R/'ordinary-routing/tests/native13-access/electrical-review02',O/'conditional-signal-review',dirs_exist_ok=True)
shutil.copy2(R/'checkpoint12-R4-placement-reproduction/placement-reproduction.json',C/'placement12-reproduction.json')
s=read(C/'current-status.json');s['loaded_power_diagnostic']=s['loaded_power_diagnostic'].replace('Current13','Current12');s['current_numerical_power_status']=s['current_numerical_power_status'].replace('current13','current12');s['placement_recipe_current_evidence']='placement12-reproduction.json';s['placement_transform_current_evidence']='transform-placement12.json';s['placement_recipe_original_reproduction']='placement12-reproduction.json';s['i2c_routing']['source_board_sha256']=h
s['source13_reference_preservation']=s['reference_preservation'];s['reference_preservation']={'board_sha256':h,'receipt':'checkpoint56-integration/owner-adoption-assessment.json','critical_copper_and_numeric_projection_delta_zero':True,'retained_track_global_delta_receipt':'checkpoint56-integration/global-retained-track-reference-delta.json','changed_nets_receipt':'checkpoint56-integration/changed-net-reference.json','AC_or_impedance_qualification':False,'limits':'Eight inherited source13 actual-hole predicate ambiguities remain unresolved; tiny nonzero retained-track edge differences and a new CS width-edge wedge are preserved in raw evidence.'}
s['flash_CS_pullup_revision']={'board_sha256':h,'receipt':'checkpoint56-integration/conditional-signal-review/README.md','R4_pose':[40.55,19,180,'B.Cu'],'U3_to_R4_complete':True,'actual_MCU_connection_complete':False,'CS_existing_planar_mm':13.999707,'new_CORE_spur_mm':4.335,'restored_CORE_junction_bridge_mm':1.835756,'electrical_qualified':False}
write(C/'current-status.json',s)
p=N/'README.md';t=p.read_text().replace('checks/checkpoint13-owner-review.json','checks/checkpoint12-owner-review.json');anchor='Checkpoint55 completes';text='Checkpoint56 completes the flash CS pull-up branch by moving R4 to the rear USB-side edge, while preserving all other 155 footprints and all original track/via objects. The old R4 CORE junction now has an explicit full-width bridge, and its new supply spur lands at C15.1. All 156 poses and 558 pad records reproduce. The actual MCU CS connection remains open. The [electrical review](checks/checkpoint56-integration/conditional-signal-review/README.md) records startup, active VERY_HIGH GPIO edges and incomplete full-tree timing limits. Critical reference metrics are unchanged; the [owner assessment](checks/checkpoint56-integration/owner-adoption-assessment.json) retains small ordinary-track projection differences and a CS width-edge wedge. Current numerical power/VCAP, decoupling and AC checks remain pending.\n\nThe preceding '
assert anchor in t;t=t.replace(anchor,text+anchor,1);p.write_text(t)
p=R/'ACTIVE-STATE.json';d=read(p);d['updated_utc']=datetime.datetime.now(datetime.timezone.utc).isoformat();d['owner_current_review']={'source':'ordinary-routing/candidate56','board_sha256':h,'assessment':'checkpoint12-owner-review/owner-adoption-assessment.json','numerical_power_current':False};write(p,d)
with (R/'OWNER-RESUME.md').open('a') as f:f.write('\n2026-10-10 07:31 UTC: Accepted candidate56 at12 opens/0 errors/0 warnings, PCB '+h+'. Only R4 moves; 156 poses/558 pads reproduce; all original track/via objects retained, 13 tracks/2 vias added. Owner evidence checkpoint12-owner-review and conditional review preserve current power/AC limitations. Remote13 verified PR16/638a53d2; prepare compact incremental12.\n')
print('Canonical12 compact evidence refreshed.')
