#!/usr/bin/python3
"""Join independently completed CAD/attachment reports and fresh XML semantics."""
import copy,hashlib,json,xml.etree.ElementTree as ET
from pathlib import Path
D=Path(__file__).resolve().parent;F=D/'final-fafa9c3f';P=Path('/workspace/shared/storm32-redesign/controller-r3s-p6');A=Path('/workspace/shared/storm32-redesign/controller-r3s-p5');PAD=Path('/workspace/shared/storm32-redesign/research/controller-r3s-p6-pad-attachment-audit');H='fafa9c3f0efc570ab70c69d45ffb7bfc7e548dae520a391ed167540ffccf6c6a';sha=lambda q:hashlib.sha256(q.read_bytes()).hexdigest();read=lambda q:json.loads(q.read_text());errors=[]
def check(ok,msg):
 if not ok:errors.append(msg)
full=read(F/'native-gate-summary.json');geo=read(F/'revision-geometry.json');top=read(F/'topology.json');replay=read(F/'route-replay.json');joins=read(D/'join-throats-fafa9c3f.json');via=read(D/'all-via-attachments-fafa9c3f.json');plane=read(D/'ground-plane-attachments-fafa9c3f.json');pad=read(PAD/'final-fafa9c3f-closure.json');pad_integration=read(PAD/'final-fafa9c3f-integration-proof.json');quality=read(F/'route-quality/route-quality-comparison.json');negative=read(D/'join-throats-p5-constructive.json')
for name,doc in [('native',full),('geometry',geo),('topology',top),('replay',replay),('joins',joins),('via',via),('plane',plane),('pads',pad)]:
 check(doc.get('candidate_sha256')==H,name+' source hash mismatch');check(not doc.get('errors'),name+' contains errors')
check(full['status'].startswith('PASS') and full['source_stable'],'Full numerical gate did not pass with stable source');check(not any(full['native_counts'].values()),'Native ERC/DRC/opens/parity nonzero');check(not joins['narrow_local_join_flags'],'Unresolved local copper joins');check(not via['new_or_worsened_shallow_groups'] and not via['inherited_or_improved_shallow_groups'],'Unresolved signal/via contact quality');check(not via['disappeared_via_layer_contacts'],'Previously routed via-layer attachment disappeared');check(pad['counts']['failed_groups']==0 and pad['unresolved_functional_nominal_advisory_count']==0 and not pad['new_or_worse_nominal_cases'],'Unresolved functional pad-entry geometry');check(pad['all431_pad_inventory_unchanged'],'Pad inventory changed');check(pad_integration['main_sha256']==pad_integration['tested_sha256']==H and pad_integration['final_closure_report_sha256']==sha(PAD/'final-fafa9c3f-closure.json'),'Pad independent integration proof differs');check(plane['verified_reference_plane_terminal_attachments']==303,'Incomplete solid-reference-plane terminal coverage')
negative_host=[q for q in negative['narrow_local_join_flags'] if q['net']=='HOST_TX_RAW'];check(len(negative_host)==2 and all(abs(q['pair_circle_lens_neck_mm']-.05)<1e-10 for q in negative_host),'Known HOST_TX_RAW negative control was not detected');check(negative['audit_script_sha256']==joins['audit_script_sha256']==sha(D/'audit_copper_join_throats.py'),'Negative/final copper-join methods differ')
clone=F/'cli-snapshot';oldxml=A/'review/controller-netlist.xml';fresh=clone/'review/controller-netlist.xml';current=P/'review/controller-netlist.xml';raw=fresh.read_bytes();expected=raw.replace(str(clone).encode(),str(P).encode());check(raw.count(str(clone).encode())==8,'Fresh XML prefix count differs');check(current.read_bytes()==expected,'Current XML differs beyond the exact eight clone-root replacements');xo=ET.parse(oldxml).getroot();xf=ET.parse(fresh).getroot();xc=ET.parse(current).getroot();electrical={tag:ET.tostring(xo.find(tag))==ET.tostring(xc.find(tag))==ET.tostring(xf.find(tag)) for tag in ['components','libparts','nets']};check(all(electrical.values()),'XML electrical content differs')
norm=lambda data:data.replace(str(A).encode(),b'PROJECT_ROOT').replace(str(P).encode(),b'PROJECT_ROOT');libraries=norm(ET.tostring(xo.find('libraries')))==norm(ET.tostring(xc.find('libraries')));check(libraries,'XML library identities differ');ad,bd=copy.deepcopy(xo.find('design')),copy.deepcopy(xc.find('design'));dates={'baseline':ad.findtext('date'),'final':bd.findtext('date')};ad.find('date').text=bd.findtext('date');design=norm(ET.tostring(ad))==norm(ET.tostring(bd)).replace(b'R3-S6-P6',b'R3-S6-P5');check(design,'XML design metadata differs beyond exact title/root/date normalization');revs=[q.text for q in xc.findall('./design/sheet/title_block/rev')];check(len(revs)==7 and set(revs)=={'R3-S6-P6'},'Fresh XML does not contain exactly seven P6 titles')
metadata={'status':'PASS FRESH XML METADATA/SEMANTIC CLOSURE' if all(electrical.values()) and libraries and design and current.read_bytes()==expected else 'NOT PASSED','candidate_sha256':H,'fresh_cli_XML_sha256':sha(fresh),'current_main_XML_sha256':sha(current),'exact_root_prefix_replacements':8,'electrical_sections_unchanged':electrical,'library_identity_unchanged':libraries,'exact_design_metadata_normalization':design,'sheet_revisions':revs,'export_dates':dates,'allowed_changes':'Fresh native export date, exact P5→P6 title revision, and exact isolated-snapshot root rebasing to main project; no component/libpart/net edits'};(F/'XML-metadata-closure.json').write_text(json.dumps(metadata,indent=2)+'\n')
changed=[]
for path,h in full['source_sha256'].items():
 now=sha(Path(path))
 if now!=h:changed.append(path)
check(changed==[str(current)],'Unexpected source changes after full gate: '+str(changed));check(sha(P/'controller.kicad_pcb')==H,'Native PCB changed after qualification')
guard={path:sha(Path(path)) for path in full['source_sha256']}
for rel in ['review/printed-pad-legend.json','review/approved-small-vias.json','review/pad-wiring-map.csv','review/assembly-cpl-overrides.json','inputs/user-corrected-JLC_CPL.csv','review/edge-pad-map.json','review/h743-pin-map.json']:guard[str(P/rel)]=sha(P/rel)
evidence=[F/'native-gate-summary.json',F/'revision-geometry.json',F/'route-replay.json',F/'topology.json',F/'XML-metadata-closure.json',F/'erc.json',F/'drc.json',F/'refill-verification.json',F/'uncapped-copper-census.json',F/'advisories/advisory-clearance-census.json',F/'pin-audit-run.log',F/'native-audit.json',D/'join-throats-fafa9c3f.json',D/'join-throats-p5-constructive.json',D/'all-via-attachments-fafa9c3f.json',D/'ground-plane-attachments-fafa9c3f.json',PAD/'final-fafa9c3f-closure.json',PAD/'final-fafa9c3f-integration-proof.json',D/'final-fafa9c3f-exceptions.json',D/'east-rail-reference-independent.json',D/'j162-pruning-rebased-independent.json']
proof_modes={key:sum(bool(q.get(key)) for q in joins['all_screened_low_lens_width_contacts']) for key in ['strict_erosion_connected','constructive_full_width_path_connected','contained_target_width_virtual_stroke','one_nm_polygon_near_exact_nominal_width_connected']}
report={'status':'PASS FINAL SOURCE CAD AND COMPLETE COPPER-ATTACHMENT QUALIFICATION' if not errors else 'NOT PASSED','candidate_sha256':H,'baseline_sha256':full['baseline_sha256'],'errors':errors,'native_counts':full['native_counts'],'logical_pin_entries':full['independent_pin_entries'],'physical_live_nets':len(top['candidate']['nets']),'reference_planes_unchanged':all(q['loss_mm2']==q['gain_mm2']==0 for q in geo['facts']['reference_plane_delta']),'unchanged_footprints':geo['facts']['footprints'],'exact_USB_tracks':full['protected_USB_tracks'],'USB_width_mm':.1392,'ordinary_trace_floor_mm':.13,'foreign_trace_clearance_mm':.16,'all_vias':via['summary']['audited_vias'],'ground_vias':geo['facts']['ground_via_count'],'ground_pads':top['candidate']['ground_pad_count'],'operation_count':replay['operation_count'],'rail_operation_count':replay['rail_operation_count'],'copper_joins':{'summary':joins['summary'],'all_narrow_local_join_flags':0,'proof_modes':proof_modes,'negative_control':'The same exact script rejects both P5 HOST_TX_RAW .050mm throats and finds no unresolved final join','numerical_limits':joins['tolerances']},'via_attachments':via['summary'],'pad_attachments':{'counts':pad['counts'],'unresolved_functional_nominal_advisories':0,'all_pad_inventory_unchanged':True,'manufactured_land_limited_contacts':pad['intended_land_limited_contacts'],'qualified_local_contexts':{'VDDA':'Original small redundant corner graze has a separately proven full .200mm native-union route','J162':'The .450×.050mm endpoint flare does not set feed width; its sole .300mm incoming path passes the full nominal check'}},'ground_plane_attachments':{'plane_only_live_pads':4,'reference_plane_terminal_attachment_checks':303,'actual_modes':'FULL_SOLID; no thermal spokes are relied upon','annular_geometry':plane['annulus_exception'],'routing_layer_GND_fill':'In2 GND fill is supplemental and may form separate islands; every ground terminal independently passes all three solid reference planes','outside_terminal_proof_width_mm':.1302},'reference_dispositions':geo['facts']['reference_gap_classification'],'route_quality_before':quality['before_summary'],'route_quality_after':quality['after_summary'],'metadata_closure':metadata,'export_guard_source_sha256':guard,'evidence_sha256':{str(q):sha(q) for q in evidence},'qualification_limits':['Final all-route visual acceptance is owned by the independent visual reviewer; shape-count reductions alone are not acceptance','This source qualification permits final export generation under the exact hash guard; final Gerber/drill/BOM/CPL/package parity must still be verified','Native land and approved plated-annulus dimensions are intentionally distinguished from ordinary trace necks','Supplier process acceptance, load-current/thermal capacity, impedance, EMI, firmware and hardware performance are not certified by CAD checks']}
(F/'complete-source-qualification.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k in ['status','candidate_sha256','errors','native_counts','logical_pin_entries','physical_live_nets','all_vias','ground_vias','ground_pads','operation_count','rail_operation_count']},indent=2));raise SystemExit(bool(errors))
