#!/usr/bin/python3
"""Combine initial full gate with narrowly rerun failed stages on identical CAD."""
import hashlib,json
from pathlib import Path
D=Path(__file__).resolve().parent;F=D/'final-64ac0d81';C=D/'closure-64ac0d81';P=Path('/workspace/shared/storm32-redesign/controller-r3s-p6');H='64ac0d810d013d8a85491d8bd9672040b351f12e4e31b628105cdb2adbca5e90';sha=lambda q:hashlib.sha256(q.read_bytes()).hexdigest();read=lambda q:json.loads(q.read_text());full=read(F/'native-gate-summary.json');geom=read(C/'revision-geometry.json');current=read(C/'current-geometry/current-geometry-audit.json');replay=read(F/'route-replay.json');top=read(F/'topology.json');quality=read(F/'route-quality/route-quality-comparison.json');errors=[]
if sha(P/'controller.kicad_pcb')!=H:errors.append('Final source PCB differs from audited SHA')
if not full['source_stable'] or full['candidate_sha256']!=H:errors.append('Original full run lacked source stability')
if any(full['native_counts'].values()):errors.append('Original fresh native ERC/DRC/opens/parity not zero')
for name,row in full['processes'].items():
 if name not in ['geometry','current-geometry'] and row['returncode']:errors.append('Unclosed stage failed: '+name)
for name,doc in [('geometry',geom),('current-geometry',current),('route-replay',replay),('topology',top)]:
 if doc.get('errors'):errors.append(name+' retains errors')
 if doc.get('candidate_sha256',doc.get('native_sha256'))!=H:errors.append(name+' hash differs')
if read(P/'review/printed-pad-legend.json')['native_sha256']!=H or read(P/'review/approved-small-vias.json')['board_sha256']!=H:errors.append('Regenerated metadata does not bind final PCB')
files=[F/'native-gate-summary.json',C/'revision-geometry.json',C/'current-geometry/current-geometry-audit.json',F/'route-replay.json',F/'topology.json',F/'uncapped-copper-census.json',F/'advisories/advisory-clearance-census.json',F/'erc.json',F/'drc.json',F/'refill-verification.json',F/'pin-audit-run.log',F/'native-audit.json',F/'route-quality/route-quality-comparison.json',D/'final-64ac0d81-exceptions.json',D/'j162-pruning-rebased-independent.json',P/'review/printed-pad-legend.json',P/'review/approved-small-vias.json',D/'check_revision_geometry.py',D/'frozen-tools/check_current_geometry.py']
report={'status':'PASS P6 NUMERICAL CAD GATE; ALL-ROUTE VISUAL DISPOSITION PENDING' if not errors else 'NOT PASSED','candidate_sha256':H,'baseline_sha256':full['baseline_sha256'],'errors':errors,'native_counts':full['native_counts'],'independent_logical_pin_entries':full['independent_pin_entries'],'physical_all_net_count':len(top['candidate']['nets']),'new_padless_or_terminal_free_components':0,'protected_USB_tracks':full['protected_USB_tracks'],'USB_exact_width_mm':.1392,'ordinary_trace_floor_mm':.130,'foreign_trace_clearance_mm':.160,'ground_vias':geom['facts']['ground_via_count'],'operation_count':replay['operation_count'],'rail_operation_count':replay['rail_operation_count'],'reference_plane_delta':geom['facts']['reference_plane_delta'],'reference_gap_classification':geom['facts']['reference_gap_classification'],'closure':[{'stage':'current-geometry','reason':'Owner regenerated printed pad legend and unchanged seven-via inventory against final PCB SHA; actual footprints/pads/vias/rules unchanged','report':str(C/'current-geometry/current-geometry-audit.json')},{'stage':'geometry','reason':'USB_PRESENT_n raw centerline-only 6.15e-11mm2 residual is wholly within the baseline centerline-gap expanded by exactly 2nm. Symmetric edge/centerline Boolean-rounding treatment leaves zero residual; no area-only waiver. Same-net via exceptions use individually bounded isolated-antipad contours, never entire merged holes.','report':str(C/'revision-geometry.json')}],'route_quality_before':quality['before_summary'],'route_quality_after':quality['after_summary'],'route_quality_disposition':'Not accepted from segment/length reduction. Remaining coordinate-level features require the independent all-net visual reviewer; detour-window count can rise when chain partitioning changes.','evidence_sha256':{str(q):sha(q) for q in files},'source_stable_now':sha(P/'controller.kicad_pcb')==H,'limits':'Numerical CAD, geometry, electrical-topology and exact-operation consistency only. Complete-route visual acceptance, final fabrication/export consistency, supplier/process acceptance and physical hardware performance remain separate.'}
(C/'numerical-gate-closure.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:v for k,v in report.items() if k not in ['evidence_sha256','route_quality_before','route_quality_after']},indent=2));raise SystemExit(bool(errors))
