#!/usr/bin/python3
"""Bind parent-approved local route geometry packets to final native UUID deltas.

This does not grant approval. Invoke only with already approved HSE/GND packets.
The final added geometry must match complete adopted operations exactly; native
UUIDs may be regenerated by integration. No board is saved.
"""
import argparse,collections,hashlib,json,os
from pathlib import Path
os.environ.setdefault('KICAD_CONFIG_HOME','/tmp/controller-r3-kicad')
import pcbnew as p
BASELINE='6e2031b040ce8f3a534c2f73abb0091e25b3e6adcab982463264ad8898d65cf8';sha=lambda q:hashlib.sha256(q.read_bytes()).hexdigest();xy=lambda v:[v.x,v.y]
def native(path):
 b=p.LoadBoard(str(path));rows={}
 for t in b.GetTracks():
  if isinstance(t,p.PCB_VIA):continue
  r={'uuid':t.m_Uuid.AsString(),'type':t.GetClass(),'net':t.GetNetname(),'start_nm':xy(t.GetStart()),'end_nm':xy(t.GetEnd()),'width_nm':t.GetWidth(),'layer':t.GetLayerName()}
  if isinstance(t,p.PCB_ARC):r['mid_nm']=xy(t.GetMid())
  rows[r['uuid']]=r
 return rows

def approved(r):return {'uuid':r['id'],'type':'PCB_TRACK','net':r['net'],'start_nm':[round(v*1e6) for v in r['start']],'end_nm':[round(v*1e6) for v in r['end']],'width_nm':round(r['width_mm']*1e6),'layer':r['layer']}
def geometry(r):return (r['type'],r['net'],r['layer'],tuple(r['start_nm']),tuple(r['end_nm']),r['width_nm'],tuple(r.get('mid_nm',[])))
def critical(n):return n.rsplit('/',1)[-1].startswith(('USB_DP','USB_DM','HSE_','BUCK_','VCAP'))
def old_ground_scope(r):return r['type']!='PCB_VIA' and r['layer']=='F.Cu' and all(24500000<=q[0]<=27200000 and 12500000<=q[1]<=15500000 for q in [r['start_nm'],r['end_nm']])
def main():
 ap=argparse.ArgumentParser();ap.add_argument('--baseline',type=Path,required=True);ap.add_argument('--candidate',type=Path,required=True);ap.add_argument('--sha256',required=True);ap.add_argument('--hse-packet',type=Path,required=True);ap.add_argument('--ground-packet',type=Path,required=True);ap.add_argument('--out',type=Path,required=True);a=ap.parse_args();assert sha(a.baseline)==BASELINE and sha(a.candidate)==a.sha256;A=native(a.baseline);B=native(a.candidate);changes=[{'uuid':u,'before':A.get(u),'after':B.get(u)} for u in sorted(A.keys()|B.keys()) if A.get(u)!=B.get(u)];report={};accepted=[];errors=[];packets=[]
 for label,path,predicate in [('HSE',a.hse_packet,lambda n:critical(n)),('GND',a.ground_packet,lambda n:n=='GND')]:
  data=json.loads(path.read_text());assert data['source_sha256']==BASELINE;packets.append({'kind':label,'path':str(path),'sha256':sha(path)})
  actual=[c for c in changes if any(r and predicate(r['net']) for r in [c['before'],c['after']])];removed={c['uuid']:c['before'] for c in actual if c['before']};added=[c['after'] for c in actual if c['after']];expected_removed={};expected_added=[]
  for i,ch in enumerate(data['changes']):
   old=[approved(q) for q in ch['removed']];new=[approved(q) for q in ch['added']]
   if any(A.get(q['uuid'])!=q for q in old):errors.append(label+' approved source record differs: '+str(i))
   active=any(q['uuid'] in removed for q in old)
   if not active:continue
   if not all(q['uuid'] in removed for q in old):errors.append(label+' partially adopted local operation: '+str(i))
   expected_removed.update({q['uuid']:q for q in old});expected_added+=new;accepted.append({'kind':label,'packet':str(path),'operation_index':i,'operation':ch.get('operation'),'net':ch['net'],'layer':ch['layer'],'removed':len(old),'added':len(new),'local_return_review':ch.get('local_return_review'),'disposition':ch.get('disposition')})
  if removed!=expected_removed:errors.append(label+' source delta exceeds approved complete operations')
  if collections.Counter(geometry(q) for q in added)!=collections.Counter(geometry(q) for q in expected_added):errors.append(label+' added geometry differs from approved complete operations')
  if label=='HSE':report['critical_changes']=actual
  else:report['extended_ground_changes']=[c for c in actual if any(not old_ground_scope(r) for r in [c['before'],c['after']] if r)]
 if errors:raise AssertionError(errors)
 named=[]
 for l in ['F.Cu','B.Cu']:
  if any(r['kind']=='HSE' and r['net']=='HSE_OUT' and r['layer']==l for r in accepted):named.append({'net':'HSE_OUT','layer':l,'via_uuid':'489cb706-6cac-473a-8fb2-739065011aaf','isolated_reference_via_uuid':'060b047c-d688-49da-9f40-03b3572d6506'})
 report.update(baseline_sha256=BASELINE,candidate_sha256=a.sha256,approved_local_packets=packets,adopted_complete_operations=accepted,named_antipad_reference_exceptions=named,scope='Exact binding of previously parent-approved local proposals; all numerical native gates, electrical/return-path review, and visual gates remain required')
 assert sha(a.baseline)==BASELINE and sha(a.candidate)==a.sha256;a.out.parent.mkdir(parents=True,exist_ok=True);a.out.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'critical_changed_objects':len(report['critical_changes']),'extended_GND_changed_objects':len(report['extended_ground_changes']),'adopted_local_operations':len(accepted),'named_antipad_exceptions':named,'out':str(a.out)},indent=2))
if __name__=='__main__':main()
