"""Seal the complete ground-only source14 successor after source-bound checks."""
import pathlib,json,hashlib,shutil
H=pathlib.Path(__file__).resolve().parent;R=H.parents[2];D=H/'candidate06';S=H.parent/'rpm17/candidate01'
read=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();write=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n')
h=sha(D/'f722-heli.kicad_pcb');sh=sha(S/'f722-heli.kicad_pcb');assert h=='24121b0e46d9a71207cd21e7cf599412c00796d48eb9af5f63ffcf92e5f2ca42'and sh=='73dbae05954b8edec4143d91248bf38c40537f83e8f5f3fed51744105169d6c7'
s=read(D/'owner-summary.json');assert s['board_sha256']==h and s['drc']==s['drc-all']==dict(unconnected=14,errors=0,warnings=0)
for k in ['process','mechanical','parity','firmware']:assert s[k]['passed']and s[k]['board_sha256']==h
assert not read(D/'owner-drc-parity.json')['schematic_parity']and not s['critical']['faults']and s['critical']['connected_nets']==16
assert not any(s.get('violations')for s in read(D/'owner-erc.json').get('sheets',[]))
for f in ['entry-support-audit.json','power-audit.json','native-coordinated-integration.json','cumulative-source52-native-coordinated.json','stock-spi-binding.json','conditional-support-review/native-binding.json','all-signal-reference-ground-delta.json']:
 q=read(D/f);assert q['passed']and q['board_sha256']==h,(f,q.get('passed'),q.get('board_sha256'))
a=read(D/'entry-support-audit.json');assert a['new_track_endpoints_checked']==14 and a['new_tracks']==7 and a['new_vias']==1 and len(a['nets'])==28 and len(a['signal_groups'])==21
assert a['all156_full_footprints_exact']and a['all_non_GND_objects_exact']and a['all24_RPM_additive_objects_exact']and all(x['rejected']for x in a['negative_controls'])
c=read(D/'protection-actual-io.json');b=read(S/'protection-actual-io.json');passed=lambda x:{r['id']for r in x['checks']if r['complete_clamp_first_path_passes']};assert c['passed']==b['passed']==20 and c['total']==22 and passed(c)==passed(b)
r=read(D/'reference-comparison14.json');assert r['critical_object_geometry_identical']and all(v==0 for row in r['net_numeric_deltas_after_minus_before'].values()for v in row.values());g=read(D/'all-signal-reference-ground-delta.json');assert g['track_projection_count']==1259 and g['all_changed_projection_intersections_exactly_empty']
ties=read(D/'reference-snapshot/critical-reference.json')['GND_ties'];assert len(ties['accepted'])==117 and not ties['rejected']
inputs=read(D/'project-input-preservation.json');assert inputs['all_listed_non_board_project_inputs_byte_identical'];assert all(sha(D/x['path'])==x['sha256']==sha(S/x['path'])for x in inputs['files'])
for f in ['construct_separated_returns14.py','audit_separated_returns14.py','extra_separated_returns14.py','finish_separated_returns14.py','screen_quiet_return_alternatives14.py','seal_separated_returns14.py','validate_checkpoint.py']:
 shutil.copy2(H/f,D/(pathlib.Path(f).stem+'.used.py'))
for f in ['construct-separated-returns14.log','validate-separated-returns14.log','audit-separated-returns14.log','extra-separated-returns14.log','finish-separated-returns14.log','cumulative-separated-returns14.log']:
 shutil.copy2(H/f,D/f)
# Retain exact failed dedicated-tie attempt as a reference, without altering it.
failed=H/'candidate05';write(D/'failed-dedicated-R52-tie-evidence.json',dict(board=str(failed/'f722-heli.kicad_pcb'),board_sha256=sha(failed/'f722-heli.kicad_pcb'),native_summary=str(failed/'owner-summary.json'),native_summary_sha256=sha(failed/'owner-summary.json'),result=dict(unconnected=14,errors=2,warnings=0),failure='R52 moved +0.15 mm conflicts with fixed RPM_HV at actual native pad-to-track clearance. The candidate is preserved and not adopted.',superseded_reservation='dedicated-u12-ground15/three-plane-ties14-proposal.json'))
prov=read(D/'construction-provenance.json');assert len(prov['removed_source_records'])==9 and len(prov['added_records'])==8 and not prov['changed_pad_records']and not prov['changed_footprint_records']
write(D/'coordinated-change-receipt.json',dict(schema='f722-separated-U12-quiet-ground-native-reconstruction/v1',source_board_sha256=sh,board_sha256=h,changed_nets=['GND'],removed_source_objects=prov['removed_source_records'],added_objects=prov['added_records'],all156_full_footprints_exact=True,all_non_GND_objects_exact=True,all24_RPM_additive_objects_exact=True,all28_support_groups_restored=True,both_original_Y1_ground_paths_exact=True,U12_local_TVS_discharge_lead_separate_to_first_plane_tie=True,R51_local_return_separate_to_first_plane_tie=True,R52_C30_shared_quiet_return=True,raw_constructor_pending_flag_superseded_by_sealed_receipts=True,numerical_power_VCAP_applicable=False,ESD_AC_ADC_noise_qualified=False,owner_adoption_claimed=False))
(D/'conditional-support-review/NATIVE-GROUND-REVIEW.md').write_text('''# Candidate06 local discharge separation

Board SHA-256: `24121b0e46d9a71207cd21e7cf599412c00796d48eb9af5f63ffcf92e5f2ca42`. Direct source is sealed RPM14 `73dbae05954b8edec4143d91248bf38c40537f83e8f5f3fed51744105169d6c7`. The change removes nine GND tracks and adds seven GND tracks plus one ordinary tented 0.45/0.20 mm via. All 156 poses, actual pads, non-GND copper and all 24 additive RPM objects remain exact.

U12.2 now reaches its retained via (13.5984,13.4847) over 2.415435022 mm of 0.25 mm F.Cu. R51.2 independently reaches the new via (12.045672,13.000917) over 1.641086794 mm of 0.20 mm F.Cu. R52.2 reaches C30.2 over 1.150391238 mm of 0.20 mm F.Cu, then shares C30's existing 1.249986804 mm of 0.25 mm F.Cu and via (16.4574,15.8435). Its total is 2.400378042 mm. Actual pad entries, track joins and track-to-annulus entries are finite and checked.

The direct source's U12, R51 and R52 paths to their one shared via were 2.513660, 3.838234 and 2.517386 mm. U12/R51 shared 1.681160 mm of 0.25 mm trace as well as that via. The revised exact outer-layer contact graph proves the three new branches do not rejoin before their intended plane ties: U12's group contains only U12.2, R51's contains only R51.2, and R52's contains R52.2 and C30.2. This removes the previous local TVS discharge current path through eFuse-control copper. Common-plane coupling is still possible; no ESD equivalence or immunity is claimed.

Each of the nine reviewed GND ties has positive conductive annular contact of approximately 0.127629877 mm² to each saved In1/In4 GND fill. All 117 ground ties contact both planes. U5.8's existing 1.448296998 mm / 0.15 mm F.Cu return to (14.15,17.23), and U5.4 PGTH's own GND return, remain exact. Both original Y1 case grounds, C18/C19 load-cap returns, HSE paths, analog feed, U12.5 CORE entry and existing decoupling topology are exact. No dedicated U12 capacitor or AC return is newly assumed.

The new R51 via has 0.257313932 mm drill-to-SMT-mask clearance on the limiting B.Mask/Y1.2 feature, 0.921659142 mm drill-to-drill gap, and 0.138621490 mm limiting copper gap to SERVO1_MCU. Thus copper surplus over 0.127 mm is 0.011621490 mm; this exact modest margin is retained, not rounded into an extra process guarantee. Both faces are tented. Native process and geometry checks pass.

A bounded 0.20 mm F.Cu domain with the completed signals and poses fixed cannot connect R52 to R51's quiet tie or U5.8's pad/tie while preserving separate U12 copper. The complete C30 route is available. The attempted dedicated R52 tie required moving R52; its exact failed native candidate05 remains 14/2/0 due to two RPM_HV pad clearances. These are scoped structural negatives, not proof against every possible global reconstruction.

Read REPORT.md for the actual TPS259472ARPWR ILM and ADC_BEC return assessment. Shared C30 lead resistance is approximately 8.06975 mΩ under the conditional 15 µm/105°C/95% IACS model. At assumed total U5 current 2 A the maximum-gain illustration produces 3.22790 µV shared-lead drop; external 2 A loading alone does not bound total U5 load. The 5.5 A illustration gives 8.87672 µV and is not a continuous board rating. Via/plane resistance, ILM parasitic capacitance, ADC sampling/charging, noise and clamp transients remain outside that arithmetic.

All 1,259 unchanged signal trace/arc projections are disjoint from the only changed plane area: the new GND via's drilled hole, 0.031418080720 mm² on each plane. All raw critical reference deltas are exactly zero. All 20 prior actual signal-pad cuts, 21 complete signal groups and 28 support groups remain preserved. The cumulative source52 transaction includes the original R50 +0.25 mm inward move, SERVO/RPM routing, and this ground-only successor. Fresh numerical power/VCAP validation and signal/ADC/ESD qualification remain pending. This is a complete geometric prototype checkpoint for owner review.
''')
(D/'README.md').write_text('''# Complete source14 ground-return successor

Candidate06 retains 14 opens with zero native errors or warnings. Board SHA-256: `24121b0e46d9a71207cd21e7cf599412c00796d48eb9af5f63ffcf92e5f2ca42`.

U12 now has its own local discharge lead and first plane tie; R51 has a separate new tie, and R52 uses C30's existing quiet return. All poses and non-GND objects are exact to sealed RPM14. Finite entries, 28 support groups, 21 complete signal groups, 20 actual I/O cuts, native process/pose/parity/ERC and all-signal projection checks pass. The prior SERVO15 and RPM14 seals and failed dedicated-R52 candidate05 remain unchanged.

Read conditional-support-review/NATIVE-GROUND-REVIEW.md and REPORT.md. The R52/C30 shared conductor's DC sensitivity is small under explicit assumptions, while ADC/ILM transients, ESD/common-plane coupling, AC returns and fresh loaded power remain unqualified. This is a sealed geometric prototype candidate pending owner adoption. Direct source14 and cumulative source52 exact transactions are included.
''')
handoff=dict(schema='f722-native-route-handoff/v1',status='sealed_native_14_open_separated_U12_local_return_geometric_prototype_pending_owner_review',board_sha256=h,integration_source_sha256=sh,drc=dict(unconnected=14,errors=0,warnings=0,strict_schematic_parity=0,ERC_violations=0),pose_reference=str((D/'poses-native.json').relative_to(R)),coordinated=True,allowed_changed_nets=['GND'],all156_full_footprints_exact=True,all_non_GND_native_objects_exact=True,all24_RPM_additive_objects_exact=True,removed_source_objects=9,added_native_objects=8,new_tracks=7,new_GND_vias=1,finite_new_endpoints=14,support_groups_preserved=28,completed_signal_groups_preserved=21,actual_IO_cuts_passed=20,actual_IO_contracts=22,actual_IO_passes_exactly_preserved=True,critical_object_geometry_identical=True,critical_reference_deltas_exactly_zero=True,all1259_signal_track_projections_unchanged=True,ground_ties_to_both_saved_planes=117,cumulative_source52_transaction='cumulative-source52-transaction.json',cumulative_source52_pose_transform='cumulative-source52-footprint-transforms.json',U12_local_discharge_separate_until_plane=True,R52_C30_shared_return_conditional=True,conditional_support_review='conditional-support-review/NATIVE-GROUND-REVIEW.md',ILM_ADC_shared_return_review='conditional-support-review/REPORT.md',signal_quality_qualified=False,protection_transient_qualified=False,reference_AC_qualified=False,ADC_ILM_noise_qualified=False,numerical_power_VCAP_applicable=False,owner_adoption_pending=True)
handoff['files']={str(p.relative_to(D)):sha(p)for p in sorted(D.rglob('*'))if p.is_file()and p.name!='route-handoff.json'};write(D/'route-handoff.json',handoff);assert all(sha(D/p)==v for p,v in handoff['files'].items())
print(json.dumps(dict(board_sha256=h,handoff_sha256=sha(D/'route-handoff.json'),files=len(handoff['files']),remaining=14,status=handoff['status'])))
