import json,pathlib,hashlib,copy,shutil
H=pathlib.Path(__file__).resolve().parent;R=H.parents[2];A=H/'candidate04';D=H/'candidate05';S=H.parent/'port-b48/candidate03';read=lambda f:json.loads(pathlib.Path(f).read_text());sha=lambda f:hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest();write=lambda f,x:pathlib.Path(f).write_text(json.dumps(x,indent=2)+'\n');physical=lambda o:{k:v for k,v in o.items()if k!='net_code'}
old=read(A/'f722-heli.native.json');new=read(D/'f722-heli.native.json');base=read(S/'f722-heli.native.json');h=sha(D/'f722-heli.kicad_pcb');patch=read(D/'patch-primitive-receipt.json');assert h==new['board_sha256']==read(D/'native-refill.json')['board_sha256'];assert sha(A/'f722-heli.kicad_pcb')==old['board_sha256']==patch['source_board_sha256'];o0={o['uuid']:o for o in old['objects']};o1={o['uuid']:o for o in new['objects']};bb={o['uuid']:o for o in base['objects']};assert o0.keys()==o1.keys();changed={k for k in o0 if physical(o0[k])!=physical(o1[k])};assert changed==set(patch['changed_ids']);assert old['footprints']==new['footprints']
for k in ['edge_cuts','outline_with_npth','copper_layers','copper_layer_ids','board_thickness_mm']:assert old[k]==new[k]
prov=read(A/'construction-provenance.json');removed={o['uuid']for o in prov['removed_source_records']};added={o['uuid']for o in prov['added_records']};assert set(o1)-set(bb)==added and set(bb)-set(o1)==removed;assert all(physical(bb[k])==physical(o1[k])for k in set(bb)&set(o1)-changed)
proposal=read(A/'proposal.json');proposal['native_track_changes']=patch['changes'];proposal['allowed_changed_nets']=sorted(set(proposal['allowed_changed_nets'])|{'PORT_B_RX_MCU'});proposal['shared_return_patch_source_board_sha256']=old['board_sha256'];proposal['shared_return_patch_receipt_sha256']=sha(D/'shared-B-return-patch.json');write(D/'proposal.json',proposal)
prov.update(board_sha256=h,native_sha256=sha(D/'f722-heli.native.json'),proposal_sha256=sha(D/'proposal.json'),prior_A_proposal_sha256=sha(A/'proposal.json'),prior_A_constructor_sha256=prov['constructor_sha256'],constructor_sha256=patch['constructor_sha256'],source_stages=dict(B03=base['board_sha256'],A04=old['board_sha256']),retained_object_count=len(bb)-len(removed)-len(changed),changed_object_count=len(changed),changed_source_records=[dict(before=bb[k],after=o1[k])for k in sorted(changed)],changed_records=[o1[k]for k in sorted(changed)],changed_routes=[dict(net='PORT_B_RX_MCU',ids=sorted(changed),name='B-RX-reference-common-bend')],added_records=[o1[o['uuid']]for o in prov['added_records']],native_refill_performed=True)
write(D/'construction-provenance.json',prov)
for name in ['f722-heli.logical-route-map.json','declared-footprint-transforms.json','project-input-preservation.json']:
 q=read(A/name);q['board_sha256']=h;write(D/name,q)
shutil.copy2(A/'fixed-explicit-native-ids.json',D/'fixed-explicit-native-ids.json')
q=read(A/'cumulative50-transaction.json');q['board_sha256']=h;q['source_stages']={'B03':base['board_sha256'],'A04':old['board_sha256']};q['shared_B_RX_existing_object_changes']=patch['changes'];write(D/'cumulative50-transaction.json',q)
write(D/'composed-patch-review.json',dict(source_board_sha256=old['board_sha256'],board_sha256=h,changed_native_UUIDs=sorted(changed),all_other_native_objects_exact_except_net_code=True,all_footprints_exact=True,all_vias_exact=True,no_undeclared_additions_or_removals=True,patch_receipt_sha256=sha(D/'shared-B-return-patch.json'),raw_A04_return_report_sha256=sha(A/'combined-signal-reference-review.json')))
print(json.dumps(dict(board_sha256=h,source_B_objects=len(bb),retained_source_B_objects=prov['retained_object_count'],added=len(added),removed=len(removed),changed=len(changed))))
