import json,pathlib,hashlib,sys
H=pathlib.Path(__file__).resolve().parent;R=H.parents[2];A=H/'candidate03';B=H/'candidate04';read=lambda f:json.loads(pathlib.Path(f).read_text());sha=lambda f:hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest();sys.path.insert(0,str(R/'repo/f722-heli/layout-revision/signal-review/native'))
from check_critical_reference import ground_geometry
from check_signal_geometry import copper_entries
old=read(A/'f722-heli.native.json');new=read(B/'f722-heli.native.json');p0=read(A/'proposal.json');p1=read(B/'proposal.json');r0={r['name']:r for r in p0['routes']};r1={r['name']:r for r in p1['routes']};changed=[k for k in r0 if r0[k]!=r1[k]];assert set(changed)=={'tx-clamp-up','rx0-trunk-In3.Cu'};assert p0['vias']==p1['vias'];assert old['footprints']==new['footprints'];o0={o['uuid']:o for o in old['objects']};o1={o['uuid']:o for o in new['objects']};same=set(o0)&set(o1);physical=lambda o:{k:v for k,v in o.items()if k!='net_code'};assert all(physical(o0[k])==physical(o1[k])for k in same)
_,_,g0,_=ground_geometry(old,copper_entries(old));_,_,g1,_=ground_geometry(new,copper_entries(new));ground={l:dict(lost_area_mm2=g0[l].difference(g1[l]).area,gained_area_mm2=g1[l].difference(g0[l]).area,exact_set_equal=g0[l].equals(g1[l]))for l in ['In1.Cu','In4.Cu']};assert all(v['exact_set_equal']for v in ground.values())
f0=read(A/'new-route-reference-review.json');f1=read(B/'new-route-reference-review.json');assert f1['all_new_tracks_reference_complete_outside_explicit_own_via_windows']
out=dict(schema='f722-bounded-PORT-A-return-correction/v1',before_board_sha256=old['board_sha256'],board_sha256=new['board_sha256'],changed_route_families={k:dict(before=r0[k],after=r1[k])for k in changed},all_other_route_families_exact=True,all_via_definitions_exact=True,all_footprints_exact=True,all_shared_native_UUID_records_exact_except_net_code=True,removed_native_UUIDs=sorted(set(o0)-set(o1)),added_native_UUIDs=sorted(set(o1)-set(o0)),identity_note='Rebuilding from the same B03 source with a new proposal digest intentionally regenerates every new A/NRST UUID; native geometry changes are confined to the two named route families.',ground_plane_physical_sets=ground,raw_before_reference_summary=f0['summary'],raw_after_reference_summary=f1['summary'],raw_residual_receipt_sha256=sha(A/'new-route-reference-review.json'),after_receipt_sha256=sha(B/'new-route-reference-review.json'),no_polygon_normalization_or_threshold_rounding=True,AC_return_qualification=False)
(B/'return-correction-review.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(dict(changed=changed,ground=ground,all_new_reference_complete=True)))
