import pathlib,json,hashlib,shutil,collections
H=pathlib.Path(__file__).resolve().parent;ROOT=H.parents[2];S=ROOT/'ordinary-routing/candidate46';D=H/'candidate01'
read=lambda f:json.loads(pathlib.Path(f).read_text());sha=lambda f:hashlib.sha256(pathlib.Path(f).read_bytes()).hexdigest();write=lambda n,r:(D/n).write_text(json.dumps(r,indent=2)+'\n')
h=sha(D/'f722-heli.kicad_pcb');oldh=sha(S/'f722-heli.kicad_pcb');assert oldh=='87c5ced471edaf2e0ace382d4236bc1787efb869b7ae759c53d87ee76165c0cb';assert h=='f7d5731bb0bf1ad314aca6d507da004993671bce413fbdeba545083168e28161'
s=read(D/'owner-summary.json');assert s['board_sha256']==h and s['drc']==s['drc-all']=={'unconnected':32,'errors':0,'warnings':0};strict=read(D/'owner-drc-parity.json');assert not strict['schematic_parity']and not strict['violations'];assert all(s[k]['passed']for k in ['process','mechanical','parity','firmware']);assert s['critical']['connected_nets']==s['critical']['total_nets']==16 and not s['critical']['faults']and not s['critical']['missing_ground_returns'];assert not any(x['violations']for x in read(D/'owner-erc.json')['sheets'])
a=read(D/'entry-support-audit.json');assert a['passed']and all(a['gates'].values())and all(x['rejected']for x in a['negative_controls']);ref=read(D/'reference-comparison46.json');assert ref['critical_object_geometry_identical']and not ref['critical_object_differences'];assert all(v==0 for row in ref['net_numeric_deltas_after_minus_before'].values()for v in row.values());assert all(v['lost_GND_overlap_with_trace_width_mm2']==0 for x in ref['ground_fill_changes'].values()for v in x['critical_trace_proximity'].values());assert read(S/'reference-snapshot/critical-reference.json')['nets']==read(D/'reference-snapshot/critical-reference.json')['nets'];assert read(D/'native-coordinated-integration.json')['passed']
io=read(D/'protection-actual-io.json');prior=read(S/'protection-actual-io.json');passed=lambda r:{x['id']for x in r['checks']if x['complete_clamp_first_path_passes']};assert io['passed']==13 and prior['passed']==12 and io['total']==22 and passed(prior)<passed(io);assert passed(io)-passed(prior)=={'supplemental-07'};cuts={x['net']:x for x in io['checks']if x['net']in ['RPM_HV','SBUS_HV']};assert all(x['complete_clamp_first_path_passes']and x['source_target_physically_disconnected_after_removing_actual_pad_copper']for x in cuts.values());assert cuts['RPM_HV']['minimum_gap_measured_mm']==next(x['minimum_gap_measured_mm']for x in prior['checks']if x['net']=='RPM_HV');channels=len({(x['net'],x['clamp'])for x in io['checks']if x['complete_clamp_first_path_passes']});assert channels==11
assert s['supplemental']['passed']==s['supplemental']['total']==7;i2c=read(D/'i2c-geometry-review.json');assert all(i2c['nets'][n]['topology']['clean_complete_tree']for n in ['BARO_SCL','BARO_SDA']);assert i2c['I2C_final_status']=='NOT_QUALIFIED';assert read(D/'stock-spi-binding.json')['passed'];assert read(D/'parallel-ADC-planned-clearance.json')['passed']
p=read(D/'construction-provenance.json');m=read(D/'f722-heli.logical-route-map.json')['logical_route_map'];om=read(S/'f722-heli.logical-route-map.json')['logical_route_map'];remove={o['uuid']for o in p['removed_source_records']};assert len(remove)==4 and len(p['added_records'])==23;assert all(m.get(u)==v for u,v in om.items()if u not in remove);assert not remove&set(m)
before=read(S/'f722-heli.native.json');after=read(D/'f722-heli.native.json');old={o['uuid']:o for o in before['objects']};new={o['uuid']:o for o in after['objects']};assert all(new[u]==o for u,o in old.items()if u not in remove);assert len(old)==1950 and len(new)==1969;assert before['footprints']==after['footprints'];assert sha(S/'poses-native.json')==sha(D/'poses-native.json');assert read(D/'owner-native.json')==after
for row in read(D/'project-input-preservation.json')['files']:assert sha(S/row['path'])==sha(D/row['path'])==row['sha256']
write('coordinated-change-receipt.json',{'schema':'f722-explicit-coordinated-native-transaction/v1','passed':True,'source_board_sha256':oldh,'board_sha256':h,'source_native_sha256':sha(S/'f722-heli.native.json'),'candidate_native_sha256':sha(D/'f722-heli.native.json'),'source_map_sha256':sha(S/'f722-heli.logical-route-map.json'),'candidate_map_sha256':sha(D/'f722-heli.logical-route-map.json'),'allowed_changed_nets':['SBUS_HV','+3V3_CORE','ADC_DIV_MID'],'removed_source_records':p['removed_source_records'],'added_candidate_records':p['added_records'],'changed_pad_records':[],'changed_footprint_records':[],'removed_logical_owners':{u:om[u]for u in remove if u in om},'added_logical_owners':{o['uuid']:m[o['uuid']]for o in p['added_records']if o['uuid']in m},'all_other_source_objects_exact':1946,'all_retained_logical_owners_exact':True,'all_GND_pad_track_via_records_exact':True,'all_RPM_HV_records_and_cut_exact':True,'zone_definitions_exact_refill_performed':True,'complete_rewritten_entry_receipt':'entry-support-audit.json','complete_rewritten_entry_receipt_sha256':sha(D/'entry-support-audit.json'),'support_receipt':'power-audit.json','support_receipt_sha256':sha(D/'power-audit.json'),'actual_io_receipt':'protection-actual-io.json','actual_io_receipt_sha256':sha(D/'protection-actual-io.json'),'construction_provenance_sha256':sha(D/'construction-provenance.json'),'engine_success_claimed':False,'numerical_power_VCAP_applicable':False,'adoption_claimed':False})
write('f722-heli.import.json',{'schema':'f722-explicit-coordinated-native-construction-receipt/v1','passed':True,'source_sha256':oldh,'output_sha256':h,'construction_source_sha256':oldh,'construction_kind':'Complete Q2.3 to actual U16.2 SBUS_HV branch, with declared CORE via/two-feed replacement and one ADC_DIV_MID dogleg. No footprints or GND returns changed.','direct_engine_output':False,'engine_routing_succeeded':False,'engine_partial_geometry_adopted':False,'ses_engine_native_geometry_equal':False,'session_artifact':None,'coordinated_change_receipt':'coordinated-change-receipt.json','coordinated_change_receipt_sha256':sha(D/'coordinated-change-receipt.json'),'construction_provenance':'construction-provenance.json','construction_provenance_sha256':sha(D/'construction-provenance.json'),'logical_route_map_artifact':'f722-heli.logical-route-map.json','logical_route_map_sha256':sha(D/'f722-heli.logical-route-map.json'),'undeclared_native_changes':0,'source_objects_preserved_exact':1946,'objects_added':23,'objects_removed':4,'footprints_preserved':156,'reference_plane_refill_performed':True,'fresh_model_zero_control_performed':False,'numerical_power_VCAP_applicable':False})
write('power-revalidation-required.json',{'board_sha256':h,'source_board_sha256':oldh,'numerical_power_and_VCAP_applicability':False,'geometric_support_continuity_passed':True,'all28_support_groups_exact':True,'all_capacitor_pads_and_GND_return_objects_exact':True,'CORE_local_feed_review':a['CORE_local_feed_review'],'new_signal_through_vias':2,'moved_CORE_through_vias':1,'reference_planes_refilled':True,'reason':'CORE via/two0.20mm feeds changed, two SBUS through-vias added and reference fills changed. Fresh source-bound numerical power/VCAP applicability remains required; source43 historical numerical results are not inherited.','transient_qualification_claimed':False,'I2C_electrical_status':'NOT_QUALIFIED'})
helpers=['construct.py','audit.py','plan.py','native_geometry.py','joint_hypothesis.py','route_joint.py','refine_joint.py','refine_repairs.py','check_repairs.py','extra_gates.py','check_parallel_adc.py','seal.py']
for f in helpers:shutil.copy2(H/f,D/(pathlib.Path(f).stem+'.used.py'))
for f in ['local-repair-results.json','refined-local-repair-results.json','complete-joint-proposal.json','complete-joint-refined.json','planned_adc_obstacles.json']:shutil.copy2(H/f,D/f)
write('input-hashes.json',{str(x.relative_to(ROOT)):sha(x)for x in [*[H/f for f in helpers],S/'f722-heli.kicad_pcb',S/'f722-heli.native.json',S/'poses-native.json',S/'power-audit.json',ROOT/'ordinary-routing/dsm40-audits/audit_dsm40_entries_return.py',ROOT/'ordinary-routing/dsm41-audits/audit_dsm41_entries_return.py',ROOT/'integrated-routing/check_coordinated_integration.py',ROOT/'integrated-routing/verify_support_adoption.py']})
(D/'README.md').write_text(f'''# Isolated SBUS_HV closure from accepted candidate46

Native result:32 unfinished connections, zero geometric errors/warnings, strict schematic parity and ERC zero. Pending owner adoption; not manufacturing/flight qualified.

Fourteen0.127mm F.Cu/In3.Cu tracks and two0.45/0.20mm tented through-vias complete Q2.3→actual bonded U16.2. The SBUS_HV native graph now joins Q2.3,U16.2,R26.2. Actual U16.2 pad cut disconnects source and target with0.4208mm nominal outside-pad gap. The existing RPM_HV actual U16.1 cut remains exactly0.577505167861mm. Protection rises12→13/22 endpoint cases and10→11/20 channels; supplemental7/7.

The complete local reconstruction removes exactly four source objects: CORE via4ac2092d-48da-4042-9f80-6d638e3072d9; CORE tracks4c08b337-8a52-4b54-91f6-5521720e8561 ande712d11a-7e0e-4cb8-9a2a-275159c4142c; ADC_DIV_MID In2 tracka502a7e6-5c8c-4e37-91e0-b48000060a82. CORE via moves(17.110541,9.777898)→(17.1,9.84); both feeds keep0.20mm width and exactly the same remote source endpoints. Combined feed length0.947400815→0.966218588mm, increase0.018817774mm. No capacitor footprints or GND return objects move. ADC_DIV_MID receives four0.127mm replacement segments; complete coordinates and native IDs are in constructed-paths.json and coordinated-change-receipt.json.

Twenty tracks plus three vias are added;1946 source records,all156 footprints and all GND pad/track/via records remain exact. Both reference planes are refilled with unchanged definitions. All40 new track endpoints have finite proof, comprising two actual pad entries,18 full-width joins and8 actual annular entries. Eleven rejection controls pass. All28 native support pad partitions, both complete I2C trees and16 critical nets/returns pass. Raw critical-record comparison is true with zero reference metric deltas and zero lost-ground overlap with critical trace widths. Changed fill geometry is retained explicitly.

The narrow local portal geometry and route centering are nominal CAD evidence only, not manufacturing margin. The source CORE-via proposal had0.000489371mm minimum excess over its controlling native rule. Planned ADC_BUS obstacle clearance was also checked; this is a partial future compatibility receipt, not a merged ADC board qualification. Final ADC/C31 changes require source-bound merged native checks.

Current numerical power/VCAP and I2C electrical applicability remain pending. No historical source43 numerical qualification is inherited.

Source SHA256:{oldh}
Candidate SHA256:{h}
''')
files={str(x.relative_to(D)):sha(x)for x in D.rglob('*')if x.is_file()and x.name!='route-handoff.json'and x.suffix not in ['.log','.kicad_prl']}
write('route-handoff.json',{'schema':'f722-native-route-handoff/v1','status':'frozen_native_verified_32_open_complete_SBUS_HV_geometric_WIP_pending_owner_review','board_sha256':h,'integration_source_sha256':oldh,'drc':{'unconnected':32,'errors':0,'warnings':0,'strict_schematic_parity':0,'ERC_violations':0},'pose_reference':'ordinary-routing/candidate46/poses-native.json','coordinated':True,'allowed_changed_nets':['SBUS_HV','+3V3_CORE','ADC_DIV_MID'],'all_156_footprints_exact':True,'source_objects_retained_exact':1946,'removed_source_objects':4,'added_native_objects':23,'new_signal_vias':2,'replaced_CORE_vias':1,'completed_net':'SBUS_HV','new_logical_branches_complete':['SBUS_HV::P1'],'completed_terminals':['Q2.3','U16.2','R26.2'],'actual_io_passed':13,'actual_io_total':22,'actual_io_channels_passed':11,'actual_io_channels_total':20,'SBUS_actual_U16_cut_gap_mm':cuts['SBUS_HV']['minimum_gap_measured_mm'],'RPM_actual_U16_cut_gap_preserved_mm':cuts['RPM_HV']['minimum_gap_measured_mm'],'entry_support_audit':'entry-support-audit.json','entry_support_gates':len(a['gates']),'negative_controls':len(a['negative_controls']),'power_wrapper_schema':'f722-native-support-audit/v1','raw_critical_object_geometry_identical':True,'critical_reference_deltas_exactly_zero':True,'all_GND_native_pad_track_via_records_exact':True,'reference_plane_refill_performed':True,'both_BARO_clean_complete_trees':True,'I2C_electrical_status':'NOT_QUALIFIED','numerical_power_VCAP_applicable':False,'owner_adoption_pending':True,'direct_engine_output':False,'fresh_router_zero_replay_performed':False,'parallel_ADC_compatibility_scope':'Known unadopted R43/two-via/In3 proposal only; no final C31 or merged native qualification.','files':files})
for name,digest in read(D/'route-handoff.json')['files'].items():assert sha(D/name)==digest,name
print(json.dumps({'board_sha256':h,'handoff_sha256':sha(D/'route-handoff.json'),'sealed_files':len(files),'native_unconnected':32,'negative_controls':len(a['negative_controls'])}))
