import pathlib,json,hashlib,shutil,sys
HERE=pathlib.Path(__file__).resolve().parent;ROOT=HERE.parents[2];S=ROOT/'ordinary-routing/candidate47';D=HERE/'candidate01';sys.path.insert(0,str(ROOT/'integrated-routing'))
from verify_reference_window_classification import verify
read=lambda p:json.loads(pathlib.Path(p).read_text());sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();write=lambda n,r:(D/n).write_text(json.dumps(r,indent=2)+'\n')
h=sha(D/'f722-heli.kicad_pcb');oldh=sha(S/'f722-heli.kicad_pcb');assert oldh=='f7d5731bb0bf1ad314aca6d507da004993671bce413fbdeba545083168e28161'and h=='dcdd0e5655d098ceaffa7f40b6a21f1ca101429ac8eb142c50fa96df86697e68'
summary=read(D/'owner-summary.json');assert summary['board_sha256']==h and summary['drc']==summary['drc-all']=={'unconnected':30,'errors':0,'warnings':0};assert not read(D/'owner-drc-parity.json')['schematic_parity'];assert all(summary[k]['passed']for k in ['process','mechanical','parity','firmware']);assert summary['critical']['connected_nets']==summary['critical']['total_nets']==16 and not summary['critical']['faults']and not summary['critical']['missing_ground_returns'];assert not any(s['violations']for s in read(D/'owner-erc.json')['sheets'])
audit=read(D/'entry-support-audit.json');integration=read(D/'native-coordinated-integration.json');assert audit['passed']and integration['passed'];assert all(x['rejected']for x in audit['negative_controls']);assert all(x['board_sha256']==h for x in [audit,integration]);refpath=HERE/'reference-classification.json';rc=verify(refpath,oldh,h,D/'reference-comparison47.json',ROOT);shutil.copy2(refpath,D/'reference-region-review/reference-classification.json');write('reference-classification-binding.json',rc)
comp=read(D/'reference-comparison47.json');assert comp['critical_object_geometry_identical'];assert read(refpath)['exact_containment_predicate_disagreement_count']==2
io=read(D/'protection-actual-io.json');prior=read(S/'protection-actual-io.json');assert io['board_sha256']==h and io['passed']==prior['passed']==13 and io['total']==22;assert {x['id']for x in io['checks']if x['complete_clamp_first_path_passes']}=={x['id']for x in prior['checks']if x['complete_clamp_first_path_passes']}
i2c=read(D/'i2c-geometry-review.json');assert all(i2c['nets'][n]['topology']['clean_complete_tree']for n in ['BARO_SCL','BARO_SDA']);assert i2c['I2C_final_status']=='NOT_QUALIFIED'
prov=read(D/'construction-provenance.json');mapping=read(D/'f722-heli.logical-route-map.json')['logical_route_map'];oldmap=read(S/'f722-heli.logical-route-map.json')['logical_route_map'];removed={o['uuid']for o in prov['removed_source_records']};assert all(mapping.get(k)==v for k,v in oldmap.items()if k not in removed)
write('coordinated-change-receipt.json',{'schema':'f722-explicit-coordinated-native-transaction/v1','passed':True,'source_board_sha256':oldh,'board_sha256':h,'source_native_sha256':sha(S/'f722-heli.native.json'),'candidate_native_sha256':sha(D/'f722-heli.native.json'),'source_map_sha256':sha(S/'f722-heli.logical-route-map.json'),'candidate_map_sha256':sha(D/'f722-heli.logical-route-map.json'),'removed_source_records':prov['removed_source_records'],'added_candidate_records':prov['added_records'],'changed_pad_records':prov['changed_pad_records'],'changed_footprint_records':prov['changed_footprint_records'],'removed_logical_owners':{u:oldmap[u]for u in removed if u in oldmap},'added_logical_owners':{o['uuid']:mapping[o['uuid']]for o in prov['added_records']if o['uuid']in mapping},'all_other_source_objects_exact_except_runtime_net_code':prov['all_other_source_native_objects_exact_except_net_code'],'all_retained_logical_owners_exact':True,'all_other_native_board_track_via_arc_structures_exact':True,'complete_rewritten_entry_receipt':'entry-support-audit.json','complete_rewritten_entry_receipt_sha256':sha(D/'entry-support-audit.json'),'support_receipt':'power-audit.json','support_receipt_sha256':sha(D/'power-audit.json'),'actual_io_receipt':'protection-actual-io.json','actual_io_receipt_sha256':sha(D/'protection-actual-io.json'),'footprint_transform_receipt':'native-coordinated-integration.json','footprint_transform_receipt_sha256':sha(D/'native-coordinated-integration.json'),'reference_classification_receipt':'reference-region-review/reference-classification.json','reference_classification_receipt_sha256':sha(D/'reference-region-review/reference-classification.json'),'construction_provenance_sha256':sha(D/'construction-provenance.json'),'engine_success_claimed':False,'numerical_power_VCAP_applicable':False,'adoption_claimed':False})
write('f722-heli.import.json',{'schema':'f722-explicit-coordinated-native-construction-receipt/v1','passed':True,'source_sha256':oldh,'output_sha256':h,'construction_source_sha256':oldh,'construction_kind':'Complete ADC_BUS tree: R43 translated0.30mm, C31 inward native180degree pose;12tracks+2vias added and C31 old dedicatedGNDtrack/via removed.','direct_engine_output':False,'engine_routing_succeeded':False,'engine_partial_geometry_adopted':False,'ses_engine_native_geometry_equal':False,'session_artifact':None,'coordinated_change_receipt':'coordinated-change-receipt.json','coordinated_change_receipt_sha256':sha(D/'coordinated-change-receipt.json'),'construction_provenance':'construction-provenance.json','construction_provenance_sha256':sha(D/'construction-provenance.json'),'logical_route_map_artifact':'f722-heli.logical-route-map.json','logical_route_map_sha256':sha(D/'f722-heli.logical-route-map.json'),'undeclared_native_changes':0,'footprints_preserved':154,'footprints_transformed':2,'reference_plane_refill_performed':True,'fresh_model_zero_control_performed':False,'numerical_power_VCAP_applicable':False})
write('power-revalidation-required.json',{'board_sha256':h,'source_board_sha256':oldh,'numerical_power_and_VCAP_applicability':False,'geometric_support_continuity_passed':True,'all28_support_groups_exact':True,'C31_return_rebuilt':True,'reference_planes_refilled':True,'reason':'Two signal via antipads and removal of C31 old ground via change actual plane geometry. Current geometry does not inherit historical source43 power/VCAP qualification.','transient_qualification_claimed':False,'I2C_electrical_status':'NOT_QUALIFIED'})
for name in ['construct.py','audit.py','prepare_proposal.py','native_geometry.py','inspect_access.py','classify_reference_delta.py','electrical_screen.py','extra_gates.py','plot_final.py','seal.py']:shutil.copy2(HERE/name,D/(pathlib.Path(name).stem+'.used.py'))
sources=[S/'f722-heli.kicad_pcb',S/'f722-heli.native.json',S/'poses-native.json',S/'power-audit.json',S/'reference-snapshot/native-geometry.json',S/'reference-snapshot/native-signals.json',S/'reference-snapshot/critical-reference.json',ROOT/'ordinary-routing/dsm40-audits/audit_dsm40_entries_return.py',ROOT/'ordinary-routing/dsm41-audits/audit_dsm41_entries_return.py',ROOT/'integrated-routing/verify_footprint_transforms.py',ROOT/'integrated-routing/check_coordinated_integration.py',ROOT/'integrated-routing/verify_support_adoption.py',ROOT/'integrated-routing/verify_reference_window_classification.py']+[HERE/name for name in ['construct.py','audit.py','prepare_proposal.py','native_geometry.py','inspect_access.py','classify_reference_delta.py','electrical_screen.py','extra_gates.py','plot_final.py','seal.py']];write('input-hashes.json',{str(p.relative_to(ROOT)):sha(p)for p in sources});write('source-reference-bindings.json',{'source_board_sha256':oldh,'board_sha256':h,'source_snapshot_files':{str(p.relative_to(ROOT)):sha(p)for p in sources if 'reference-snapshot'in str(p)},'fresh_candidate_snapshot_files':{str(p.relative_to(D)):sha(p)for p in (D/'reference-snapshot').glob('*.json')}})
(D/'README.md').write_text(f'''# Complete isolated ADC_BUS tree from candidate47

Native candidate:30 opens,0 errors,0 warnings; strict schematic parity and pairedERC0. Source {oldh}; candidate {h}. Owner adoption is pending; this is geometric WIP, not manufacturing/flight qualification.

C31 keeps220nF/16V/X7R and its native0402 identity. It moves from B(14,24.1),0degrees to B(15.9,8),180degrees. Its ADC branch is4.283655mm, and the complete B.Cu C31-to-U1.10 path is6.798656mm with no barrel transition. Its0.25mm ground lead is1.379246mm to retained GNDvia(16.4252,7.0556); exact finite annulus/corridor entries to both saved ground planes pass. The old dedicated C31 ground track and via are removed only after proving no other non-plane attachment. R43 keeps16.0k/0.1percent and moves F(22.5,17.6)→(22.5,17.9),0degrees, opening the ADC portal. The other154 complete footprint structures remain exact. Native pose transforms, body/land/courtyard, mask/drill, header and manufacturing-process gates pass.

Twelve tracks and two tented0.45/0.20mm through-vias are added. Vias:(16.99,12.24) and(22,17.27). Tracks use F.Cu,B.Cu,In3.Cu, minimum0.127mm. All prior signal/supply copper is retained. Source47 SBUS/CORE/ADC_DIV repair and actual protection13/22 cases,11/20 channels remain intact. Native graphs connect C31.1,R42.2,R43.1,U1.10 as one complete net. Both I2C trees, all16 critical nets/returns and all28 support pad partitions pass.

Every one of24 new track endpoints has finite full-width pad, exact round-ended join or actual-annular proof. The retained ADC_DIV_MID tail into movedR43.2 has its own strict full-width entry. The retained ADC_BUS diagonal ends at an exact full-width join to the new vertical entry; its direct moved-pad section remains false in the composite receipt instead of being relabeled as a direct entry. Five refusal controls pass.

Reference copper is exactly identical. Raw BARO_SCL refill differences remain−4.3543590200201265e−7mm centerline and−2.63311599746352e−8mm² width area. The fresh source-bound classifier finds all changed critical projection geometry within unchanged own-via windows; exact missing-centerline equality and actual-hole containment remainfalse with2 boundary-predicate disagreements. No geometry normalization was applied. Whole-plane changes and new holes remain real and need current power/VCAP assessment.

The ADC-specific reference screen reports complete centerline coverage outside the two explicit own-via windows, with two In3 width-edge fragments totaling6.0864812525609e−5mm² outside them retained as a limitation. It does not claim complete full-width reference coverage or EMC qualification.

The conditional electrical screen preserves the divider gain0.32 and Thevenin impedance21.76kOhm. Nominal220nF filtering gives4.7872ms and33.246Hz. Pinned stock code uses480 ADC sample cycles and PCLK/8; at stock216MHz/PCLK2=108MHz, sampling is35.556us versus1.887us for the conservative datasheet sample-switch/source-resistance acquisition estimate. Effective capacitance over all corners, noise pickup, load/source switching, total ADC error and bench settling remain to be qualified. The51.35mm inner and56.09mm back-layer alternatives are diagnostic files only and are not used.

Primary sources: [ST DS11853 Rev9, ADC Table67/Equation1](https://www.st.com/resource/en/datasheet/stm32f722re.pdf); [pinned stock ADC source](https://github.com/rotorflight/rotorflight-firmware/blob/ba6c7e3e328b91a549bf6ca87c9eadd7006b6d94/src/main/drivers/adc_stm32f7xx.c). Actual values, source hashes and conditional parasitic sensitivity assumptions are in adc-electrical-screen.json. placement-detail.png was visually inspected and shows the actual native C31/R43 lands, routes and courtyards; owner fresh full-board previews remain required.
''')
files={str(p.relative_to(D)):sha(p)for p in D.rglob('*')if p.is_file()and p.name!='route-handoff.json'and p.suffix not in ['.log','.kicad_prl']}
ref=read(refpath);handoff={'schema':'f722-native-route-handoff/v1','status':'frozen_native_verified_30_open_complete_ADC_BUS_geometric_WIP_pending_owner_review','board_sha256':h,'integration_source_sha256':oldh,'drc':{'unconnected':30,'errors':0,'warnings':0,'strict_schematic_parity':0,'ERC_violations':0},'pose_reference':str((D/'poses-native.json').relative_to(ROOT)),'declared_footprint_transforms':'declared-footprint-transforms.json','coordinated':True,'allowed_changed_nets':['ADC_BUS','GND','ADC_DIV_MID'],'all_other_154_footprints_exact':True,'removed_source_objects':2,'added_native_objects':14,'new_signal_vias':2,'removed_dedicated_GND_vias':1,'completed_net':'ADC_BUS','completed_terminals':['C31.1','R42.2','R43.1','U1.10'],'actual_io_passed':13,'actual_io_total':22,'actual_io_channels_passed':11,'actual_io_channels_total':20,'entry_support_audit':'entry-support-audit.json','entry_support_gates':len(audit['gates']),'negative_controls':len(audit['negative_controls'])+len(ref['rejection_controls']),'power_wrapper_schema':'f722-native-support-audit/v1','raw_critical_object_geometry_identical':True,'critical_reference_deltas_exactly_zero':False,'reference_window_classification':'reference-region-review/reference-classification.json','reference_window_classification_sha256':sha(D/'reference-region-review/reference-classification.json'),'missing_centerline_geometries_exactly_equal':False,'actual_hole_predicate_disagreements':2,'both_BARO_clean_complete_trees':True,'I2C_electrical_status':'NOT_QUALIFIED','numerical_power_VCAP_applicable':False,'ADC_functional_qualification':False,'owner_adoption_pending':True,'direct_engine_output':False,'fresh_router_zero_replay_performed':False,'files':files};write('route-handoff.json',handoff);assert all(sha(D/name)==digest for name,digest in files.items());print(json.dumps({'board_sha256':h,'handoff_sha256':sha(D/'route-handoff.json'),'sealed_files':len(files),'native_unconnected':30,'negative_controls':handoff['negative_controls']}))
