import os,json,hashlib,collections,datetime
from pathlib import Path
os.environ.setdefault('KICAD_CONFIG_HOME','/tmp/controller-r3-kicad')
import pcbnew as p
D=Path(__file__).resolve().parents[2];R=D.parent;P=R.parent/'controller-r3s-p6';A=R.parent/'controller-r3s-p5';F=D/'final-cf16a6f5';H='cf16a6f5ceae65aad217e29eef23a60dbc8f15af743b363df03aa5a42c9c71dc';sha=lambda q:hashlib.sha256(q.read_bytes()).hexdigest();oldpath=R/'controller-r3s-p5-independent-validation/final-6e2031b0/advisories/advisory-clearance-census.json';newpath=F/'advisories/advisory-clearance-census.json';old=json.loads(oldpath.read_text());new=json.loads(newpath.read_text());supplierpath=Path('/workspace/scratch/8a35c1f26232/jlcdfm-p6-review/mask-warning-comparison.json');supplier=json.loads(supplierpath.read_text());assert sha(P/'controller.kicad_pcb')==new['native_sha256']==H and old['native_sha256']==sha(A/'controller.kicad_pcb');ob=p.LoadBoard(str(A/'controller.kicad_pcb'));nb=p.LoadBoard(str(P/'controller.kicad_pcb'));oi={q.m_Uuid.AsString():q for q in ob.GetTracks()};ni={q.m_Uuid.AsString():q for q in nb.GetTracks()}
def record(q,objects,mask):
 t=objects[q['object_uuid']];return {**q,'trace_width_mm':t.GetWidth()/1e6 if not isinstance(t,p.PCB_VIA) else None,'start_mm':[t.GetStart().x/1e6,t.GetStart().y/1e6],'end_mm':[t.GetEnd().x/1e6,t.GetEnd().y/1e6],'mask_bounds_mm':mask['regions'][q['region']]['native_bounds_mm']}
rows=[]
for owners,net,gap in [(['J114.1'],'EXT_SPI_CS',.1),(['J115.1'],'EXT_SPI_CS',.1),(['J140.1'],'OUT5',.125)]:
 oldm=old['mask_results']['F.Mask'];newm=new['mask_results']['F.Mask'];before=[record(q,oi,oldm) for q in oldm['all_pairs_below_0200mm'] if not q['same_net'] and q['owners']==owners and q['object_net']==net];after=[record(q,ni,newm) for q in newm['all_pairs_below_0200mm'] if not q['same_net'] and q['owners']==owners and q['object_net']==net];matches=[q for q in after if q['trace_width_mm']==.15 and q['gap_mm']==gap];assert matches
 predecessors=[q for q in before if q['trace_width_mm']==.13 and q['gap_mm']==round(gap+.01,6)];assert predecessors
 rows.append({'owners':owners,'net':net,'display_consistent_gap_mil':round(gap/.0254,2),'width_mm':.15,'current_gap_mm':gap,'matching_native_tracks':matches,'P5_corresponding_0130mm_segments':predecessors,'P5_corresponding_segment_gap_mm':round(gap+.01,6),'whole_owner_net_minimum_P5_mm':min(q['gap_mm'] for q in before),'whole_owner_net_minimum_P6_mm':min(q['gap_mm'] for q in after),'margin_above_official_0090mm_mm':round(gap-.09,6)})
sides={}
for name,m in new['mask_results'].items():
 assert not m['foreign_overlaps'] and not m['foreign_below_0100mm'] and m['minimum_foreign_clearance_mm']>=.1
 sides[name]={'mask_region_count':m['polygon_count'],'minimum_foreign_gap_mm':m['minimum_foreign_clearance_mm'],'official_floor_mm':.09,'minimum_design_margin_mm':round(m['minimum_foreign_clearance_mm']-.09,6),'foreign_overlaps':0,'foreign_below_0100mm':0,'foreign_below_0090mm':0,'all_foreign_pairs_below_0200mm':len([q for q in m['all_pairs_below_0200mm'] if not q['same_net']])}
mask_parity=json.loads((F/'export-parity/exact-gerber-regeneration.json').read_text());assert not mask_parity['errors'];assert all(q['invariant_after_exact_title_revision_and_two_date_lines'] for q in mask_parity['conserved_exports'] if 'Mask' in q['file'])
report={'status':'PASS SOURCE-BOUND MASK PROCESS-FLOOR CORRELATION','native_sha256':H,'baseline_sha256':old['native_sha256'],'supplier_warning_comparison':supplier,'supplier_warning_comparison_sha256':sha(supplierpath),'official_process_floor':{'clearance_mm':.09,'source':'https://jlcpcb.com/capabilities/Capabilities','section':'Soldermask / Soldermask Expansion','verified_date_UTC':'2026-10-03','statement':'Keep at least 0.09 mm clearance between soldermask openings and neighboring traces.'},'native_uncapped_census':sides,'mask_aperture_geometry_unchanged_P5_to_P6':True,'added_display_tuple_consistent_native_sites':rows,'front_new_physical_site_count':3,'front_native_track_pairs_at_these_sites':sum(len(q['matching_native_tracks']) for q in rows),'evidence_sha256':{str(oldpath):sha(oldpath),str(newpath):sha(newpath),str(F/'export-parity/exact-gerber-regeneration.json'):sha(F/'export-parity/exact-gerber-regeneration.json')},'resolution':'All supplier mask advisories are bounded by the uncapped exact-source census: no mask opening overlaps foreign trace/via copper and every measured foreign gap is at least0.100mm, exceeding the applicable0.090mm requirement. Width homogenization from0.130 to0.150mm explains the three consistent front additions; no geometry change is needed to meet this process floor.','limits':'Supplier rounded display tuples and aperture names do not uniquely identify native objects; the three sites are consistent candidates, not an invented supplier-ID mapping. Advisory counts are not direct native pair counts because segmented/overlapping paths may group differently. Printed colour thresholds do not replace the explicit process requirement. No purchase or PCBA production approval is implied.'};report['measurement_scope']='Native F/B mask-opening polygons versus all nearby foreign-net outer-layer tracks and vias, matching the supplier mask-to-trace category; direct pad geometry is separately qualified.';assert sha(P/'controller.kicad_pcb')==H;(F/'supplier-correlation/mask-process-closure.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({'status':report['status'],'sides':sides,'native_sites':[(q['owners'],q['net'],q['current_gap_mm']) for q in rows]},indent=2))
