import pathlib,json,sys,hashlib
H=pathlib.Path(__file__).resolve().parent;R=H.parents[2];sys.path.insert(0,str(R/'repo/f722-heli/layout-revision/signal-review/native'))
from check_signal_geometry import copper_entries,centerline,poly
from check_critical_reference import ground_geometry,REFERENCE
read=lambda p:json.loads(pathlib.Path(p).read_text());sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
stages={s:R/'ordinary-routing'/s for s in ['candidate49','candidate50']};data={s:read(p/'f722-heli.native.json')for s,p in stages.items()}
for s,p in stages.items():assert sha(p/'f722-heli.kicad_pcb')==data[s]['board_sha256']
obs={s:{o['uuid']:o for o in d['objects']if o['net']=='ADC_BUS'}for s,d in data.items()};physical=lambda o:{k:v for k,v in o.items()if k!='net_code'};exact={u:physical(o)for u,o in obs['candidate49'].items()}=={u:physical(o)for u,o in obs['candidate50'].items()};assert exact
planes={s:ground_geometry(d,copper_entries(d))[2]for s,d in data.items()};rows=[]
for u,t in obs['candidate49'].items():
 if t['kind']not in['track','arc']:continue
 layer=next(iter(t['copper']));ref=REFERENCE[layer];line=centerline(t);width=poly(t['copper'][layer]);miss={s:(line.difference(planes[s][ref]),width.difference(planes[s][ref]))for s in stages};before,after=miss['candidate49'],miss['candidate50']
 rows.append({'uuid':u,'layer':layer,'reference_layer':ref,'source49_missing_centerline_mm':before[0].length,'source50_missing_centerline_mm':after[0].length,'source49_missing_width_mm2':before[1].area,'source50_missing_width_mm2':after[1].area,'missing_centerline_geometry_equal':before[0].equals(after[0]),'missing_width_geometry_equal':before[1].equals(after[1]),'added_missing_centerline_mm':after[0].difference(before[0]).length,'added_missing_width_mm2':after[1].difference(before[1]).area,'removed_missing_centerline_mm':before[0].difference(after[0]).length,'removed_missing_width_mm2':before[1].difference(after[1]).area,'source50_missing_width_bounds':list(after[1].bounds)if not after[1].is_empty else None})
out={'schema':'f722-ADC_BUS-reference49-to50/v1','source49_board_sha256':data['candidate49']['board_sha256'],'source50_board_sha256':data['candidate50']['board_sha256'],'ADC_BUS_native_objects_exact':exact,'tracks':rows,'all_missing_geometries_exactly_equal':all(r['missing_centerline_geometry_equal']and r['missing_width_geometry_equal']for r in rows),'totals':{k:sum(r[k]for r in rows)for k in ['source49_missing_centerline_mm','source50_missing_centerline_mm','source49_missing_width_mm2','source50_missing_width_mm2','added_missing_centerline_mm','added_missing_width_mm2','removed_missing_centerline_mm','removed_missing_width_mm2']},'sources':{str(p.relative_to(R)):sha(p)for s,d in stages.items()for p in [d/'f722-heli.kicad_pcb',d/'f722-heli.native.json']},'limits':'Actual saved GND union minus every native drill on actual span, adjacent-plane centerline and complete-width projection. No snapping, tolerance suppression or polygon repair. Exact acquisition-branch geometry permits source49 arithmetic identity; power/noise/ADC performance remain unqualified.'}
(H/'ADC_BUS-reference50.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({k:v for k,v in out.items()if k not in ['tracks','sources']}))
